# Copyright (c) Microsoft Corporation. All rights reserved.

# AzuredigitaltwinsClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict, List
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class AddModelsInput:
    """Add Model"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ListModelsResponse:
    """Response for List Models"""

    value: Optional[List[Dict[str, Any]]] = None
    """Array values."""
    continuation_token: Optional[str] = None
    """Continuation Token the next page of Twin Relationship."""
    next_link: Optional[str] = None
    """URL to get the next page of Models."""


@dataclass
class GetModelByIdResponse:
    """Response for Get Model By Id"""

    id: Optional[str] = None
    """The id of the model as specified in the model definition."""
    upload_time: Optional[str] = None
    """The time the model was uploaded to the service."""
    decommissioned: Optional[bool] = None
    """
    Indicates if the model is decommissioned. Decommissioned models cannot be
    referenced by newly created digital twins.
    """
    model: Optional[Dict[str, Any]] = None
    """Model reference."""


@dataclass
class TwinResult:
    """Response for Get Twin by Id"""

    result: Optional[str] = None
    """Results From the Twin."""


@dataclass
class GetComponentResult:
    """Response for Get Component"""

    result: Optional[str] = None
    """Results From the Twin."""


@dataclass
class TwinRelationship:
    """Response for Get Relationship by Id"""

    source_id: Optional[str] = None
    """Source Id."""
    relationship_id: Optional[str] = None
    """Relationship Id."""
    target_id: Optional[str] = None
    """Target Id."""
    relationship_name: Optional[str] = None
    """Relationship Name."""
    etag: Optional[str] = None
    """E Tag Link."""
    additional_properties: Optional[str] = None
    """Property Values."""


@dataclass
class ListIncomingRelationshipsResponse:
    """Response for List Incoming Relationships"""

    value: Optional[List[IncomingRelationship]] = None
    """The collection of Incoming relationships."""
    continuation_token: Optional[str] = None
    """Continuation Token the next page of Twin Relationship."""
    next_link: Optional[str] = None
    """URL to get the next page of Incoming Relationship."""


@dataclass
class SendTelemetryInput:
    """Send Telemetry"""

    value: Optional[str] = None
    """Send Telemetry Inputs."""


@dataclass
class SendComponentTelemetryInput:
    """Send Component Telemetry"""

    value: Optional[str] = None
    """Send Component Telemetry Inputs."""


@dataclass
class ListRelationshipsResponse:
    """Response for List Relationships"""

    value: Optional[List[TwinRelationship]] = None
    """The collection of twin relationships."""
    continuation_token: Optional[str] = None
    """Continuation Token the next page of Twin Relationship."""
    next_link: Optional[str] = None
    """URL to get the next page of Twin Relationship."""


@dataclass
class QueryTwinsInput:
    """Query API"""

    query: Optional[str] = None
    """Query the Twins."""
    continuation_token: Optional[str] = None
    """Link to get next set of items."""


@dataclass
class QueryResult:
    """Response for Query API"""

    value: Optional[str] = None
    """Results From the Twin."""
    continuation_token: Optional[str] = None
    """Link to get next set of items."""


@dataclass
class IncomingRelationship:
    """Definition: IncomingRelationship"""

    source_id: Optional[str] = None
    """Source Id."""
    relationship_id: Optional[str] = None
    """Relationship Id."""
    relationship_name: Optional[str] = None
    """Relationship Name."""
    relationship_link: Optional[str] = None
    """Relationship Link."""


# Client Class

class AzuredigitaltwinsClient(ConnectorClientBase):
    """Typed client for azuredigitaltwins connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a AzuredigitaltwinsClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "azuredigitaltwins"

    async def add_models_async(
        self,
        input: AddModelsInput,
    ):
        """
        Add Model

        Uploads one or more models. When any error occurs, no models are
        uploaded.
        """
        path = f"{self._connection_runtime_url}/models"

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_models_async(
        self,
        dependencies_for: Optional[str] = None,
        include_model_definition: Optional[str] = None,
    ):
        """
        List Models

        Retrieves model metadata and, optionally, model definitions.
        """
        path = f"{self._connection_runtime_url}/models"
        query_params = []
        if dependencies_for is not None:
            value = str(dependencies_for)
            if isinstance(dependencies_for, bool):
                value = value.lower()
            query_params.append(f"dependenciesFor={quote(value)}")
        if include_model_definition is not None:
            value = str(include_model_definition)
            if isinstance(include_model_definition, bool):
                value = value.lower()
            query_params.append(f"includeModelDefinition={quote(value)}")
        if query_params:
            path += '?' + '&'.join(query_params)

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_model_async(
        self,
        modelid: str,
    ):
        """
        Delete Model

        Deletes a model. A model can only be deleted if no other models
        reference it.
        """
        path = f"{self._connection_runtime_url}/models/{str(modelid)}"

        await self.http_client.send_async("DELETE", path, body=None)

    async def get_model_by_id_async(
        self,
        modelid: str,
        include_model_definition: Optional[str] = None,
    ):
        """
        Get Model By Id

        Retrieves model metadata and, optionally, the model definition.
        """
        path = f"{self._connection_runtime_url}/models/{str(modelid)}"
        query_params = []
        if include_model_definition is not None:
            value = str(include_model_definition)
            if isinstance(include_model_definition, bool):
                value = value.lower()
            query_params.append(f"includeModelDefinition={quote(value)}")
        if query_params:
            path += '?' + '&'.join(query_params)

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def update_model_async(
        self,
        modelid: str,
    ):
        """
        Update Model's Property

        Updates the metadata for a model.
        """
        path = f"{self._connection_runtime_url}/models/{str(modelid)}"

        await self.http_client.send_async("PATCH", path, body=None)

    async def get_twin_by_id_async(
        self,
        twinid: str,
    ):
        """
        Get Twin by Id

        Retrieves a digital twin and its data.
        """
        path = f"{self._connection_runtime_url}/digitaltwins/{str(twinid)}"

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_twin_async(
        self,
        twinid: str,
    ):
        """
        Delete Twin

        Deletes a digital twin. All relationships referencing the digital twin
        must already be deleted.
        """
        path = f"{self._connection_runtime_url}/digitaltwins/{str(twinid)}"

        await self.http_client.send_async("DELETE", path, body=None)

    async def add_twin_async(
        self,
        twinid: str,
    ):
        """
        Add Twin

        Adds or replaces a digital twin.
        """
        path = f"{self._connection_runtime_url}/digitaltwins/{str(twinid)}"

        response = await self.http_client.send_async("PUT", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def update_twin_async(
        self,
        twinid: str,
    ):
        """
        Update Twin

        Updates properties on a twin.
        """
        path = f"{self._connection_runtime_url}/digitaltwins/{str(twinid)}"

        await self.http_client.send_async("PATCH", path, body=None)

    async def get_component_async(
        self,
        twinid: str,
        component_path: str,
    ):
        """
        Get Component

        Retrieves a component from a digital twin.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/components/{str(component_path)}"
        )

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def update_component_async(
        self,
        twinid: str,
        component_path: str,
    ):
        """
        Update Component

        Updates integer properties on a component of a twin.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/components/{str(component_path)}"
        )

        await self.http_client.send_async("PATCH", path, body=None)

    async def get_relationship_by_id_async(
        self,
        twinid: str,
        relationship_id: str,
    ):
        """
        Get Relationship by Id

        Retrieves a relationship between two digital twins.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/relationships/{str(relationship_id)}"
        )

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_relationship_async(
        self,
        twinid: str,
        relationship_id: str,
    ):
        """
        Delete Relationship

        Deletes a relationship between two digital twins.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/relationships/{str(relationship_id)}"
        )

        await self.http_client.send_async("DELETE", path, body=None)

    async def add_relationship_async(
        self,
        twinid: str,
        relationship_id: str,
    ):
        """
        Add Relationship

        Adds a relationship between two digital twins.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/relationships/{str(relationship_id)}"
        )

        response = await self.http_client.send_async("PUT", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def update_relationship_async(
        self,
        twinid: str,
        relationship_id: str,
    ):
        """
        Update Relationship

        Updates integer properties on a relationship between two digital twins.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/relationships/{str(relationship_id)}"
        )

        await self.http_client.send_async("PATCH", path, body=None)

    async def list_incoming_relationships_async(
        self,
        twinid: str,
    ):
        """
        List Incoming Relationships

        Retrieves all incoming relationships for a digital twin.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/incomingrelationships"
        )

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def send_telemetry_async(
        self,
        input: SendTelemetryInput,
        twinid: str,
    ):
        """
        Send Telemetry

        Sends telemetry on behalf of a digital twin.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/telemetry"
        )

        await self.http_client.send_async("POST", path, body=input)

    async def send_component_telemetry_async(
        self,
        input: SendComponentTelemetryInput,
        twinid: str,
        component_path: str,
    ):
        """
        Send Component Telemetry

        Sends telemetry on behalf of a component in a digital twin.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins"
            f"/{str(twinid)}"
            f"/components"
            f"/{str(component_path)}"
            f"/telemetry"
        )

        await self.http_client.send_async("POST", path, body=input)

    async def list_relationships_async(
        self,
        twinid: str,
    ):
        """
        List Relationships

        Retrieves all outgoing relationships from a digital twin.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/digitaltwins/{str(twinid)}/relationships"
        )

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def query_twins_async(
        self,
        input: QueryTwinsInput,
    ):
        """
        Query API

        Executes a query that allows traversing relationships and filtering by
        property values.
        """
        path = f"{self._connection_runtime_url}/query"

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)
