# Copyright (c) Microsoft Corporation. All rights reserved.

# AzuretablesClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, AsyncIterator, Dict, List, Any, Mapping
from urllib.parse import quote, urlsplit
import json

from azure.core.credentials import AzureKeyCredential
from azure.core.credentials_async import AsyncTokenCredential
from azure.core.pipeline.transport import AsyncHttpTransport

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorException,
    ConnectorResponseHook,
)


# Type Definitions

@dataclass
class CreateEntityInput:
    """
    Insert Entity
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class InsertEntityResponse:
    """
    Response for Insert Entity
    """

    odata_metadata: Optional[str] = field(
        default=None,
        metadata={"wire_name": "odata.metadata"},
    )
    """Entity Metadata location"""
    partition_key: Optional[str] = field(
        default=None,
        metadata={"wire_name": "PartitionKey"},
    )
    """Partition Key"""
    row_key: Optional[str] = field(
        default=None,
        metadata={"wire_name": "RowKey"},
    )
    """Row Key"""
    additional_properties: Optional[str] = field(
        default=None,
        metadata={"wire_name": "additionalProperties"},
    )
    """Dynamic entity columns returned by the service."""


CreateTableInput = str


@dataclass
class GetTableResponse:
    """
    Response for Create table
    """

    odata_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "odata.id"},
    )
    """URL to the Table data"""
    table_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "TableName"},
    )
    """Table Name"""


@dataclass
class GetEntitiesResponse:
    """
    Response for Get entities
    """

    odata_metadata: Optional[str] = field(
        default=None,
        metadata={"wire_name": "odata.metadata"},
    )
    """Table Metadata location"""
    value: Optional[List[EntityItem]] = None
    """List of Entities"""
    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "nextLink"},
    )
    """The URL to retrieve the next page."""


@dataclass
class GetEntityResponse:
    """
    Response for Get entity
    """

    odata_metadata: Optional[str] = field(
        default=None,
        metadata={"wire_name": "odata.metadata"},
    )
    """Table Metadata location"""
    partition_key: Optional[str] = field(
        default=None,
        metadata={"wire_name": "PartitionKey"},
    )
    """Partition Key"""
    row_key: Optional[str] = field(
        default=None,
        metadata={"wire_name": "RowKey"},
    )
    """Row Key"""
    additional_properties: Optional[str] = field(
        default=None,
        metadata={"wire_name": "additionalProperties"},
    )
    """Dynamic entity columns returned by the service."""


@dataclass
class GetTablesResponse:
    """
    Response for List tables
    """

    odata_metadata: Optional[str] = field(
        default=None,
        metadata={"wire_name": "odata.metadata"},
    )
    """URL to the account metadata"""
    value: Optional[List[Dict[str, Any]]] = None
    """List of tables"""


@dataclass
class InsertMergeEntityInput:
    """
    Insert or Merge Entity
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class InsertReplaceEntityInput:
    """
    Insert or Replace Entity
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class MergeEntityInput:
    """
    Merge Entity
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ReplaceEntityInput:
    """
    Replace Entity
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class StorageAccountList:
    """
    Response for Get storage accounts
    """

    value: Optional[List[StorageAccount]] = None
    """List of storage account names"""


@dataclass
class StorageAccount:
    """
    Definition: StorageAccount
    """

    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """The name of the storage account."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """The display name of the storage account."""


@dataclass
class EntityItem:
    """
    Definition: Item
    """

    partition_key: Optional[str] = field(
        default=None,
        metadata={"wire_name": "PartitionKey"},
    )
    """Partition Key"""
    row_key: Optional[str] = field(
        default=None,
        metadata={"wire_name": "RowKey"},
    )
    """Row Key"""
    additional_properties: Optional[str] = field(
        default=None,
        metadata={"wire_name": "additionalProperties"},
    )
    """Dynamic entity columns returned by the service."""


# Client Class

class AzuretablesClient(ConnectorClientBase):
    """Typed client for azuretables connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        credential: AsyncTokenCredential | AzureKeyCredential,
        *,
        max_retry_attempts: int = 3,
        timeout_seconds: float = 30.0,
        use_exponential_backoff: bool = True,
        initial_retry_delay_seconds: float = 0.5,
        maximum_retry_delay_seconds: float = 120.0,
        retry_jitter_factor: float = 0.1,
        retry_unsafe_http_methods: bool = False,
        transport: Optional[AsyncHttpTransport] = None,
        **kwargs: Any,
    ):
        """
        Initialize a AzuretablesClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            credential: Caller-owned Azure Core credential.
            max_retry_attempts: The maximum number of request attempts.
            timeout_seconds: The total network timeout for each request,
                including retries, response loading, and body reads.
                Nonpositive values disable SDK and transport deadlines.
            use_exponential_backoff: Whether retries use exponential backoff.
            initial_retry_delay_seconds: The initial retry delay in seconds.
            maximum_retry_delay_seconds: The maximum retry delay in seconds.
            retry_jitter_factor: The jitter fraction applied to retry delays.
            retry_unsafe_http_methods: Whether unsafe HTTP methods may be
                retried.
            transport: Optional Azure Core async HTTP transport closed by
                the client through its asynchronous lifecycle.
            **kwargs: Optional Azure Core pipeline policy settings.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if credential is None:
            raise ValueError("credential cannot be None")

        super().__init__(
            credential,
            max_retry_attempts=max_retry_attempts,
            timeout_seconds=timeout_seconds,
            use_exponential_backoff=use_exponential_backoff,
            initial_retry_delay_seconds=initial_retry_delay_seconds,
            maximum_retry_delay_seconds=maximum_retry_delay_seconds,
            retry_jitter_factor=retry_jitter_factor,
            retry_unsafe_http_methods=retry_unsafe_http_methods,
            transport=transport,
            **kwargs,
        )
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "azuretables"

    def _resolve_pagination_url(self, next_link: str, current_request_url: str) -> str:
        parsed_next_link = urlsplit(next_link)
        if not parsed_next_link.scheme or not parsed_next_link.netloc:
            if next_link.startswith("/"):
                return f"{self._connection_runtime_url}{next_link}"
            if next_link.startswith("?"):
                return f"{current_request_url.partition('?')[0]}{next_link}"
            return f"{self._connection_runtime_url}/{next_link}"

        parsed_connection = urlsplit(self._connection_runtime_url)
        next_link_hostname = parsed_next_link.hostname
        connection_hostname = parsed_connection.hostname
        if next_link_hostname is None or connection_hostname is None:
            raise ValueError("Pagination URLs must include a hostname.")

        next_link_port = parsed_next_link.port
        if next_link_port is None:
            next_link_port = 443 if parsed_next_link.scheme == "https" else 80
        connection_port = parsed_connection.port
        if connection_port is None:
            connection_port = 443 if parsed_connection.scheme == "https" else 80
        if next_link_hostname.lower() == connection_hostname.lower():
            if (
                parsed_next_link.scheme == parsed_connection.scheme
                and next_link_port == connection_port
            ):
                return next_link

            raise ValueError(
                "Pagination URL origin "
                f"'{parsed_next_link.scheme}://{next_link_hostname}:{next_link_port}' "
                "must use the connection runtime scheme and port."
            )

        suffix = parsed_next_link.path
        if parsed_next_link.query:
            suffix += f"?{parsed_next_link.query}"
        return f"{self._connection_runtime_url}{suffix}"

    async def create_entity_async(
        self,
        input: CreateEntityInput,
        storage_account_name: str,
        table_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Insert Entity

        Operation to add an entity to a table.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
            f"/entities"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_table_async(
        self,
        input: CreateTableInput,
        storage_account_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Create table

        This operation adds a table to the storage account.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_entity_async(
        self,
        storage_account_name: str,
        table_name: str,
        partition_key: str,
        row_key: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Delete Entity

        Operation to delete an entity.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
            f"/entities"
            f"/etag(PartitionKey='"
            f"{quote(str(partition_key), safe='')}"
            f"',RowKey='"
            f"{quote(str(row_key), safe='')}"
            f"')"
        )

        response = await self.http_client.send_async(
            "DELETE", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "DELETE",
                request_url,
                response.status,
                response.text,
            )

    async def delete_table_async(
        self,
        storage_account_name: str,
        table_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Delete a table

        Delete a table.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
        )

        response = await self.http_client.send_async(
            "DELETE", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "DELETE",
                request_url,
                response.status,
                response.text,
            )

    async def get_entities_async(
        self,
        storage_account_name: str,
        table_name: str,
        filter: Optional[str] = None,
        select: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """
        Get entities

        This operation queries the entities in a table.

        Yields items from every response page and automatically follows the
        connector continuation URL.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
            f"/entities"
        )
        query_params = []
        if filter is not None:
            value = str(filter)
            if isinstance(filter, bool):
                value = value.lower()
            query_params.append(f"$filter={quote(value, safe='')}")
        if select is not None:
            value = str(select)
            if isinstance(select, bool):
                value = value.lower()
            query_params.append(f"$select={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)
        request_body = None

        while True:
            response = await self.http_client.send_async(
                "GET", request_url, body=request_body,
                timeout=timeout,
                headers=headers,
                client_request_id=client_request_id,
                response_hook=response_hook,
            )

            if not (200 <= response.status < 300):
                raise ConnectorException(
                    "GET",
                    request_url,
                    response.status,
                    response.text,
                )

            if not response.text:
                return

            page = json.loads(response.text)
            for item in page.get("value", []):
                yield item

            next_link = page.get("nextLink")
            if not next_link:
                return

            request_url = self._resolve_pagination_url(next_link, request_url)
            request_body = None

    async def get_entity_async(
        self,
        storage_account_name: str,
        table_name: str,
        partition_key: str,
        row_key: str,
        select: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get entity

        This operation gets the entity in a table based on the partition and
        row key.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
            f"/entities(PartitionKey='"
            f"{quote(str(partition_key), safe='')}"
            f"',RowKey='"
            f"{quote(str(row_key), safe='')}"
            f"')"
        )
        query_params = []
        if select is not None:
            value = str(select)
            if isinstance(select, bool):
                value = value.lower()
            query_params.append(f"$select={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_table_async(
        self,
        storage_account_name: str,
        table_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get a table

        This operation gets the metadata of a table.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_tables_async(
        self,
        storage_account_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        List tables

        List all the tables for your storage account.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def insert_merge_entity_async(
        self,
        input: InsertMergeEntityInput,
        storage_account_name: str,
        table_name: str,
        partition_key: str,
        row_key: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Insert or Merge Entity

        Operation to merge data with an entity in a table, creating a new
        entity if needed.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
            f"/entities(PartitionKey='"
            f"{quote(str(partition_key), safe='')}"
            f"',RowKey='"
            f"{quote(str(row_key), safe='')}"
            f"')"
        )

        response = await self.http_client.send_async(
            "PATCH", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PATCH",
                request_url,
                response.status,
                response.text,
            )

    async def insert_replace_entity_async(
        self,
        input: InsertReplaceEntityInput,
        storage_account_name: str,
        table_name: str,
        partition_key: str,
        row_key: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Insert or Replace Entity

        Operation to replace an entity in a table, creating a new entity if
        needed.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
            f"/entities(PartitionKey='"
            f"{quote(str(partition_key), safe='')}"
            f"',RowKey='"
            f"{quote(str(row_key), safe='')}"
            f"')"
        )

        response = await self.http_client.send_async(
            "PUT", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                request_url,
                response.status,
                response.text,
            )

    async def merge_entity_async(
        self,
        input: MergeEntityInput,
        storage_account_name: str,
        table_name: str,
        partition_key: str,
        row_key: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Merge Entity

        Operation to merge data with an entity in a table.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
            f"/entities"
            f"/etag(PartitionKey='"
            f"{quote(str(partition_key), safe='')}"
            f"',RowKey='"
            f"{quote(str(row_key), safe='')}"
            f"')"
        )

        response = await self.http_client.send_async(
            "PATCH", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PATCH",
                request_url,
                response.status,
                response.text,
            )

    async def replace_entity_async(
        self,
        input: ReplaceEntityInput,
        storage_account_name: str,
        table_name: str,
        partition_key: str,
        row_key: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Replace Entity

        Operation to replace an entity in a table.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/storageAccounts"
            f"/{quote(quote(str(storage_account_name), safe=''), safe='')}"
            f"/tables"
            f"/{quote(str(table_name), safe='')}"
            f"/entities"
            f"/etag(PartitionKey='"
            f"{quote(str(partition_key), safe='')}"
            f"',RowKey='"
            f"{quote(str(row_key), safe='')}"
            f"')"
        )

        response = await self.http_client.send_async(
            "PUT", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                request_url,
                response.status,
                response.text,
            )

    async def get_storage_accounts_async(
        self,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get storage accounts

        This operation list the user's Azure Storage Account.
        """
        request_url = f"{self._connection_runtime_url}/v2/GetStorageAccounts"

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)
