# Copyright (c) Microsoft Corporation. All rights reserved.

# AzuredatafactoryClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, AsyncIterator, Dict, List, Any, Mapping
from urllib.parse import quote, urlsplit
import json

from azure.core.credentials import AzureKeyCredential
from azure.core.credentials_async import AsyncTokenCredential
from azure.core.pipeline.transport import AsyncHttpTransport

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorException,
    ConnectorResponseHook,
)


# Type Definitions

@dataclass
class CreatePipelineRunResponse:
    """
    Response for Create a pipeline run
    """

    run_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "runId"},
    )
    """runId"""


@dataclass
class PipelineRun:
    """
    Response for Get a pipeline run
    """

    run_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "runId"},
    )
    """Identifier of a run"""
    pipeline_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "pipelineName"},
    )
    """The pipeline name"""
    parameters: Optional[Dict[str, Any]] = None
    """
    The full of partial list of parameter name, value pair used in the pipeline
    run.
    """
    invoked_by: Optional[Dict[str, Any]] = field(
        default=None,
        metadata={"wire_name": "invokedBy"},
    )
    """Entity that started the pipeline."""
    run_start: Optional[str] = field(
        default=None,
        metadata={"wire_name": "runStart"},
    )
    """The start time of a pipeline run in ISO8601 format."""
    run_end: Optional[str] = field(
        default=None,
        metadata={"wire_name": "runEnd"},
    )
    """The end time of a pipeline run in ISO8601 format."""
    duration_in_ms: Optional[int] = field(
        default=None,
        metadata={"wire_name": "durationInMs"},
    )
    """The duration of a pipeline run in milliseconds."""
    status: Optional[str] = None
    """The status of the pipeline run."""
    message: Optional[str] = None
    """The message from a pipeline run."""
    last_updated: Optional[str] = field(
        default=None,
        metadata={"wire_name": "lastUpdated"},
    )
    """
    The last updated timestamp for the pipeline run event in ISO8601 format.
    """
    annotations: Optional[List[str]] = None
    """The annotations for the pipeline run."""


@dataclass
class SubscriptionListResult:
    """
    Response for List subscriptions
    """

    value: Optional[List[Subscription]] = None
    """The subscriptions."""
    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "nextLink"},
    )
    """The URL to get the next set of results."""


@dataclass
class ResourceGroupListResult:
    """
    Response for List resource groups
    """

    value: Optional[List[ResourceGroup]] = None
    """The list of resource groups."""
    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "nextLink"},
    )
    """The URL to get the next set of results."""


@dataclass
class DataFactoryListResult:
    """
    Response for List Factories
    """

    value: Optional[List[DataFactory]] = None
    """The list of Data Factories."""
    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "nextLink"},
    )
    """The URL to get the next set of results."""


@dataclass
class PipelineListResult:
    """
    Response for List pipelines
    """

    value: Optional[List[Pipeline]] = None
    """The list of Data Factories."""
    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "nextLink"},
    )
    """The URL to get the next set of results."""


@dataclass
class DataFactory:
    """
    Definition: DataFactory
    """

    name: Optional[str] = None
    """The resource name."""
    tags: Optional[Dict[str, Any]] = None
    """The resource tags."""
    properties: Optional[Dict[str, Any]] = None
    """Data Factory additional properties."""
    identity: Optional[Dict[str, Any]] = None
    """Managed service identity of the factory."""
    id: Optional[str] = None
    """The resource identitfier."""
    type_: Optional[str] = field(default=None, metadata={"wire_name": "type"})
    """The resource type."""
    location: Optional[str] = None
    """The resource location"""


@dataclass
class Pipeline:
    """
    Definition: Pipeline
    """

    id: Optional[str] = None
    """The resource identifier."""
    name: Optional[str] = None
    """The resource name of the pipeline."""
    properties: Optional[Dict[str, Any]] = None
    """The pipeline properties."""
    etag: Optional[str] = None
    """Etag identifies change in the resource."""


@dataclass
class Activity:
    """
    Definition: Activity
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ActivityFull:
    """
    Definition: Activity-Full
    """

    name: Optional[str] = None
    """name"""
    type_: Optional[str] = field(default=None, metadata={"wire_name": "type"})
    """type"""
    inputs: Optional[List[Dict[str, Any]]] = None
    """inputs"""
    outputs: Optional[List[Dict[str, Any]]] = None
    """outputs"""
    type_properties: Optional[Dict[str, Any]] = field(
        default=None,
        metadata={"wire_name": "typeProperties"},
    )
    """typeProperties"""
    policy: Optional[Dict[str, Any]] = None
    """policy"""


@dataclass
class ParameterValueSpecification:
    """
    Definition: ParameterValueSpecification
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class Subscription:
    """
    Definition: Subscription
    """

    id: Optional[str] = None
    """
    The fully qualified Id. For example,
    /subscriptions/00000000-0000-0000-0000-000000000000.
    """
    subscription_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "subscriptionId"},
    )
    """The subscription Id."""
    tenant_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "tenantId"},
    )
    """The tenant Id."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "displayName"},
    )
    """The subscription display name."""
    state: Optional[str] = None
    """The subscription state."""
    subscription_policies: Optional[SubscriptionPolicies] = field(
        default=None,
        metadata={"wire_name": "subscriptionPolicies"},
    )
    authorization_source: Optional[str] = field(
        default=None,
        metadata={"wire_name": "authorizationSource"},
    )
    """
    The authorization source of the request. Valid values are one or more
    combinations of Legacy, RoleBased, Bypassed, Direct and Management. For
    example, 'Legacy, RoleBased'.
    """


@dataclass
class SubscriptionPolicies:
    """
    Definition: SubscriptionPolicies
    """

    location_placement_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "locationPlacementId"},
    )
    """
    The subscription location placement Id. The Id indicates which regions are
    visible for a subscription. For example, a subscription with a location
    placement Id of Public_2014-09-01 has access to Azure public regions.
    """
    quota_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "quotaId"},
    )
    """The subscription quota Id."""
    spending_limit: Optional[str] = field(
        default=None,
        metadata={"wire_name": "spendingLimit"},
    )
    """The subscription spending limit."""


@dataclass
class ResourceGroup:
    """
    Definition: ResourceGroup
    """

    id: Optional[str] = None
    """
    The ID of the resource group (e.g. /subscriptions/XXX/resourceGroups/YYY).
    """
    name: Optional[str] = None
    """The Name of the resource group."""
    location: Optional[str] = None
    """
    The location of the resource group. It cannot be changed after the resource
    group has been created. Has to be one of the supported Azure Locations,
    such as West US, East US, West Europe, East Asia, etc.
    """
    managed_by: Optional[str] = field(
        default=None,
        metadata={"wire_name": "managedBy"},
    )
    """Id of the resource that manages this resource group."""
    tags: Optional[Dict[str, str]] = None
    """The tags attached to the resource group."""
    properties: Optional[ResourceGroupProperties] = None


@dataclass
class ResourceGroupProperties:
    """
    Definition: ResourceGroupProperties
    """

    provisioning_state: Optional[str] = field(
        default=None,
        metadata={"wire_name": "provisioningState"},
    )
    """The provisioning state."""


# Client Class

class AzuredatafactoryClient(ConnectorClientBase):
    """Typed client for azuredatafactory connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        credential: AsyncTokenCredential | AzureKeyCredential,
        *,
        max_retry_attempts: int = 3,
        timeout_seconds: float = 30.0,
        use_exponential_backoff: bool = True,
        initial_retry_delay_seconds: float = 0.5,
        maximum_retry_delay_seconds: float = 120.0,
        retry_jitter_factor: float = 0.1,
        retry_unsafe_http_methods: bool = False,
        transport: Optional[AsyncHttpTransport] = None,
        **kwargs: Any,
    ):
        """
        Initialize a AzuredatafactoryClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            credential: Caller-owned Azure Core credential.
            max_retry_attempts: The maximum number of request attempts.
            timeout_seconds: The total network timeout for each request,
                including retries, response loading, and body reads.
                Nonpositive values disable SDK and transport deadlines.
            use_exponential_backoff: Whether retries use exponential backoff.
            initial_retry_delay_seconds: The initial retry delay in seconds.
            maximum_retry_delay_seconds: The maximum retry delay in seconds.
            retry_jitter_factor: The jitter fraction applied to retry delays.
            retry_unsafe_http_methods: Whether unsafe HTTP methods may be
                retried.
            transport: Optional Azure Core async HTTP transport closed by
                the client through its asynchronous lifecycle.
            **kwargs: Optional Azure Core pipeline policy settings.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if credential is None:
            raise ValueError("credential cannot be None")

        super().__init__(
            credential,
            max_retry_attempts=max_retry_attempts,
            timeout_seconds=timeout_seconds,
            use_exponential_backoff=use_exponential_backoff,
            initial_retry_delay_seconds=initial_retry_delay_seconds,
            maximum_retry_delay_seconds=maximum_retry_delay_seconds,
            retry_jitter_factor=retry_jitter_factor,
            retry_unsafe_http_methods=retry_unsafe_http_methods,
            transport=transport,
            **kwargs,
        )
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "azuredatafactory"

    def _resolve_pagination_url(self, next_link: str, current_request_url: str) -> str:
        parsed_next_link = urlsplit(next_link)
        if not parsed_next_link.scheme or not parsed_next_link.netloc:
            if next_link.startswith("/"):
                return f"{self._connection_runtime_url}{next_link}"
            if next_link.startswith("?"):
                return f"{current_request_url.partition('?')[0]}{next_link}"
            return f"{self._connection_runtime_url}/{next_link}"

        parsed_connection = urlsplit(self._connection_runtime_url)
        next_link_hostname = parsed_next_link.hostname
        connection_hostname = parsed_connection.hostname
        if next_link_hostname is None or connection_hostname is None:
            raise ValueError("Pagination URLs must include a hostname.")

        next_link_port = parsed_next_link.port
        if next_link_port is None:
            next_link_port = 443 if parsed_next_link.scheme == "https" else 80
        connection_port = parsed_connection.port
        if connection_port is None:
            connection_port = 443 if parsed_connection.scheme == "https" else 80
        if next_link_hostname.lower() == connection_hostname.lower():
            if (
                parsed_next_link.scheme == parsed_connection.scheme
                and next_link_port == connection_port
            ):
                return next_link

            raise ValueError(
                "Pagination URL origin "
                f"'{parsed_next_link.scheme}://{next_link_hostname}:{next_link_port}' "
                "must use the connection runtime scheme and port."
            )

        suffix = parsed_next_link.path
        if parsed_next_link.query:
            suffix += f"?{parsed_next_link.query}"
        return f"{self._connection_runtime_url}{suffix}"

    async def create_pipeline_run_async(
        self,
        input: ParameterValueSpecification,
        subscription_id: str,
        resource_group_name: str,
        data_factory_name: str,
        pipeline_name: str,
        reference_pipeline_run_id: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Create a pipeline run

        This operation creates a new pipeline run in your factory
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/subscriptions"
            f"/{quote(str(subscription_id), safe='')}"
            f"/resourcegroups"
            f"/{quote(str(resource_group_name), safe='')}"
            f"/providers"
            f"/Microsoft.DataFactory"
            f"/factories"
            f"/{quote(str(data_factory_name), safe='')}"
            f"/pipelines"
            f"/{quote(str(pipeline_name), safe='')}"
            f"/CreateRun"
        )
        query_params = []
        query_params.append("x-ms-api-version=" + quote("2017-09-01-preview", safe=''))
        if reference_pipeline_run_id is not None:
            value = str(reference_pipeline_run_id)
            if isinstance(reference_pipeline_run_id, bool):
                value = value.lower()
            query_params.append(f"referencePipelineRunId={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def cancel_pipeline_run_async(
        self,
        subscription_id: str,
        resource_group_name: str,
        data_factory_name: str,
        pipeline_run_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Cancel a pipeline run

        This operation cancels a pipeline run by its run ID.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/subscriptions"
            f"/{quote(str(subscription_id), safe='')}"
            f"/resourcegroups"
            f"/{quote(str(resource_group_name), safe='')}"
            f"/providers"
            f"/Microsoft.DataFactory"
            f"/factories"
            f"/{quote(str(data_factory_name), safe='')}"
            f"/cancelpipelineRun"
            f"/{quote(str(pipeline_run_name), safe='')}"
        )
        query_params = []
        query_params.append("x-ms-api-version=" + quote("2017-09-01-preview", safe=''))
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

    async def get_pipeline_run_async(
        self,
        subscription_id: str,
        resource_group_name: str,
        data_factory_name: str,
        pipeline_run_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get a pipeline run

        Get a particular pipeline run execution
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/subscriptions"
            f"/{quote(str(subscription_id), safe='')}"
            f"/resourcegroups"
            f"/{quote(str(resource_group_name), safe='')}"
            f"/providers"
            f"/Microsoft.DataFactory"
            f"/factories"
            f"/{quote(str(data_factory_name), safe='')}"
            f"/pipelineRuns"
            f"/{quote(str(pipeline_run_name), safe='')}"
        )
        query_params = []
        query_params.append("x-ms-api-version=" + quote("2017-09-01-preview", safe=''))
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_subscriptions_async(
        self,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """
        List subscriptions

        Gets a list of all the subscriptions to which the principal has access.

        Yields items from every response page and automatically follows the
        connector continuation URL.
        """
        request_url = f"{self._connection_runtime_url}/subscriptions"
        query_params = []
        query_params.append("x-ms-api-version=" + quote("2017-09-01-preview", safe=''))
        if query_params:
            request_url += '?' + '&'.join(query_params)
        request_body = None

        while True:
            response = await self.http_client.send_async(
                "GET", request_url, body=request_body,
                timeout=timeout,
                headers=headers,
                client_request_id=client_request_id,
                response_hook=response_hook,
            )

            if not (200 <= response.status < 300):
                raise ConnectorException(
                    "GET",
                    request_url,
                    response.status,
                    response.text,
                )

            if not response.text:
                return

            page = json.loads(response.text)
            for item in page.get("value", []):
                yield item

            next_link = page.get("nextLink")
            if not next_link:
                return

            request_url = self._resolve_pagination_url(next_link, request_url)
            request_body = None

    async def list_resource_groups_async(
        self,
        subscription_id: str,
        filter: Optional[str] = None,
        top: Optional[int] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """
        List resource groups

        Lists all the resource groups within the subscription. The results are
        paginated at 1,000+ records.

        Yields items from every response page and automatically follows the
        connector continuation URL.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/subscriptions"
            f"/{quote(str(subscription_id), safe='')}"
            f"/resourcegroups"
        )
        query_params = []
        query_params.append("x-ms-api-version=" + quote("2017-09-01-preview", safe=''))
        if filter is not None:
            value = str(filter)
            if isinstance(filter, bool):
                value = value.lower()
            query_params.append(f"$filter={quote(value, safe='')}")
        if top is not None:
            value = str(top)
            if isinstance(top, bool):
                value = value.lower()
            query_params.append(f"$top={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)
        request_body = None

        while True:
            response = await self.http_client.send_async(
                "GET", request_url, body=request_body,
                timeout=timeout,
                headers=headers,
                client_request_id=client_request_id,
                response_hook=response_hook,
            )

            if not (200 <= response.status < 300):
                raise ConnectorException(
                    "GET",
                    request_url,
                    response.status,
                    response.text,
                )

            if not response.text:
                return

            page = json.loads(response.text)
            for item in page.get("value", []):
                yield item

            next_link = page.get("nextLink")
            if not next_link:
                return

            request_url = self._resolve_pagination_url(next_link, request_url)
            request_body = None

    async def list_data_factories_async(
        self,
        subscription_id: str,
        resource_group_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """
        List Factories

        Get the list of Data Factories

        Yields items from every response page and automatically follows the
        connector continuation URL.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/subscriptions"
            f"/{quote(str(subscription_id), safe='')}"
            f"/resourcegroups"
            f"/{quote(str(resource_group_name), safe='')}"
            f"/providers"
            f"/Microsoft.DataFactory"
            f"/factories"
        )
        query_params = []
        query_params.append("x-ms-api-version=" + quote("2017-09-01-preview", safe=''))
        if query_params:
            request_url += '?' + '&'.join(query_params)
        request_body = None

        while True:
            response = await self.http_client.send_async(
                "GET", request_url, body=request_body,
                timeout=timeout,
                headers=headers,
                client_request_id=client_request_id,
                response_hook=response_hook,
            )

            if not (200 <= response.status < 300):
                raise ConnectorException(
                    "GET",
                    request_url,
                    response.status,
                    response.text,
                )

            if not response.text:
                return

            page = json.loads(response.text)
            for item in page.get("value", []):
                yield item

            next_link = page.get("nextLink")
            if not next_link:
                return

            request_url = self._resolve_pagination_url(next_link, request_url)
            request_body = None

    async def list_pipelines_async(
        self,
        subscription_id: str,
        resource_group_name: str,
        data_factory_name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """
        List pipelines

        List the list of pipelines from a particular factory

        Yields items from every response page and automatically follows the
        connector continuation URL.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/subscriptions"
            f"/{quote(str(subscription_id), safe='')}"
            f"/resourcegroups"
            f"/{quote(str(resource_group_name), safe='')}"
            f"/providers"
            f"/Microsoft.DataFactory"
            f"/factories"
            f"/{quote(str(data_factory_name), safe='')}"
            f"/pipelines"
        )
        query_params = []
        query_params.append("x-ms-api-version=" + quote("2017-09-01-preview", safe=''))
        if query_params:
            request_url += '?' + '&'.join(query_params)
        request_body = None

        while True:
            response = await self.http_client.send_async(
                "GET", request_url, body=request_body,
                timeout=timeout,
                headers=headers,
                client_request_id=client_request_id,
                response_hook=response_hook,
            )

            if not (200 <= response.status < 300):
                raise ConnectorException(
                    "GET",
                    request_url,
                    response.status,
                    response.text,
                )

            if not response.text:
                return

            page = json.loads(response.text)
            for item in page.get("value", []):
                yield item

            next_link = page.get("nextLink")
            if not next_link:
                return

            request_url = self._resolve_pagination_url(next_link, request_url)
            request_body = None
