# Copyright (c) Microsoft Corporation. All rights reserved.

# AzureblobClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, AsyncIterator, Dict, List, Any, Mapping
from urllib.parse import quote, urlsplit
import json

from azure.core.credentials import AzureKeyCredential
from azure.core.credentials_async import AsyncTokenCredential
from azure.core.pipeline.transport import AsyncHttpTransport

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorException,
    ConnectorResponseHook,
)


# Type Definitions

@dataclass
class BlobMetadata:
    """
    Response for Copy blob
    """

    id: Optional[str] = field(default=None, metadata={"wire_name": "Id"})
    """The unique id of the file or folder."""
    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """The name of the file or folder."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """The display name of the file or folder."""
    path: Optional[str] = field(default=None, metadata={"wire_name": "Path"})
    """The path of the file or folder."""
    last_modified: Optional[str] = field(
        default=None,
        metadata={"wire_name": "LastModified"},
    )
    """The date and time the file or folder was last modified."""
    size: Optional[int] = field(default=None, metadata={"wire_name": "Size"})
    """The size of the file or folder."""
    media_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "MediaType"},
    )
    """The media type of the file or folder."""
    is_folder: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "IsFolder"},
    )
    """
    A boolean value (true, false) to indicate whether or not the blob is a
    folder.
    """
    e_tag: Optional[str] = field(default=None, metadata={"wire_name": "ETag"})
    """The etag of the file or folder."""
    file_locator: Optional[str] = field(
        default=None,
        metadata={"wire_name": "FileLocator"},
    )
    """The filelocator of the file or folder."""


@dataclass
class SharedAccessSignature:
    """
    Response for Create SAS URI by path
    """

    web_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "WebUrl"},
    )
    """A URL to an object with access token."""


@dataclass
class SharedAccessSignatureBlobPolicy:
    """
    Response for Get available access policies
    """

    group_policy_identifier: Optional[str] = field(
        default=None,
        metadata={"wire_name": "GroupPolicyIdentifier"},
    )
    """
    The string identifying a stored access policy. The Group policy parameters
    (e.g. Start time and End time) have precedence over input parameters
    mentioned in actions.
    """
    permissions: Optional[str] = field(
        default=None,
        metadata={"wire_name": "Permissions"},
    )
    """The permissions specified on the SAS (Values separated by comma)."""
    start_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "StartTime"},
    )
    """
    The date and time at which the SAS becomes valid (example:
    '2017-11-01T15:30:00+00:00'). Default = now().
    """
    expiry_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "ExpiryTime"},
    )
    """
    The date and time after which the SAS is no longer valid (example:
    '2017-12-01T15:30:00+00:00'). Default = now() + 24h.
    """
    access_protocol: Optional[str] = field(
        default=None,
        metadata={"wire_name": "AccessProtocol"},
    )
    """
    The allowed protocols (https only, or http and https). Null if you don't
    want to restrict protocol.
    """
    ip_address_or_range: Optional[str] = field(
        default=None,
        metadata={"wire_name": "IpAddressOrRange"},
    )
    """
    The allowed IP address or IP address range. Null if you don't want to
    restrict based on IP address.
    """


@dataclass
class DataWithSensitivityLabelInfo:
    """
    Response for Get Blob Metadata
    """

    id: Optional[str] = field(default=None, metadata={"wire_name": "Id"})
    """The unique id of the file or folder."""
    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """The name of the file or folder."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """The display name of the file or folder."""
    path: Optional[str] = field(default=None, metadata={"wire_name": "Path"})
    """The path of the file or folder."""
    last_modified: Optional[str] = field(
        default=None,
        metadata={"wire_name": "LastModified"},
    )
    """The date and time the file or folder was last modified."""
    size: Optional[int] = field(default=None, metadata={"wire_name": "Size"})
    """The size of the file or folder."""
    media_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "MediaType"},
    )
    """The media type of the file or folder."""
    is_folder: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "IsFolder"},
    )
    """
    A boolean value (true, false) to indicate whether or not the blob is a
    folder.
    """
    e_tag: Optional[str] = field(default=None, metadata={"wire_name": "ETag"})
    """The etag of the file or folder."""
    file_locator: Optional[str] = field(
        default=None,
        metadata={"wire_name": "FileLocator"},
    )
    """The filelocator of the file or folder."""
    sensitivity_label_info: Optional[List[SensitivityLabelMetadata]] = field(
        default=None,
        metadata={"wire_name": "SensitivityLabelInfo"},
    )
    """Sensitivity label metadata info list"""


@dataclass
class ListOfBlobsWithSensitivityLabels:
    """
    Response for Lists blobs
    """

    value: Optional[List[DataWithSensitivityLabelInfo]] = None
    """List of Blobs"""
    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "nextLink"},
    )
    """The URL to retrieve the next page."""


@dataclass
class BlobMetadataPage:
    """
    Response for Lists blobs in the root folder
    """

    value: Optional[List[BlobMetadata]] = None
    """Blob metadata collection."""
    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "nextLink"},
    )
    """An Url which can be used to retrieve the next page."""
    next_page_marker: Optional[str] = field(
        default=None,
        metadata={"wire_name": "nextPageMarker"},
    )
    """A marker which can be used to retrieve the next page."""


@dataclass
class StorageAccountList:
    """
    Response for Get storage accounts
    """

    value: Optional[List[StorageAccount]] = None
    """List of storage account names"""


@dataclass
class ObjectEntity:
    """
    Definition: Object
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class BlobMetadataResponse:
    """
    Definition: BlobMetadataResponse
    """

    id: Optional[str] = field(default=None, metadata={"wire_name": "Id"})
    """The unique id of the file or folder."""
    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """The name of the file or folder."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """The display name of the file or folder."""
    path: Optional[str] = field(default=None, metadata={"wire_name": "Path"})
    """The path of the file or folder."""
    last_modified: Optional[str] = field(
        default=None,
        metadata={"wire_name": "LastModified"},
    )
    """The date and time the file or folder was last modified."""
    size: Optional[int] = field(default=None, metadata={"wire_name": "Size"})
    """The size of the file or folder."""
    media_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "MediaType"},
    )
    """The media type of the file or folder."""
    is_folder: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "IsFolder"},
    )
    """
    A boolean value (true, false) to indicate whether or not the blob is a
    folder.
    """
    e_tag: Optional[str] = field(default=None, metadata={"wire_name": "ETag"})
    """The etag of the file or folder."""
    file_locator: Optional[str] = field(
        default=None,
        metadata={"wire_name": "FileLocator"},
    )
    """The filelocator of the file or folder."""


@dataclass
class SensitivityLabelMetadata:
    """
    Definition: SensitivityLabelMetadata
    """

    sensitivity_label_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "sensitivityLabelId"},
    )
    """SensitivityLabel Id."""
    name: Optional[str] = None
    """SensitivityLabel name."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "displayName"},
    )
    """SensitivityLabel displayName info"""
    tooltip: Optional[str] = None
    """SensitivityLabel details on tooltip."""
    priority: Optional[int] = None
    """SensitivityLabel priority."""
    color: Optional[str] = None
    """SensitivityLabel color."""
    is_encrypted: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "isEncrypted"},
    )
    """ is  SensitivityLabel Encrypted."""
    is_enabled: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "isEnabled"},
    )
    """Whether  SensitivityLabel is Enabled."""
    is_parent: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "isParent"},
    )
    """Whether  SensitivityLabel is Parent."""
    parent_sensitivity_label_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "parentSensitivityLabelId"},
    )
    """Parent  SensitivityLabel Id."""


@dataclass
class StorageAccount:
    """
    Definition: StorageAccount
    """

    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """The name of the storage account."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """The display name of the storage account."""


@dataclass
class DataSetsMetadata:
    """
    Definition: DataSetsMetadata
    """

    tabular: Optional[TabularDataSetsMetadata] = None
    blob: Optional[BlobDataSetsMetadata] = None


@dataclass
class TabularDataSetsMetadata:
    """
    Definition: TabularDataSetsMetadata
    """

    source: Optional[str] = None
    """Dataset source"""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "displayName"},
    )
    """Dataset display name"""
    url_encoding: Optional[str] = field(
        default=None,
        metadata={"wire_name": "urlEncoding"},
    )
    """Dataset url encoding"""
    table_display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "tableDisplayName"},
    )
    """Table display name"""
    table_plural_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "tablePluralName"},
    )
    """Table plural display name"""


@dataclass
class BlobDataSetsMetadata:
    """
    Definition: BlobDataSetsMetadata
    """

    source: Optional[str] = None
    """Blob dataset source"""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "displayName"},
    )
    """Blob dataset display name"""
    url_encoding: Optional[str] = field(
        default=None,
        metadata={"wire_name": "urlEncoding"},
    )
    """Blob dataset url encoding"""


# Client Class

class AzureblobClient(ConnectorClientBase):
    """Typed client for azureblob connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        credential: AsyncTokenCredential | AzureKeyCredential,
        *,
        max_retry_attempts: int = 3,
        timeout_seconds: float = 30.0,
        use_exponential_backoff: bool = True,
        initial_retry_delay_seconds: float = 0.5,
        maximum_retry_delay_seconds: float = 120.0,
        retry_jitter_factor: float = 0.1,
        retry_unsafe_http_methods: bool = False,
        transport: Optional[AsyncHttpTransport] = None,
        **kwargs: Any,
    ):
        """
        Initialize a AzureblobClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            credential: Caller-owned Azure Core credential.
            max_retry_attempts: The maximum number of request attempts.
            timeout_seconds: The total network timeout for each request,
                including retries, response loading, and body reads.
            use_exponential_backoff: Whether retries use exponential backoff.
            initial_retry_delay_seconds: The initial retry delay in seconds.
            maximum_retry_delay_seconds: The maximum retry delay in seconds.
            retry_jitter_factor: The jitter fraction applied to retry delays.
            retry_unsafe_http_methods: Whether unsafe HTTP methods may be
                retried.
            transport: Optional Azure Core async HTTP transport.
            **kwargs: Optional Azure Core pipeline policy settings.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if credential is None:
            raise ValueError("credential cannot be None")

        super().__init__(
            credential,
            max_retry_attempts=max_retry_attempts,
            timeout_seconds=timeout_seconds,
            use_exponential_backoff=use_exponential_backoff,
            initial_retry_delay_seconds=initial_retry_delay_seconds,
            maximum_retry_delay_seconds=maximum_retry_delay_seconds,
            retry_jitter_factor=retry_jitter_factor,
            retry_unsafe_http_methods=retry_unsafe_http_methods,
            transport=transport,
            **kwargs,
        )
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "azureblob"

    def _resolve_pagination_url(self, next_link: str, current_request_url: str) -> str:
        parsed_next_link = urlsplit(next_link)
        if not parsed_next_link.scheme or not parsed_next_link.netloc:
            if next_link.startswith("/"):
                return f"{self._connection_runtime_url}{next_link}"
            if next_link.startswith("?"):
                return f"{current_request_url.partition('?')[0]}{next_link}"
            return f"{self._connection_runtime_url}/{next_link}"

        parsed_connection = urlsplit(self._connection_runtime_url)
        next_link_hostname = parsed_next_link.hostname
        connection_hostname = parsed_connection.hostname
        if next_link_hostname is None or connection_hostname is None:
            raise ValueError("Pagination URLs must include a hostname.")

        next_link_port = parsed_next_link.port
        if next_link_port is None:
            next_link_port = 443 if parsed_next_link.scheme == "https" else 80
        connection_port = parsed_connection.port
        if connection_port is None:
            connection_port = 443 if parsed_connection.scheme == "https" else 80
        if next_link_hostname.lower() == connection_hostname.lower():
            if (
                parsed_next_link.scheme == parsed_connection.scheme
                and next_link_port == connection_port
            ):
                return next_link

            raise ValueError(
                "Pagination URL origin "
                f"'{parsed_next_link.scheme}://{next_link_hostname}:{next_link_port}' "
                "must use the connection runtime scheme and port."
            )

        suffix = parsed_next_link.path
        if parsed_next_link.query:
            suffix += f"?{parsed_next_link.query}"
        return f"{self._connection_runtime_url}{suffix}"

    async def copy_file_async(
        self,
        dataset: str,
        source: str,
        destination: str,
        overwrite: Optional[bool] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Copy blob

        This operation copies a blob. If blob is being deleted/renamed on
        server right after it was copied, connector may return HTTP 404 error
        by it's design. Please use a delay for 1 minute before deleting or
        renaming newly created blob. Chunk transfer is not supported in this
        action. If source and destination are present in same storage account,
        please use relative path. Otherwise, maximum size of a source for copy
        blob operation is 50 MB.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/copyFile"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(source)
        if isinstance(source, bool):
            value = value.lower()
        query_params.append(f"source={quote(value, safe='')}")
        value = str(destination)
        if isinstance(destination, bool):
            value = value.lower()
        query_params.append(f"destination={quote(value, safe='')}")
        if overwrite is not None:
            value = str(overwrite)
            if isinstance(overwrite, bool):
                value = value.lower()
            query_params.append(f"overwrite={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_block_blob_async(
        self,
        input: bytes,
        storage_account_name: str,
        folder_path: str,
        name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Create block blob

        This operation uploads a block blob to Azure Blob Storage.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/codeless"
            f"/datasets"
            f"/{quote(str(storage_account_name), safe='')}"
            f"/CreateBlockBlob"
        )
        query_params = []
        value = str(folder_path)
        if isinstance(folder_path, bool):
            value = value.lower()
        query_params.append(f"folderPath={quote(value, safe='')}")
        value = str(name)
        if isinstance(name, bool):
            value = value.lower()
        query_params.append(f"name={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST",
            request_url,
            body=input,
            content_type="application/octet-stream",
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

    async def create_file_async(
        self,
        input: bytes,
        dataset: str,
        folder_path: str,
        name: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Create blob

        This operation uploads a blob to Azure Blob Storage.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/files"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(folder_path)
        if isinstance(folder_path, bool):
            value = value.lower()
        query_params.append(f"folderPath={quote(value, safe='')}")
        value = str(name)
        if isinstance(name, bool):
            value = value.lower()
        query_params.append(f"name={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST",
            request_url,
            body=input,
            content_type="application/octet-stream",
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_share_link_by_path_async(
        self,
        input: SharedAccessSignatureBlobPolicy,
        storage_account_name: str,
        path: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Create SAS URI by path

        This operation creates a SAS link for a blob using the path.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(str(storage_account_name), safe='')}"
            f"/CreateSharedLinkByPath"
        )
        query_params = []
        value = str(path)
        if isinstance(path, bool):
            value = value.lower()
        query_params.append(f"path={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_file_async(
        self,
        dataset: str,
        id: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Delete blob

        This operation deletes a blob.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/files"
            f"/{quote(quote(str(id), safe=''), safe='')}"
        )

        response = await self.http_client.send_async(
            "DELETE", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "DELETE",
                request_url,
                response.status,
                response.text,
            )

    async def extract_folder_async(
        self,
        dataset: str,
        source: str,
        destination: str,
        overwrite: Optional[bool] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Extract archive to folder

        This operation extracts an archive blob into a folder (example: .zip).
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/extractFolderV2"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(source)
        if isinstance(source, bool):
            value = value.lower()
        query_params.append(f"source={quote(value, safe='')}")
        value = str(destination)
        if isinstance(destination, bool):
            value = value.lower()
        query_params.append(f"destination={quote(value, safe='')}")
        if overwrite is not None:
            value = str(overwrite)
            if isinstance(overwrite, bool):
                value = value.lower()
            query_params.append(f"overwrite={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_access_policies_async(
        self,
        storage_account_name: str,
        path: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get available access policies

        This operation gets available shared access policies for a blob.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(str(storage_account_name), safe='')}"
            f"/policies"
        )
        query_params = []
        value = str(path)
        if isinstance(path, bool):
            value = value.lower()
        query_params.append(f"path={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_file_content_async(
        self,
        dataset: str,
        id: str,
        infer_content_type: Optional[bool] = None,
        extract_sensitivity_label: Optional[bool] = None,
        purview_account_name: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> bytes:
        """
        Get blob content

        This operation retrieves blob contents using id.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/files"
            f"/{quote(quote(str(id), safe=''), safe='')}"
            f"/content"
        )
        query_params = []
        if infer_content_type is not None:
            value = str(infer_content_type)
            if isinstance(infer_content_type, bool):
                value = value.lower()
            query_params.append(f"inferContentType={quote(value, safe='')}")
        if extract_sensitivity_label is not None:
            value = str(extract_sensitivity_label)
            if isinstance(extract_sensitivity_label, bool):
                value = value.lower()
            query_params.append(f"extractSensitivityLabel={quote(value, safe='')}")
        if purview_account_name is not None:
            value = str(purview_account_name)
            if isinstance(purview_account_name, bool):
                value = value.lower()
            query_params.append(f"purviewAccountName={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        return response.content

    async def get_file_content_by_path_async(
        self,
        dataset: str,
        path: str,
        infer_content_type: Optional[bool] = None,
        extract_sensitivity_label: Optional[bool] = None,
        purview_account_name: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> bytes:
        """
        Get blob content using path

        This operation retrieves blob contents using path.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/GetFileContentByPath"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(path)
        if isinstance(path, bool):
            value = value.lower()
        query_params.append(f"path={quote(value, safe='')}")
        if infer_content_type is not None:
            value = str(infer_content_type)
            if isinstance(infer_content_type, bool):
                value = value.lower()
            query_params.append(f"inferContentType={quote(value, safe='')}")
        if extract_sensitivity_label is not None:
            value = str(extract_sensitivity_label)
            if isinstance(extract_sensitivity_label, bool):
                value = value.lower()
            query_params.append(f"extractSensitivityLabel={quote(value, safe='')}")
        if purview_account_name is not None:
            value = str(purview_account_name)
            if isinstance(purview_account_name, bool):
                value = value.lower()
            query_params.append(f"purviewAccountName={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        return response.content

    async def get_file_metadata_async(
        self,
        dataset: str,
        id: str,
        extract_sensitivity_label: Optional[bool] = None,
        purview_account_name: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get Blob Metadata

        This operation retrieves blob metadata using blob id.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/files"
            f"/{quote(quote(str(id), safe=''), safe='')}"
        )
        query_params = []
        if extract_sensitivity_label is not None:
            value = str(extract_sensitivity_label)
            if isinstance(extract_sensitivity_label, bool):
                value = value.lower()
            query_params.append(f"extractSensitivityLabel={quote(value, safe='')}")
        if purview_account_name is not None:
            value = str(purview_account_name)
            if isinstance(purview_account_name, bool):
                value = value.lower()
            query_params.append(f"purviewAccountName={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_file_metadata_by_path_async(
        self,
        dataset: str,
        path: str,
        extract_sensitivity_label: Optional[bool] = None,
        purview_account_name: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get Blob Metadata using path

        This operation retrieves blob metadata using path.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/GetFileByPath"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(path)
        if isinstance(path, bool):
            value = value.lower()
        query_params.append(f"path={quote(value, safe='')}")
        if extract_sensitivity_label is not None:
            value = str(extract_sensitivity_label)
            if isinstance(extract_sensitivity_label, bool):
                value = value.lower()
            query_params.append(f"extractSensitivityLabel={quote(value, safe='')}")
        if purview_account_name is not None:
            value = str(purview_account_name)
            if isinstance(purview_account_name, bool):
                value = value.lower()
            query_params.append(f"purviewAccountName={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_folder_async(
        self,
        dataset: str,
        id: str,
        next_page_marker: Optional[str] = None,
        use_flat_listing: Optional[bool] = None,
        extract_sensitivity_label: Optional[bool] = None,
        purview_account_name: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """
        Lists blobs

        This operation lists blobs in a container.

        Yields items from every response page and automatically follows the
        connector continuation URL.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/foldersV2"
            f"/{quote(quote(str(id), safe=''), safe='')}"
        )
        query_params = []
        if next_page_marker is not None:
            value = str(next_page_marker)
            if isinstance(next_page_marker, bool):
                value = value.lower()
            query_params.append(f"nextPageMarker={quote(value, safe='')}")
        if use_flat_listing is not None:
            value = str(use_flat_listing)
            if isinstance(use_flat_listing, bool):
                value = value.lower()
            query_params.append(f"useFlatListing={quote(value, safe='')}")
        if extract_sensitivity_label is not None:
            value = str(extract_sensitivity_label)
            if isinstance(extract_sensitivity_label, bool):
                value = value.lower()
            query_params.append(f"extractSensitivityLabel={quote(value, safe='')}")
        if purview_account_name is not None:
            value = str(purview_account_name)
            if isinstance(purview_account_name, bool):
                value = value.lower()
            query_params.append(f"purviewAccountName={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)
        request_body = None

        while True:
            response = await self.http_client.send_async(
                "GET", request_url, body=request_body,
                timeout=timeout,
                headers=headers,
                client_request_id=client_request_id,
                response_hook=response_hook,
            )

            if not (200 <= response.status < 300):
                raise ConnectorException(
                    "GET",
                    request_url,
                    response.status,
                    response.text,
                )

            if not response.text:
                return

            page = json.loads(response.text)
            for item in page.get("value", []):
                yield item

            next_link = page.get("nextLink")
            if not next_link:
                return

            request_url = self._resolve_pagination_url(next_link, request_url)
            request_body = None

    async def list_root_folder_async(
        self,
        dataset: str,
        next_page_marker: Optional[str] = None,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """
        Lists blobs in the root folder

        This operation lists blobs in the Azure Blob Storage root folder.

        Yields items from every response page and automatically follows the
        connector continuation URL.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/foldersV2"
        )
        query_params = []
        query_params.append("useFlatListing=" + quote("false"))
        if next_page_marker is not None:
            value = str(next_page_marker)
            if isinstance(next_page_marker, bool):
                value = value.lower()
            query_params.append(f"nextPageMarker={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)
        request_body = None

        while True:
            response = await self.http_client.send_async(
                "GET", request_url, body=request_body,
                timeout=timeout,
                headers=headers,
                client_request_id=client_request_id,
                response_hook=response_hook,
            )

            if not (200 <= response.status < 300):
                raise ConnectorException(
                    "GET",
                    request_url,
                    response.status,
                    response.text,
                )

            if not response.text:
                return

            page = json.loads(response.text)
            for item in page.get("value", []):
                yield item

            next_link = page.get("nextLink")
            if not next_link:
                return

            request_url = self._resolve_pagination_url(next_link, request_url)
            request_body = None

    async def set_blob_tier_by_path_async(
        self,
        storage_account_name: str,
        path: str,
        new_tier: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> None:
        """
        Set blob tier by path

        This operation sets a tier for a block blob on a standard storage
        account using the path.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(str(storage_account_name), safe='')}"
            f"/SetBlobTierByPath"
        )
        query_params = []
        value = str(path)
        if isinstance(path, bool):
            value = value.lower()
        query_params.append(f"path={quote(value, safe='')}")
        value = str(new_tier)
        if isinstance(new_tier, bool):
            value = value.lower()
        query_params.append(f"newTier={quote(value, safe='')}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

    async def update_file_async(
        self,
        input: bytes,
        dataset: str,
        id: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Update blob

        This operation updates a blob in Azure Blob Storage.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v2"
            f"/datasets"
            f"/{quote(quote(str(dataset), safe=''), safe='')}"
            f"/files"
            f"/{quote(quote(str(id), safe=''), safe='')}"
        )

        response = await self.http_client.send_async(
            "PUT",
            request_url,
            body=input,
            content_type="application/octet-stream",
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_data_sets_async(
        self,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get storage accounts

        This operation list the user's Azure Storage Account.
        """
        request_url = f"{self._connection_runtime_url}/v2/codeless/GetDataSets"

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)


# Trigger Operations
#
# Trigger routes are not callable client methods. Register a trigger with the
# Connector Namespace trigger-config API using the operation id and required
# parameters below; Connector Namespace invokes the callback when the trigger
# fires. When the callback body has a JSON schema, ``callback_payload_type``
# names the generated dataclass to deserialize the callback payload into.
TRIGGER_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "OnUpdatedFiles_V2": {
        "operation_id": "OnUpdatedFiles_V2",
        "path": "/{connectionId}/v2/datasets/{dataset}/triggers/batch/onupdatedfile",
        "method": "get",
        "required_parameters": ["dataset", "folderId"],
        "callback_payload_type": "BlobMetadata",
    },
}
