# Copyright (c) Microsoft Corporation. All rights reserved.

# ClicksendsmsClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict, List
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class SmsSendInput:
    """
    Send SMS
    """

    messages: Optional[List[Dict[str, Any]]] = None
    """Message"""


@dataclass
class SmsSendResponse:
    """
    Response for Send SMS
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Msg"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class CreateListInput:
    """
    Create New Contact List
    """

    list_name: Optional[str] = None
    """Your contact list name"""


@dataclass
class CreateListResponse:
    """
    Response for Create New Contact List
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class GetContactListsResponse:
    """
    Response for Get Contact Lists
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class SendVoiceInput:
    """
    Send Voice Message
    """

    messages: Optional[List[Dict[str, Any]]] = None
    """Message"""


@dataclass
class SendVoiceResponse:
    """
    Response for Send Voice Message
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class DeleteListResponse:
    """
    Response for Delete List
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""


@dataclass
class CreateListContactInput:
    """
    Create New Contact
    """

    first_name: Optional[str] = None
    """Contact's first name."""
    last_name: Optional[str] = None
    """Contact's last name."""
    phone_number: Optional[str] = None
    """The contact phone in local or international format e.g. +61411111111."""
    email: Optional[str] = None
    """Contact's email address."""
    fax_number: Optional[str] = None
    """Contact's fax number."""
    organization_name: Optional[str] = None
    """Contact's organization name."""
    address_country: Optional[str] = None
    """The contact's country."""
    address_state: Optional[str] = None
    """State"""
    address_city: Optional[str] = None
    """Address City"""
    custom1: Optional[str] = field(
        default=None,
        metadata={"wire_name": "custom_1"},
    )
    """Custom 1"""
    custom3: Optional[str] = field(
        default=None,
        metadata={"wire_name": "custom_3"},
    )
    """Custom 3"""
    address_postal_code: Optional[str] = None
    custom2: Optional[str] = field(
        default=None,
        metadata={"wire_name": "custom_2"},
    )
    """Custom 2"""
    custom4: Optional[str] = field(
        default=None,
        metadata={"wire_name": "custom_4"},
    )
    """Custom 4"""
    address_line1: Optional[str] = field(
        default=None,
        metadata={"wire_name": "address_line_1"},
    )
    """Address Line 1"""
    address_line2: Optional[str] = field(
        default=None,
        metadata={"wire_name": "address_line_2"},
    )
    """Address Line 2"""


@dataclass
class CreateListContactResponse:
    """
    Response for Create New Contact
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class ViewListContactsResponse:
    """
    Response for Get Contacts in a List
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class DeleteListContactResponse:
    """
    Response for Delete a Contact
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""


@dataclass
class SendMmsInput:
    """
    Send MMS
    """

    messages: Optional[List[Dict[str, Any]]] = None
    """Message"""
    media_file: Optional[str] = None
    """
    Supports maximum file size of 250kB, Gif can only be supported if it below
    100 kB file size
    """


@dataclass
class SendMmsResponse:
    """
    Response for Send MMS
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class SendFaxInput:
    """
    Send Fax
    """

    messages: Optional[List[Dict[str, Any]]] = None
    """Message"""
    file_url: Optional[str] = None
    """
    Maximum file size is 4 MB. All pages should be in portrait. Chat with
    ClickSend Support for complete specifications
    """


@dataclass
class SendFaxResponse:
    """
    Response for Send Fax
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class UploadMediaInput:
    """
    Convert Media File Format
    """

    content: Optional[str] = None
    """File Content (base64)"""


@dataclass
class UploadMediaResponse:
    """
    Response for Convert Media File Format
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class SearchContactListResponse:
    """
    Response for Search Contact Lists
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class SendLetterInput:
    """
    Send Letter
    """

    file_url: Optional[str] = None
    """
    Maximum file size is 10 MB. All pages should be in portrait. Chat with
    ClickSend Support for complete specifications.
    """
    template_used: Optional[int] = None
    """
    Whether using letter template. Flag value must be 1 for yes or 0 for no.
    """
    colour: Optional[int] = None
    """Choose to use colour or B&W printing. (Black & White = 0, Colour = 1)"""
    duplex: Optional[int] = None
    """
    Choose to use Duplex = 1 (double-sided) or Simplex = 0(single sided)
    printing.
    """
    priority_post: Optional[int] = None
    """Whether letter is priority, Flag value must be 1 for yes or 0 for no."""
    recipients: Optional[List[Dict[str, Any]]] = None
    """Recipient"""
    source: Optional[str] = None
    """Source"""


@dataclass
class SendLetterResponse:
    """
    Response for Send Letter
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class SendPostcardInput:
    """
    Send Postcard
    """

    recipients: Optional[List[Dict[str, Any]]] = None
    """item"""
    file_urls: Optional[List[str]] = None
    """PDF File URL"""


@dataclass
class SendPostcardResponse:
    """
    Response for Send Postcard
    """

    http_code: Optional[int] = None
    """Http Code"""
    response_code: Optional[str] = None
    """Response Code"""
    response_msg: Optional[str] = None
    """Response Message"""
    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class SmsInboundAutomationInput:
    """
    SMS Inbound Automation
    """

    message_search_type: Optional[int] = None
    """
    Message Search Type: 0=Any message, 1=starts with, 2=contains, 3=does not
    contain.
    """
    message_search_term: Optional[str] = None
    """word or phrase in the SMS"""
    action_address: Optional[str] = None
    """Action address"""
    dedicated_number: Optional[str] = None
    """Decicated Number. Can be '*' to apply to all numbers."""
    rule_name: Optional[str] = None
    """Rule Name"""
    webhook_type: Optional[str] = None
    """Webhook Type"""
    action: Optional[str] = None
    """
    Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL,
    GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL,
    CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE).
    """
    enabled: Optional[int] = None
    """enabled"""


# Client Class

class ClicksendsmsClient(ConnectorClientBase):
    """Typed client for clicksendsms connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a ClicksendsmsClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "clicksendsms"

    async def sms_send_async(
        self,
        input: SmsSendInput,
    ) -> dict[str, Any] | None:
        """
        Send SMS

        Each 160 characters = 1 SMS. Can send up to 1,224 standard characters.
        """
        request_url = f"{self._connection_runtime_url}/sms/send"

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_list_async(
        self,
        input: CreateListInput,
    ) -> dict[str, Any] | None:
        """
        Create New Contact List

        Create New Contact List
        """
        request_url = f"{self._connection_runtime_url}/lists"

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_contact_lists_async(
        self,
        page: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> dict[str, Any] | None:
        """
        Get Contact Lists

        Get all contact lists unless specified in the advance options
        """
        request_url = f"{self._connection_runtime_url}/lists"
        query_params = []
        if page is not None:
            value = str(page)
            if isinstance(page, bool):
                value = value.lower()
            query_params.append(f"page={quote(value)}")
        if limit is not None:
            value = str(limit)
            if isinstance(limit, bool):
                value = value.lower()
            query_params.append(f"limit={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def send_voice_async(
        self,
        input: SendVoiceInput,
    ) -> dict[str, Any] | None:
        """
        Send Voice Message

        Each 300 characters = 1 voice message. Can send up to 1,200 standard
        characters
        """
        request_url = f"{self._connection_runtime_url}/voice/send"

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_list_async(
        self,
        list_id: int,
    ) -> dict[str, Any] | None:
        """
        Delete List

        Delete a specific contact list
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/lists/{quote(str(list_id), safe='')}"
        )

        response = await self.http_client.send_async(
            "DELETE", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "DELETE",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_list_contact_async(
        self,
        input: CreateListContactInput,
        list_id: int,
    ) -> dict[str, Any] | None:
        """
        Create New Contact

        Create New Contact
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/lists/{quote(str(list_id), safe='')}/contacts"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def view_list_contacts_async(
        self,
        list_id: int,
    ) -> dict[str, Any] | None:
        """
        Get Contacts in a List

        Get all Contacts in a List
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/lists/{quote(str(list_id), safe='')}/contacts"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_list_contact_async(
        self,
        list_id: int,
        contact_id: int,
    ) -> dict[str, Any] | None:
        """
        Delete a Contact

        Delete a Contact
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/lists"
            f"/{quote(str(list_id), safe='')}"
            f"/contacts"
            f"/{quote(str(contact_id), safe='')}"
        )

        response = await self.http_client.send_async(
            "DELETE", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "DELETE",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def send_mms_async(
        self,
        input: SendMmsInput,
    ) -> dict[str, Any] | None:
        """
        Send MMS

        Send MMS
        """
        request_url = f"{self._connection_runtime_url}/mms/send"

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def send_fax_async(
        self,
        input: SendFaxInput,
    ) -> dict[str, Any] | None:
        """
        Send Fax

        Send Fax
        """
        request_url = f"{self._connection_runtime_url}/fax/send"

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def upload_media_async(
        self,
        input: UploadMediaInput,
        convert: str,
    ) -> dict[str, Any] | None:
        """
        Convert Media File Format

        Convert Media File Format
        """
        request_url = f"{self._connection_runtime_url}/uploads"
        query_params = []
        value = str(convert)
        if isinstance(convert, bool):
            value = value.lower()
        query_params.append(f"convert={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def search_contact_list_async(
        self,
        q: str,
    ) -> dict[str, Any] | None:
        """
        Search Contact Lists

        Get list of searched contact list
        """
        request_url = f"{self._connection_runtime_url}/search/contacts-lists"
        query_params = []
        value = str(q)
        if isinstance(q, bool):
            value = value.lower()
        query_params.append(f"q={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def send_letter_async(
        self,
        input: SendLetterInput,
    ) -> dict[str, Any] | None:
        """
        Send Letter

        Send Letter
        """
        request_url = f"{self._connection_runtime_url}/post/letters/send"

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def send_postcard_async(
        self,
        input: SendPostcardInput,
    ) -> dict[str, Any] | None:
        """
        Send Postcard

        Send one or more postcards
        """
        request_url = f"{self._connection_runtime_url}/post/postcards/send"

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)


# Trigger Operations
#
# Trigger routes are not callable client methods. Register a trigger with the
# Connector Namespace trigger-config API using the operation id and required
# parameters below; Connector Namespace invokes the callback when the trigger
# fires. When the callback body has a JSON schema, ``callback_payload_type``
# names the generated dataclass to deserialize the callback payload into.
TRIGGER_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "sms_inbound_automation": {
        "operation_id": "sms_inbound_automation",
        "path": "/{connectionId}/ms-flow/automations/sms/inbound",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": None,
    },
}
