# Copyright (c) Microsoft Corporation. All rights reserved.

# FormstackformsClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Any, Dict, List
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class FormstackFormSubmittedInput:
    """
    Triggers when a form is submitted
    """

    url: Optional[str] = None
    """url"""
    content_type: Optional[str] = None
    """content type"""
    file_transfer_type: Optional[str] = None
    """file transfer type"""
    standardize_field_values: Optional[bool] = None
    """standardize field values"""


@dataclass
class FormstackFormSubmittedResponse:
    """
    Response for Triggers when a form is submitted
    """

    id: Optional[str] = None


@dataclass
class GetAvailableFormsResponse:
    """
    Response for Get Available Forms
    """

    forms: Optional[List[Dict[str, Any]]] = None
    """forms"""
    total: Optional[int] = None
    """total"""


# Client Class

class FormstackformsClient(ConnectorClientBase):
    """Typed client for formstackforms connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a FormstackformsClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "formstackforms"

    async def get_available_forms_async(
        self,
    ) -> dict[str, Any] | None:
        """
        Get Available Forms

        Returns all available forms
        """
        request_url = f"{self._connection_runtime_url}/api/v2/form/"

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_form_schema_async(
        self,
        form_id: str,
    ) -> None:
        """
        Returns Form Schema from Webhook API

        Used for the x-ms-dynamic-schema
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/api/v2/form/{quote(str(form_id), safe='')}/webhookopenapi/"
        )
        query_params = []
        query_params.append("file_transfer_type=" + quote("base64encode"))
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )


# Trigger Operations
#
# Trigger routes are not callable client methods. Register a trigger with the
# Connector Namespace trigger-config API using the operation id and required
# parameters below; Connector Namespace invokes the callback when the trigger
# fires. When the callback body has a JSON schema, ``callback_payload_type``
# names the generated dataclass to deserialize the callback payload into.
TRIGGER_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "FormstackFormSubmitted": {
        "operation_id": "FormstackFormSubmitted",
        "path": "/{connectionId}/api/v2/form/{form_id}/webhook/",
        "method": "post",
        "required_parameters": ["form_id", "body"],
        "callback_payload_type": "FormstackFormSubmittedResponse",
    },
}
