# Copyright (c) Microsoft Corporation. All rights reserved.

# GoogledriveClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict, List
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class BlobMetadata:
    """
    Response for Get file metadata using id
    """

    id: Optional[str] = field(default=None, metadata={"wire_name": "Id"})
    """The unique id of the file or folder."""
    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """The name of the file or folder."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """The display name of the file or folder."""
    path: Optional[str] = field(default=None, metadata={"wire_name": "Path"})
    """The path of the file or folder."""
    folder_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "FolderId"},
    )
    """The unique id of the parent folder of the file or folder."""
    folder_path: Optional[str] = field(
        default=None,
        metadata={"wire_name": "FolderPath"},
    )
    """The current path of the parent folder of the file or folder."""
    last_modified: Optional[str] = field(
        default=None,
        metadata={"wire_name": "LastModified"},
    )
    """The date and time the file or folder was last modified."""
    size: Optional[int] = field(default=None, metadata={"wire_name": "Size"})
    """The size of the file or folder."""
    media_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "MediaType"},
    )
    """The media type of the file or folder."""
    is_folder: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "IsFolder"},
    )
    """
    A boolean value (true, false) to indicate whether or not the blob is a
    folder.
    """
    e_tag: Optional[str] = field(default=None, metadata={"wire_name": "ETag"})
    """The etag of the file or folder."""
    file_locator: Optional[str] = field(
        default=None,
        metadata={"wire_name": "FileLocator"},
    )
    """The filelocator of the file or folder."""
    last_modified_by: Optional[str] = field(
        default=None,
        metadata={"wire_name": "LastModifiedBy"},
    )
    """The user who last modified the file or folder."""


@dataclass
class DataSetsMetadata:
    """
    Definition: DataSetsMetadata
    """

    tabular: Optional[TabularDataSetsMetadata] = None
    blob: Optional[BlobDataSetsMetadata] = None


@dataclass
class TabularDataSetsMetadata:
    """
    Definition: TabularDataSetsMetadata
    """

    source: Optional[str] = None
    """Dataset source"""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "displayName"},
    )
    """Dataset display name"""
    url_encoding: Optional[str] = field(
        default=None,
        metadata={"wire_name": "urlEncoding"},
    )
    """Dataset url encoding"""
    table_display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "tableDisplayName"},
    )
    """Table display name"""
    table_plural_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "tablePluralName"},
    )
    """Table plural display name"""


@dataclass
class BlobDataSetsMetadata:
    """
    Definition: BlobDataSetsMetadata
    """

    source: Optional[str] = None
    """Blob dataset source"""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "displayName"},
    )
    """Blob dataset display name"""
    url_encoding: Optional[str] = field(
        default=None,
        metadata={"wire_name": "urlEncoding"},
    )
    """Blob dataset url encoding"""


@dataclass
class ObjectEntity:
    """
    Definition: Object
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class TableMetadata:
    """
    Definition: TableMetadata
    """

    name: Optional[str] = None
    """Table name"""
    title: Optional[str] = None
    """Table title"""
    x_ms_permission: Optional[str] = field(
        default=None,
        metadata={"wire_name": "x-ms-permission"},
    )
    """Table permission"""
    x_ms_capabilities: Optional[TableCapabilitiesMetadata] = field(
        default=None,
        metadata={"wire_name": "x-ms-capabilities"},
    )
    schema: Optional[ObjectEntity] = None
    referenced_entities: Optional[ObjectEntity] = field(
        default=None,
        metadata={"wire_name": "referencedEntities"},
    )
    web_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "webUrl"},
    )
    """Url link"""


@dataclass
class TableCapabilitiesMetadata:
    """
    Definition: TableCapabilitiesMetadata
    """

    sort_restrictions: Optional[TableSortRestrictionsMetadata] = field(
        default=None,
        metadata={"wire_name": "sortRestrictions"},
    )
    filter_restrictions: Optional[TableFilterRestrictionsMetadata] = field(
        default=None,
        metadata={"wire_name": "filterRestrictions"},
    )
    select_restrictions: Optional[TableSelectRestrictionsMetadata] = field(
        default=None,
        metadata={"wire_name": "selectRestrictions"},
    )
    is_only_server_pagable: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "isOnlyServerPagable"},
    )
    """Server paging restrictions"""
    filter_function_support: Optional[List[str]] = field(
        default=None,
        metadata={"wire_name": "filterFunctionSupport"},
    )
    """List of supported filter capabilities"""
    server_paging_options: Optional[List[str]] = field(
        default=None,
        metadata={"wire_name": "serverPagingOptions"},
    )
    """List of supported server-driven paging capabilities"""


@dataclass
class TableSortRestrictionsMetadata:
    """
    Definition: TableSortRestrictionsMetadata
    """

    sortable: Optional[bool] = None
    """Indicates whether this table has sortable columns"""
    unsortable_properties: Optional[List[str]] = field(
        default=None,
        metadata={"wire_name": "unsortableProperties"},
    )
    """List of unsortable properties"""
    ascending_only_properties: Optional[List[str]] = field(
        default=None,
        metadata={"wire_name": "ascendingOnlyProperties"},
    )
    """List of properties which support ascending order only"""


@dataclass
class TableFilterRestrictionsMetadata:
    """
    Definition: TableFilterRestrictionsMetadata
    """

    filterable: Optional[bool] = None
    """Indicates whether this table has filterable columns"""
    non_filterable_properties: Optional[List[str]] = field(
        default=None,
        metadata={"wire_name": "nonFilterableProperties"},
    )
    """List of non filterable properties"""
    required_properties: Optional[List[str]] = field(
        default=None,
        metadata={"wire_name": "requiredProperties"},
    )
    """List of required properties"""


@dataclass
class TableSelectRestrictionsMetadata:
    """
    Definition: TableSelectRestrictionsMetadata
    """

    selectable: Optional[bool] = None
    """Indicates whether this table has selectable columns"""


@dataclass
class TablesList:
    """
    Definition: TablesList
    """

    value: Optional[List[Table]] = None
    """List of Tables"""


@dataclass
class Table:
    """
    Definition: Table
    """

    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """The name of the table. The name is used at runtime."""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """The display name of the table."""
    dynamic_properties: Optional[Dict[str, Any]] = field(
        default=None,
        metadata={"wire_name": "DynamicProperties"},
    )
    """Additional table properties provided by the connector to the clients."""


@dataclass
class Item:
    """
    Definition: Item
    """

    dynamic_properties: Optional[Dict[str, Any]] = field(
        default=None,
        metadata={"wire_name": "dynamicProperties"},
    )


@dataclass
class ItemsList:
    """
    Definition: ItemsList
    """

    value: Optional[List[Item]] = None
    """List of Items"""


@dataclass
class DataSetsList:
    """
    Definition: DataSetsList
    """

    value: Optional[List[DataSet]] = None
    """List of datasets"""


@dataclass
class DataSet:
    """
    Definition: DataSet
    """

    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """Dataset name"""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """Dataset display name"""
    query: Optional[List[PassThroughNativeQuery]] = None
    """Pass-through Native Queries"""


@dataclass
class Procedure:
    """
    Definition: Procedure
    """

    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """Procedure name"""
    display_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "DisplayName"},
    )
    """Procedure display name"""


@dataclass
class PassThroughNativeQuery:
    """
    Definition: PassThroughNativeQuery
    """

    language: Optional[str] = field(
        default=None,
        metadata={"wire_name": "Language"},
    )
    """Query language"""


# Client Class

class GoogledriveClient(ConnectorClientBase):
    """Typed client for googledrive connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a GoogledriveClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "googledrive"

    async def get_file_metadata_async(
        self,
        id: str,
    ) -> dict[str, Any] | None:
        """
        Get file metadata using id

        Retrieves file metadata from Google Drive using id
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/datasets"
            f"/default"
            f"/files"
            f"/{quote(quote(str(id), safe=''), safe='')}"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def update_file_async(
        self,
        input: bytes,
        id: str,
    ) -> dict[str, Any] | None:
        """
        Update file

        Updates a file in Google Drive
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/datasets"
            f"/default"
            f"/files"
            f"/{quote(quote(str(id), safe=''), safe='')}"
        )

        response = await self.http_client.send_async(
            "PUT",
            request_url,
            body=input,
            content_type="application/octet-stream",
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_file_async(
        self,
        id: str,
    ) -> None:
        """
        Delete file

        Deletes a file from Google Drive
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/datasets"
            f"/default"
            f"/files"
            f"/{quote(quote(str(id), safe=''), safe='')}"
        )

        response = await self.http_client.send_async(
            "DELETE", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "DELETE",
                request_url,
                response.status,
                response.text,
            )

    async def get_file_metadata_by_path_async(
        self,
        path: str,
    ) -> dict[str, Any] | None:
        """
        Get file metadata using path

        Retrieves file metadata from Google Drive using path
        """
        request_url = (
            f"{self._connection_runtime_url}/datasets/default/GetFileByPath"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(path)
        if isinstance(path, bool):
            value = value.lower()
        query_params.append(f"path={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_file_content_by_path_async(
        self,
        path: str,
        infer_content_type: Optional[bool] = None,
    ) -> bytes:
        """
        Get file content using path

        Retrieves file content from Google Drive using path
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/datasets/default/GetFileContentByPath"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(path)
        if isinstance(path, bool):
            value = value.lower()
        query_params.append(f"path={quote(value)}")
        if infer_content_type is not None:
            value = str(infer_content_type)
            if isinstance(infer_content_type, bool):
                value = value.lower()
            query_params.append(f"inferContentType={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        return response.content

    async def get_file_content_async(
        self,
        id: str,
        infer_content_type: Optional[bool] = None,
    ) -> bytes:
        """
        Get file content using id

        Retrieves file content from Google Drive using id
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/datasets"
            f"/default"
            f"/files"
            f"/{quote(quote(str(id), safe=''), safe='')}"
            f"/content"
        )
        query_params = []
        if infer_content_type is not None:
            value = str(infer_content_type)
            if isinstance(infer_content_type, bool):
                value = value.lower()
            query_params.append(f"inferContentType={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        return response.content

    async def copy_file_async(
        self,
        source: str,
        destination: str,
        overwrite: Optional[bool] = None,
    ) -> dict[str, Any] | None:
        """
        Copy file

        Copies a file on Google Drive
        """
        request_url = (
            f"{self._connection_runtime_url}/datasets/default/copyFile"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(source)
        if isinstance(source, bool):
            value = value.lower()
        query_params.append(f"source={quote(value)}")
        value = str(destination)
        if isinstance(destination, bool):
            value = value.lower()
        query_params.append(f"destination={quote(value)}")
        if overwrite is not None:
            value = str(overwrite)
            if isinstance(overwrite, bool):
                value = value.lower()
            query_params.append(f"overwrite={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_folder_async(
        self,
        id: str,
    ) -> dict[str, Any] | None:
        """
        List files in folder

        List files in a Google Drive folder
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/datasets"
            f"/default"
            f"/folders"
            f"/{quote(quote(str(id), safe=''), safe='')}"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_root_folder_async(
        self,
    ) -> dict[str, Any] | None:
        """
        List files in root folder

        Lists files in the Google Drive root folder
        """
        request_url = (
            f"{self._connection_runtime_url}/datasets/default/folders"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_file_async(
        self,
        input: bytes,
        folder_id: str,
        name: str,
    ) -> dict[str, Any] | None:
        """
        Create file

        Uploads a file to a Google Drive folder selected by its identifier
        """
        request_url = (
            f"{self._connection_runtime_url}/datasets/default/v2/files"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(folder_id)
        if isinstance(folder_id, bool):
            value = value.lower()
        query_params.append(f"folderId={quote(value)}")
        value = str(name)
        if isinstance(name, bool):
            value = value.lower()
        query_params.append(f"name={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST",
            request_url,
            body=input,
            content_type="application/octet-stream",
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def extract_folder_async(
        self,
        source: str,
        destination: str,
        overwrite: Optional[bool] = None,
    ) -> dict[str, Any] | None:
        """
        Extract archive to folder

        Extracts an archive file into a folder in Google Drive (example: .zip)
        """
        request_url = (
            f"{self._connection_runtime_url}/datasets/default/extractFolderV2"
        )
        query_params = []
        query_params.append("queryParametersSingleEncoded=" + quote("true"))
        value = str(source)
        if isinstance(source, bool):
            value = value.lower()
        query_params.append(f"source={quote(value)}")
        value = str(destination)
        if isinstance(destination, bool):
            value = value.lower()
        query_params.append(f"destination={quote(value)}")
        if overwrite is not None:
            value = str(overwrite)
            if isinstance(overwrite, bool):
                value = value.lower()
            query_params.append(f"overwrite={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "POST", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)
