# Copyright (c) Microsoft Corporation. All rights reserved.

# GoogletasksClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict, List
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class TaskListList:
    """
    Response for List task lists
    """

    items: Optional[List[TaskListEntry]] = None
    """Task lists in the lists."""


@dataclass
class TaskListEntry:
    """
    Response for Create a task list
    """

    id: Optional[str] = None
    """The identifier of the task list."""
    title: Optional[str] = None
    """The title of the task list."""
    self_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "selfLink"},
    )
    """A link to this task list."""
    updated: Optional[str] = None
    """The time the task list was last updated."""


@dataclass
class TaskList:
    """
    Response for Lists the tasks for a task list
    """

    items: Optional[List[TaskObject]] = None
    """The tasks in the list."""


@dataclass
class TaskObject:
    """
    Response for Create a task in a task list
    """

    id: Optional[str] = None
    """The identifier of the task."""
    title: Optional[str] = None
    """The title of the task."""
    updated: Optional[str] = None
    """The last time the task was updated."""
    self_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "selfLink"},
    )
    """A link to the task."""
    parent: Optional[str] = None
    """The parent of the task."""
    position: Optional[str] = None
    """The position of the task."""
    notes: Optional[str] = None
    """The notes for the task."""
    status: Optional[str] = None
    """The status of the task."""
    due: Optional[str] = None
    """The datetime the task is due."""
    completed: Optional[str] = None
    """The datetime the task was completed."""


@dataclass
class TaskListCreate:
    """
    Definition: TaskListCreate
    """

    title: Optional[str] = None
    """The title of the task list."""


@dataclass
class TaskCreate:
    """
    Definition: TaskCreate
    """

    title: Optional[str] = None
    """The title of the task."""
    notes: Optional[str] = None
    """The notes for the task."""
    due: Optional[str] = None
    """The datetime the task is due."""


# Client Class

class GoogletasksClient(ConnectorClientBase):
    """Typed client for googletasks connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a GoogletasksClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "googletasks"

    async def list_task_lists_async(
        self,
    ) -> dict[str, Any] | None:
        """
        List task lists

        List all task lists.
        """
        request_url = f"{self._connection_runtime_url}/users/@me/lists"

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_task_list_async(
        self,
        input: TaskListCreate,
    ) -> dict[str, Any] | None:
        """
        Create a task list

        Creates a new task list.
        """
        request_url = f"{self._connection_runtime_url}/users/@me/lists"

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_tasks_async(
        self,
        task_list_id: str,
    ) -> dict[str, Any] | None:
        """
        Lists the tasks for a task list

        Lists the tasks for a specific task list.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/lists/{quote(str(task_list_id), safe='')}/tasks"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def craete_task_async(
        self,
        input: TaskCreate,
        task_list_id: str,
    ) -> dict[str, Any] | None:
        """
        Create a task in a task list

        Create a task in a specific task list.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/lists/{quote(str(task_list_id), safe='')}/tasks"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_task_async(
        self,
        task_list_id: str,
        task_id: str,
    ) -> dict[str, Any] | None:
        """
        Get a task from a task list

        Get specific task from the specified task list.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/lists"
            f"/{quote(str(task_list_id), safe='')}"
            f"/tasks"
            f"/{quote(str(task_id), safe='')}"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)


# Trigger Operations
#
# Trigger routes are not callable client methods. Register a trigger with the
# Connector Namespace trigger-config API using the operation id and required
# parameters below; Connector Namespace invokes the callback when the trigger
# fires. When the callback body has a JSON schema, ``callback_payload_type``
# names the generated dataclass to deserialize the callback payload into.
TRIGGER_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "OnNewTaskList": {
        "operation_id": "OnNewTaskList",
        "path": "/{connectionId}/trigger1/users/@me/lists",
        "method": "get",
        "required_parameters": [],
        "callback_payload_type": "TaskListList",
    },
    "OnNewTaskInList": {
        "operation_id": "OnNewTaskInList",
        "path": "/{connectionId}/trigger2/lists/{taskListId}/tasks",
        "method": "get",
        "required_parameters": ["taskListId"],
        "callback_payload_type": "TaskList",
    },
    "OnDueTaskInList": {
        "operation_id": "OnDueTaskInList",
        "path": "/{connectionId}/trigger4/lists/{taskListId}/tasks",
        "method": "get",
        "required_parameters": ["taskListId"],
        "callback_payload_type": "TaskList",
    },
    "OnCompletedTaskInListV2": {
        "operation_id": "OnCompletedTaskInListV2",
        "path": "/{connectionId}/trigger5/lists/{taskListId}/tasks",
        "method": "get",
        "required_parameters": ["taskListId"],
        "callback_payload_type": "TaskList",
    },
}
