# Copyright (c) Microsoft Corporation. All rights reserved.

# MicrosoftbookingsClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict, List
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class CreateAppointmentInput:
    """When an appointment is created"""

    webhook: Optional[Dict[str, Any]] = None


@dataclass
class WebhookResponse:
    """Response for When an appointment is created"""

    webhook_id: Optional[str] = None
    """Webhook ID."""


@dataclass
class UpdateAppointmentInput:
    """When an appointment is Updated"""

    webhook: Optional[Dict[str, Any]] = None


@dataclass
class CancelAppointmentInput:
    """When an appointment is Cancelled"""

    webhook: Optional[Dict[str, Any]] = None


@dataclass
class ListMailboxResponse:
    """Response for List Booking Businesses where user is an admin"""

    mailboxes: Optional[List[MailboxEntity]] = None
    """All mailbox entities."""


@dataclass
class DeleteWebhookResponse:
    """Definition: DeleteWebhookResponse"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class MailboxEntity:
    """Definition: MailboxEntity"""

    display_name: Optional[str] = None
    """Mailbox Display name."""
    email: Optional[str] = None
    """SMTP of the Booking mailbox."""


@dataclass
class AppointmentData:
    """Definition: AppointmentData"""

    additional_info: Optional[str] = None
    """Additional Info about the booking."""
    customer_email: Optional[str] = None
    """Customer Email address in case of 1:1 bookings."""
    customer_id: Optional[str] = None
    """Customer Id in case of 1:1 bookings."""
    customer_location: Optional[Dict[str, Any]] = None
    """Location of customer in 1:1 booking"""
    customer_name: Optional[str] = None
    """Customer Name for 1:1 booking."""
    customer_notes: Optional[str] = None
    """Customer Notes for 1:1 booking."""
    custom_question_answers: Optional[List[CustomQuestion]] = None
    """All the custom questions and answers for 1:1 booking."""
    customer_phone: Optional[str] = None
    """Customer phone for 1:1 booking."""
    customer_time_zone: Optional[str] = None
    """Customer Time Zone for 1:1 booking."""
    customers: Optional[List[CustomerData]] = None
    """List of customers in the 1:N booking"""
    duration: Optional[int] = None
    """Duration of the appointment"""
    end_time: Optional[str] = None
    """End Time of the appointment."""
    filled_attendees_count: Optional[int] = None
    """Number of attendees who have booked this appoinment slot."""
    id: Optional[str] = None
    """
    [Deprecated] - use selfServiceAppointmentId as unique identifier for the
    bookings appointment.
    """
    is_s_m_s_notifications_enabled: Optional[bool] = None
    """Field to check if SMS notification is enabled for the appointment."""
    join_web_u_r_l: Optional[str] = None
    """URL for joining this online appointment."""
    max_attendees_count: Optional[int] = None
    """Max number of attendees allowed in this appoinment."""
    self_service_appointment_id: Optional[str] = None
    """Appointment id for the booking appointment."""
    service_id: Optional[str] = None
    """Unique Service Identifier."""
    service_name: Optional[str] = None
    """Name of the bookings service."""
    service_notes: Optional[str] = None
    """Service level notes for the staff and admin."""
    staff_members: Optional[List[StaffMemberData]] = None
    """List of staff members"""
    start_time: Optional[str] = None
    """Start Time of the appointment."""
    tracking_data: Optional[str] = None
    """Campaign tracking Data."""
    cancel_reason: Optional[str] = None
    """Reason for cancellation of this booking appointment"""


@dataclass
class CustomerData:
    """Definition: CustomerData"""

    email: Optional[str] = None
    """Email of the customer in the group booking."""
    id: Optional[str] = None
    """Unique ID of the customer in the group booking."""
    location: Optional[Dict[str, Any]] = None
    """Location of customer in a group booking."""
    name: Optional[str] = None
    """Display Name of the customer in the group booking."""
    notes: Optional[str] = None
    """Notes of the customer in the group booking."""
    time_zone: Optional[str] = None
    """Timezone of the customer in the group booking."""
    answers: Optional[List[CustomQuestion]] = None
    """All the custom questions and answers."""


@dataclass
class StaffMemberData:
    """Definition: StaffMemberData"""

    display_name: Optional[str] = None
    """Display Name of the staff assigned for this appointment."""
    email_address: Optional[str] = None
    """Email Address of the staff assigned to this appointment."""
    id: Optional[str] = None
    """Unique Staff identifier."""


@dataclass
class CustomQuestion:
    """Definition: CustomQuestion"""

    answer: Optional[str] = None
    """Answer to this custom question."""
    answer_options: Optional[List[str]] = None
    """All the answer options."""
    is_required: Optional[bool] = None
    """Tells if answering this question is mandatory."""
    question: Optional[str] = None
    """Question to be answered."""
    question_id: Optional[str] = None
    """Unique Identifier of the Question to be answered."""
    selected_options: Optional[List[int]] = None
    """All the selected answer options."""


# Client Class

class MicrosoftbookingsClient(ConnectorClientBase):
    """Typed client for microsoftbookings connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a MicrosoftbookingsClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "microsoftbookings"

    async def create_appointment_async(
        self,
        input: CreateAppointmentInput,
        s_m_t_p_address: str,
    ):
        """
        When an appointment is created

        This trigger is used for listening to create of bookings appointments.
        Select a booking page or enter the SMTP address of the booking page
        that you are looking forward to listen for create appointment events
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/BookingsService"
            f"/api"
            f"/V1"
            f"/bookingBusinesses"
            f"/{str(s_m_t_p_address)}"
            f"/webhook"
            f"/AppointmentCreated"
        )

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def update_appointment_async(
        self,
        input: UpdateAppointmentInput,
        s_m_t_p_address: str,
    ):
        """
        When an appointment is Updated

        This trigger is used for listening to update of bookings appointments.
        Select a booking page or enter the SMTP address of the booking page
        that you are looking forward to listen for update appointment events.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/BookingsService"
            f"/api"
            f"/V1"
            f"/bookingBusinesses"
            f"/{str(s_m_t_p_address)}"
            f"/webhook"
            f"/AppointmentUpdated"
        )

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

    async def cancel_appointment_async(
        self,
        input: CancelAppointmentInput,
        s_m_t_p_address: str,
    ):
        """
        When an appointment is Cancelled

        This trigger is used for listening to cancel of bookings appointments.
        Select a booking page or enter the SMTP address of the booking page
        that you are looking forward to listen for cancel appointment events.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/BookingsService"
            f"/api"
            f"/V1"
            f"/bookingBusinesses"
            f"/{str(s_m_t_p_address)}"
            f"/webhook"
            f"/AppointmentDeleted"
        )

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

    async def list_bookings_business_user_as_admin_async(
        self,
    ):
        """
        List Booking Businesses where user is an admin

        Operation used to list all mailboxes for which the accessing user is an
        Administrator.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/BookingsService/api/V1/bookingBusinessesUserAsAdmin"
        )

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)
