# Copyright (c) Microsoft Corporation. All rights reserved.

# MondayClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class WebhookCreateItemInput:
    """
    When an item is created
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select a workspace from the drop-down or specify a workspace ID."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    callback_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "callbackUrl"},
    )
    """Specify the callback URL"""


@dataclass
class WebhookCreateItemResponse:
    """
    Response for When an item is created
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookCreateUpdateInput:
    """
    When a new update is posted
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select a workspace from the drop-down or specify a workspace ID."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    callback_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "callbackUrl"},
    )
    """Specify the callback URL."""


@dataclass
class WebhookCreateUpdateResponse:
    """
    Response for When a new update is posted
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookChangeNameInput:
    """
    When an item's name changes
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select a workspace from the drop-down or specify a workspace ID."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    callback_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "callbackUrl"},
    )
    """Specify the callback URL."""


@dataclass
class WebhookChangeNameResponse:
    """
    Response for When an item's name changes
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookChangeSubitemNameInput:
    """
    When a subitem's name changes
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select a workspace from the drop-down or specify a workspace ID."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    callback_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "callbackUrl"},
    )
    """Specify the callback URL."""


@dataclass
class WebhookChangeSubitemNameResponse:
    """
    Response for When a subitem's name changes
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookCreateSubitemInput:
    """
    When a subitem is created
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select a workspace from the drop-down or specify a workspace ID."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    callback_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "callbackUrl"},
    )
    """Specify the callback URL."""


@dataclass
class WebhookCreateSubitemResponse:
    """
    Response for When a subitem is created
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookColumnChangesInput:
    """
    When a column changes
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select a workspace from the drop-down or specify a workspace ID."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    column_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "columnId"},
    )
    """Select a column from the drop-down."""
    callback_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "callbackUrl"},
    )
    """Specify the callback URL."""


@dataclass
class WebhookColumnChangesResponse:
    """
    Response for When a column changes
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookAnyColumnChangesInput:
    """
    When any column changes
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select a workspace from the drop-down or specify a workspace ID."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    callback_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "callbackUrl"},
    )
    """Specify the callback URL."""


@dataclass
class WebhookAnyColumnChangesResponse:
    """
    Response for When any column changes
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookSubitemColumnChangesInput:
    """
    When any subitem column changes
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select a workspace from the drop-down or specify a workspace ID."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    callback_url: Optional[str] = field(
        default=None,
        metadata={"wire_name": "callbackUrl"},
    )
    """Specify the callback URL."""


@dataclass
class WebhookSubitemColumnChangesResponse:
    """
    Response for When any subitem column changes
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class CreateItemInput:
    """
    Create an item
    """

    workspace_id: Optional[FieldWorkspace] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    board_id: Optional[FieldBoard] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    group_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "groupId"},
    )
    """Select a group from the drop-down or specify a group ID."""
    item_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "itemName"},
    )
    """Specify the name of the item you want to create."""
    column_values: Optional[DynamicResponseGetListSchema] = field(
        default=None,
        metadata={"wire_name": "columnValues"},
    )


@dataclass
class CreateItemResponse:
    """
    Response for Create an item
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class DuplicateBoardInput:
    """
    Duplicate a board
    """

    source_workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "sourceWorkspaceId"},
    )
    """Select the workspace for the board you want to duplicate."""
    source_board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "sourceBoardId"},
    )
    """Select the board to duplicate."""
    duplicated_board_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "duplicatedBoardName"},
    )
    """Specify the name of the duplicated board."""
    duplication_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "duplicationType"},
    )
    """Select the duplication type from the drop-down."""
    destination_workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "destinationWorkspaceId"},
    )
    """Select the destination workspace for the duplicated board."""
    destination_folder: Optional[str] = field(
        default=None,
        metadata={"wire_name": "destinationFolder"},
    )
    """Select the destination folder for the duplicated board."""
    keep_board_subscribers: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "keepBoardSubscribers"},
    )
    """Select whether to keep board subscribers."""


@dataclass
class DuplicateBoardResponse:
    """
    Response for Duplicate a board
    """

    id: Optional[str] = None
    """The ID of the duplicated board"""


@dataclass
class CreateBoardInput:
    """
    Create a board
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Specify the ID of a monday.com workspace."""
    board_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardName"},
    )
    """Specify the desired name of the board you want to create."""


@dataclass
class CreateBoardResponse:
    """
    Response for Create a board
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class CreateColumnInput:
    """
    Create a column
    """

    workspace_id: Optional[FieldWorkspace] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    board_id: Optional[FieldBoard] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    title: Optional[str] = None
    """Specify the title of the column you want to create."""
    description: Optional[str] = None
    """Specify the description of the column you want to create."""
    column_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "columnType"},
    )
    """Select a column type from the drop-down."""


@dataclass
class CreateColumnResponse:
    """
    Response for Create a column
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class CreateGroupInput:
    """
    Create a group
    """

    workspace_id: Optional[FieldWorkspace] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    board_id: Optional[FieldBoard] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    group_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "groupName"},
    )
    """Specify your desired group name."""


@dataclass
class CreateGroupResponse:
    """
    Response for Create a group
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class UpdateItemColumnInput:
    """
    Update an item's column value
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select the workspace the item belongs to from the drop-down."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select the board the item belongs to from the drop-down."""
    column_id: Optional[FieldColumnsToUpdateSingleColumn] = field(
        default=None,
        metadata={"wire_name": "columnId"},
    )
    item_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "itemId"},
    )
    """Specify the ID of the item to update."""
    column_values: Optional[DynamicResponseGetSingleColumnSchema] = field(
        default=None,
        metadata={"wire_name": "columnValues"},
    )


@dataclass
class UpdateItemColumnResponse:
    """
    Response for Update an item's column value
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class UpdateMultipleItemColumnsInput:
    """
    Update multiple item column values
    """

    workspace_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    """Select the workspace the item belongs to from the drop-down."""
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select the board the item belongs to from the drop-down."""
    item_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "itemId"},
    )
    """Specify the ID of the item to update."""
    item_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "itemName"},
    )
    """
    Specify a new name for the item. Leave blank to keep the current name.
    """
    column_values: Optional[DynamicResponseGetListSchema] = field(
        default=None,
        metadata={"wire_name": "columnValues"},
    )


@dataclass
class UpdateMultipleItemColumnsResponse:
    """
    Response for Update multiple item column values
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class MoveItemToGroupInput:
    """
    Move an item to a group
    """

    workspace_id: Optional[FieldWorkspace] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    board_id: Optional[FieldBoard] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    group_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "groupId"},
    )
    """Select the group to move the item to from the drop-down."""
    item_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "itemId"},
    )
    """Specify the ID of the item to move."""


@dataclass
class MoveItemToGroupResponse:
    """
    Response for Move an item to a group
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class CreateNotificationInput:
    """
    Create a notification
    """

    user_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "userId"},
    )
    """Select a user from the drop-down or specify a user ID."""
    target_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "targetId"},
    )
    """Specify a board ID or item ID the notification will go to."""
    text: Optional[str] = None
    """Specify the notification text."""


@dataclass
class CreateNotificationResponse:
    """
    Response for Create a notification
    """

    data: Optional[Dict[str, Any]] = None
    """Data"""


@dataclass
class CreateSubitemInput:
    """
    Create a subitem
    """

    workspace_id: Optional[FieldWorkspace] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    board_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    """Select a board from the drop-down or specify a board ID."""
    parent_item_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "parentItemId"},
    )
    """Select a parent item from the drop-down or specify a parent item ID."""
    item_name: Optional[str] = field(
        default=None,
        metadata={"wire_name": "itemName"},
    )
    """Specify a name for the subitem."""
    column_values: Optional[DynamicResponseGetListSchema] = field(
        default=None,
        metadata={"wire_name": "columnValues"},
    )


@dataclass
class CreateSubitemResponse:
    """
    Response for Create a subitem
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class GetSubitemColumnNamesForGetSubitems:
    """
    Response for Get subitems
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class CreateUpdateInput:
    """
    Create an update
    """

    workspace_id: Optional[FieldWorkspace] = field(
        default=None,
        metadata={"wire_name": "workspaceId"},
    )
    board_id: Optional[FieldBoard] = field(
        default=None,
        metadata={"wire_name": "boardId"},
    )
    group_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "groupId"},
    )
    """Select a group from the drop-down or specify a group ID."""
    item_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "itemId"},
    )
    """Select an item from the drop-down or specify an item ID."""
    body: Optional[str] = None
    """Specify text for the update."""


@dataclass
class CreateUpdateResponse:
    """
    Response for Create an update
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class DynamicResponseGetListSchemaGet:
    """
    Response for Get an item by ID
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class CreateWorkspaceInput:
    """
    Create a workspace
    """

    name: Optional[str] = None
    """Specify a name for the new workspace."""
    description: Optional[str] = None
    """Specify a description for the new workspace."""


@dataclass
class CreateWorkspaceResponse:
    """
    Response for Create a workspace
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class DynamicGetGetItemsSchema:
    """
    Response for Get items
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class GetTagsResponse:
    """
    Response for Get tags
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class GetUsersResponse:
    """
    Response for Get users
    """

    data: Optional[Dict[str, Any]] = None


@dataclass
class GetWorkspacesResponse:
    """
    Response for Get workspaces
    """

    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class GetColumnNamesSchemaResponse:
    """
    Response for Get column names for a board ID
    """

    schema: Optional[Dict[str, Any]] = None
    """Schema of the requested schema type"""


@dataclass
class GetSingleColumnSchemaResponse:
    """
    Response for Gets single column schema for a board ID
    """

    schema: Optional[Dict[str, Any]] = None
    """Schema of the requested schema type"""


@dataclass
class GetColumnNamesSchemaForWebhookResponse:
    """
    Response for Get column names for a board ID for a webhook
    """

    schema: Optional[Dict[str, Any]] = None
    """Schema of the requested schema type"""


@dataclass
class GetSchemaForGetItemsActionResponse:
    """
    Response for Get column names for a board ID for a webhook
    """

    schema: Optional[Dict[str, Any]] = None
    """Schema of the requested schema type"""


@dataclass
class GetColumnNamesSchemaForUpdateWebhookResponse:
    """
    Response for Get column names for a board ID for an update webhook
    """

    schema: Optional[Dict[str, Any]] = None
    """Schema of the requested schema type"""


@dataclass
class GetSubitemColumnNamesResponse:
    """
    Response for Get subitem column names
    """

    schema: Optional[Dict[str, Any]] = None
    """Schema of the requested schema type"""


@dataclass
class GetSubitemSchemaResponse:
    """
    Response for Get subitem column names
    """

    schema: Optional[Dict[str, Any]] = None
    """Schema of the requested schema type"""


@dataclass
class DynamicResponseGetListSchema:
    """
    Definition: DynamicResponseGetListSchema
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicResponseGetSingleColumnSchema:
    """
    Definition: DynamicResponseGetSingleColumnSchema
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicGetColumnNamesForWebhook:
    """
    Definition: DynamicGetColumnNamesForWebhook
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicGetColumnNamesForUpdateWebhook:
    """
    Definition: DynamicGetColumnNamesForUpdateWebhook
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicGetSubitemColumnNamesForWebhook:
    """
    Definition: DynamicGetSubitemColumnNamesForWebhook
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class FieldWorkspace:
    """
    Definition: FieldWorkspace
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class FieldBoard:
    """
    Definition: FieldBoard
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class FieldColumnsToUpdateSingleColumn:
    """
    Definition: FieldColumnsToUpdateSingleColumn
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


# Client Class

class MondayClient(ConnectorClientBase):
    """Typed client for monday connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a MondayClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "monday"

    async def create_item_async(
        self,
        input: CreateItemInput,
    ) -> dict[str, Any] | None:
        """
        Create an item

        Creates an item in the selected monday.com board and group.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/CreateItem"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def duplicate_board_async(
        self,
        input: DuplicateBoardInput,
    ) -> dict[str, Any] | None:
        """
        Duplicate a board

        Duplicates a board in monday.com.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/DuplicateBoard"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_board_async(
        self,
        input: CreateBoardInput,
    ) -> dict[str, Any] | None:
        """
        Create a board

        Creates a board in monday.com.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/CreateBoard"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_column_async(
        self,
        input: CreateColumnInput,
    ) -> dict[str, Any] | None:
        """
        Create a column

        Creates a column in monday.com for the specified board.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/CreateColumn"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_group_async(
        self,
        input: CreateGroupInput,
    ) -> dict[str, Any] | None:
        """
        Create a group

        Creates a group in monday.com for the specified board.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/CreateGroup"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def update_item_column_async(
        self,
        input: UpdateItemColumnInput,
    ) -> dict[str, Any] | None:
        """
        Update an item's column value

        Updates a single item's column. If the value is blank, the column value
        will be cleared.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/UpdateItemColumn"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def update_multiple_item_columns_async(
        self,
        input: UpdateMultipleItemColumnsInput,
    ) -> dict[str, Any] | None:
        """
        Update multiple item column values

        Updates multiple item columns. Leave the column value blank to keep the
        current value.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/UpdateMultipleItemColumns"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def move_item_to_group_async(
        self,
        input: MoveItemToGroupInput,
    ) -> dict[str, Any] | None:
        """
        Move an item to a group

        Moves an item to another group on the same board.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/MoveItemToGroup"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_notification_async(
        self,
        input: CreateNotificationInput,
    ) -> dict[str, Any] | None:
        """
        Create a notification

        Creates a notification in monday.com for a user for either a specific
        board or item.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/CreateNotification"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_subitem_async(
        self,
        input: CreateSubitemInput,
    ) -> dict[str, Any] | None:
        """
        Create a subitem

        Creates a subitem in monday.com for the selected board and parent item.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/CreateSubitem"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_subitems_async(
        self,
        workspace_id: str,
        board_id: str,
        item_id: str,
    ) -> dict[str, Any] | None:
        """
        Get subitems

        Gets subitems in monday.com for a specific item in a board.
        """
        request_url = f"{self._connection_runtime_url}/getData/getSubitems"
        query_params = []
        value = str(workspace_id)
        if isinstance(workspace_id, bool):
            value = value.lower()
        query_params.append(f"workspaceId={quote(value)}")
        value = str(board_id)
        if isinstance(board_id, bool):
            value = value.lower()
        query_params.append(f"boardId={quote(value)}")
        value = str(item_id)
        if isinstance(item_id, bool):
            value = value.lower()
        query_params.append(f"itemId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_update_async(
        self,
        input: CreateUpdateInput,
    ) -> dict[str, Any] | None:
        """
        Create an update

        Creates an update in monday.com for a specific item.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/CreateUpdate"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_item_by_id_async(
        self,
        item_id: str,
        workspace_id: str,
        board_id: str,
    ) -> dict[str, Any] | None:
        """
        Get an item by ID

        Gets a monday.com item using the specified item ID and board.
        """
        request_url = f"{self._connection_runtime_url}/getData/getItemById"
        query_params = []
        value = str(item_id)
        if isinstance(item_id, bool):
            value = value.lower()
        query_params.append(f"itemId={quote(value)}")
        value = str(workspace_id)
        if isinstance(workspace_id, bool):
            value = value.lower()
        query_params.append(f"workspaceId={quote(value)}")
        value = str(board_id)
        if isinstance(board_id, bool):
            value = value.lower()
        query_params.append(f"boardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_workspace_async(
        self,
        input: CreateWorkspaceInput,
    ) -> dict[str, Any] | None:
        """
        Create a workspace

        Creates a monday.com workspace with a user-specified name and
        description.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/executePowerAutomateAction/CreateWorkspaceV2"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_items_async(
        self,
        workspace_id: str,
        board_id: str,
        group_id: str,
        filter1_column: Optional[str] = None,
        filter1_operator: Optional[str] = None,
        filter1_value: Optional[str] = None,
        filter2_column: Optional[str] = None,
        filter2_operator: Optional[str] = None,
        filter2_value: Optional[str] = None,
        filter3_column: Optional[str] = None,
        filter3_operator: Optional[str] = None,
        filter3_value: Optional[str] = None,
        filter4_column: Optional[str] = None,
        filter4_operator: Optional[str] = None,
        filter4_value: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Get items

        Gets items in monday.com for a specific board and group. Filter items
        by column values using the filters found under advanced options. More
        info on filtering can be found here:
        https://plugingenie.com/docs/filtering-items.
        """
        request_url = f"{self._connection_runtime_url}/getData/getItemsV2"
        query_params = []
        value = str(workspace_id)
        if isinstance(workspace_id, bool):
            value = value.lower()
        query_params.append(f"workspaceId={quote(value)}")
        value = str(board_id)
        if isinstance(board_id, bool):
            value = value.lower()
        query_params.append(f"boardId={quote(value)}")
        value = str(group_id)
        if isinstance(group_id, bool):
            value = value.lower()
        query_params.append(f"groupId={quote(value)}")
        if filter1_column is not None:
            value = str(filter1_column)
            if isinstance(filter1_column, bool):
                value = value.lower()
            query_params.append(f"filter1Column={quote(value)}")
        if filter1_operator is not None:
            value = str(filter1_operator)
            if isinstance(filter1_operator, bool):
                value = value.lower()
            query_params.append(f"filter1Operator={quote(value)}")
        if filter1_value is not None:
            value = str(filter1_value)
            if isinstance(filter1_value, bool):
                value = value.lower()
            query_params.append(f"filter1Value={quote(value)}")
        if filter2_column is not None:
            value = str(filter2_column)
            if isinstance(filter2_column, bool):
                value = value.lower()
            query_params.append(f"filter2Column={quote(value)}")
        if filter2_operator is not None:
            value = str(filter2_operator)
            if isinstance(filter2_operator, bool):
                value = value.lower()
            query_params.append(f"filter2Operator={quote(value)}")
        if filter2_value is not None:
            value = str(filter2_value)
            if isinstance(filter2_value, bool):
                value = value.lower()
            query_params.append(f"filter2Value={quote(value)}")
        if filter3_column is not None:
            value = str(filter3_column)
            if isinstance(filter3_column, bool):
                value = value.lower()
            query_params.append(f"filter3Column={quote(value)}")
        if filter3_operator is not None:
            value = str(filter3_operator)
            if isinstance(filter3_operator, bool):
                value = value.lower()
            query_params.append(f"filter3Operator={quote(value)}")
        if filter3_value is not None:
            value = str(filter3_value)
            if isinstance(filter3_value, bool):
                value = value.lower()
            query_params.append(f"filter3Value={quote(value)}")
        if filter4_column is not None:
            value = str(filter4_column)
            if isinstance(filter4_column, bool):
                value = value.lower()
            query_params.append(f"filter4Column={quote(value)}")
        if filter4_operator is not None:
            value = str(filter4_operator)
            if isinstance(filter4_operator, bool):
                value = value.lower()
            query_params.append(f"filter4Operator={quote(value)}")
        if filter4_value is not None:
            value = str(filter4_value)
            if isinstance(filter4_value, bool):
                value = value.lower()
            query_params.append(f"filter4Value={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_tags_async(
        self,
    ) -> dict[str, Any] | None:
        """
        Get tags

        This operation gets monday.com tags.
        """
        request_url = f"{self._connection_runtime_url}/getData/getTagsV2"

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_users_async(
        self,
    ) -> dict[str, Any] | None:
        """
        Get users

        This operation gets the name, email, and ID of users in your monday.com
        account.
        """
        request_url = f"{self._connection_runtime_url}/getData/getUsersV2"

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_workspaces_async(
        self,
    ) -> dict[str, Any] | None:
        """
        Get workspaces

        This operation gets the workspaces from monday.com.
        """
        request_url = f"{self._connection_runtime_url}/getData/getWorkspacesV2"

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_boards_async(
        self,
        workspace_id: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Get boards

        This operation gets the boards from monday.com.
        """
        request_url = f"{self._connection_runtime_url}/getData/getBoards"
        query_params = []
        if workspace_id is not None:
            value = str(workspace_id)
            if isinstance(workspace_id, bool):
                value = value.lower()
            query_params.append(f"workspaceId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_groups_for_get_items_async(
        self,
        board_id: str,
    ) -> dict[str, Any] | None:
        """
        Get groups for the Get Items operation

        This operation gets the groups from monday.com, which includes the
        option to select all groups.
        """
        request_url = (
            f"{self._connection_runtime_url}/getData/getGroupsForGetItems"
        )
        query_params = []
        value = str(board_id)
        if isinstance(board_id, bool):
            value = value.lower()
        query_params.append(f"boardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_columns_for_item_filtering_async(
        self,
        board_id: str,
    ) -> dict[str, Any] | None:
        """
        Get columns for item filtering

        This operation gets the columns from monday.com for item filtering.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/getData/getColumnsForItemFiltering"
        )
        query_params = []
        value = str(board_id)
        if isinstance(board_id, bool):
            value = value.lower()
        query_params.append(f"boardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_column_filter_operator_async(
        self,
        board_id: str,
        column_id: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Get column filter operator

        This operation gets the available item filter operator for the selected
        monday.com column.
        """
        request_url = (
            f"{self._connection_runtime_url}/getData/getColumnFilterOperator"
        )
        query_params = []
        value = str(board_id)
        if isinstance(board_id, bool):
            value = value.lower()
        query_params.append(f"boardId={quote(value)}")
        if column_id is not None:
            value = str(column_id)
            if isinstance(column_id, bool):
                value = value.lower()
            query_params.append(f"columnId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_column_names_schema_async(
        self,
        board_id: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Get column names for a board ID

        This operation gets the column names for a board ID.
        """
        request_url = (
            f"{self._connection_runtime_url}/getSchema/getColumnNames"
        )
        query_params = []
        if board_id is not None:
            value = str(board_id)
            if isinstance(board_id, bool):
                value = value.lower()
            query_params.append(f"boardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_single_column_schema_async(
        self,
        board_id: Optional[str] = None,
        column_id: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Gets single column schema for a board ID

        This operation gets the single column schema for a board ID.
        """
        request_url = (
            f"{self._connection_runtime_url}/getSchema/getSingleColumnSchema"
        )
        query_params = []
        if board_id is not None:
            value = str(board_id)
            if isinstance(board_id, bool):
                value = value.lower()
            query_params.append(f"boardId={quote(value)}")
        if column_id is not None:
            value = str(column_id)
            if isinstance(column_id, bool):
                value = value.lower()
            query_params.append(f"columnId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_column_names_schema_for_webhook_async(
        self,
        board_id: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Get column names for a board ID for a webhook

        This operation gets the column names for a board ID for a webhook
        (includes itemId).
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/getSchema/getColumnNamesForWebhook"
        )
        query_params = []
        if board_id is not None:
            value = str(board_id)
            if isinstance(board_id, bool):
                value = value.lower()
            query_params.append(f"boardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_schema_for_get_items_action_async(
        self,
        board_id: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Get column names for a board ID for a webhook

        This operation gets the schema for the GetItems action.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/getSchema/getSchemaForGetItemsAction"
        )
        query_params = []
        if board_id is not None:
            value = str(board_id)
            if isinstance(board_id, bool):
                value = value.lower()
            query_params.append(f"boardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_column_names_schema_for_update_webhook_async(
        self,
        board_id: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Get column names for a board ID for an update webhook

        This operation gets the column names for a board ID for a webhook
        (includes itemId).
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/getSchema/getColumnNamesForUpdateWebhook"
        )
        query_params = []
        if board_id is not None:
            value = str(board_id)
            if isinstance(board_id, bool):
                value = value.lower()
            query_params.append(f"boardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_subitem_column_names_async(
        self,
        parent_board_id: str,
    ) -> dict[str, Any] | None:
        """
        Get subitem column names

        Gets subitem column names in monday.com given a board ID.
        """
        request_url = (
            f"{self._connection_runtime_url}/getSchema/getSubitemColumnNames"
        )
        query_params = []
        value = str(parent_board_id)
        if isinstance(parent_board_id, bool):
            value = value.lower()
        query_params.append(f"parentBoardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_subitem_schema_async(
        self,
        parent_board_id: str,
    ) -> dict[str, Any] | None:
        """
        Get subitem column names

        Gets subitem schema in monday.com given a board ID.
        """
        request_url = (
            f"{self._connection_runtime_url}/getSchema/getSubitemSchema"
        )
        query_params = []
        value = str(parent_board_id)
        if isinstance(parent_board_id, bool):
            value = value.lower()
        query_params.append(f"parentBoardId={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)


# Trigger Operations
#
# Trigger routes are not callable client methods. Register a trigger with the
# Connector Namespace trigger-config API using the operation id and required
# parameters below; Connector Namespace invokes the callback when the trigger
# fires. When the callback body has a JSON schema, ``callback_payload_type``
# names the generated dataclass to deserialize the callback payload into.
TRIGGER_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "WebhookCreateItem": {
        "operation_id": "WebhookCreateItem",
        "path": "/{connectionId}/registerWebhook/CreateItem",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": "WebhookCreateItemResponse",
    },
    "WebhookCreateUpdate": {
        "operation_id": "WebhookCreateUpdate",
        "path": "/{connectionId}/registerWebhook/CreateUpdate",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": "WebhookCreateUpdateResponse",
    },
    "WebhookChangeName": {
        "operation_id": "WebhookChangeName",
        "path": "/{connectionId}/registerWebhook/ChangeName",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": "WebhookChangeNameResponse",
    },
    "WebhookChangeSubitemName": {
        "operation_id": "WebhookChangeSubitemName",
        "path": "/{connectionId}/registerWebhook/ChangeSubitemName",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": "WebhookChangeSubitemNameResponse",
    },
    "WebhookCreateSubitem": {
        "operation_id": "WebhookCreateSubitem",
        "path": "/{connectionId}/registerWebhook/CreateSubitem",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": "WebhookCreateSubitemResponse",
    },
    "WebhookColumnChanges": {
        "operation_id": "WebhookColumnChanges",
        "path": "/{connectionId}/registerWebhook/ColumnChanges",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": "WebhookColumnChangesResponse",
    },
    "WebhookAnyColumnChanges": {
        "operation_id": "WebhookAnyColumnChanges",
        "path": "/{connectionId}/registerWebhook/AnyColumnChanges",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": "WebhookAnyColumnChangesResponse",
    },
    "WebhookSubitemColumnChanges": {
        "operation_id": "WebhookSubitemColumnChanges",
        "path": "/{connectionId}/registerWebhook/SubitemColumnChanges",
        "method": "post",
        "required_parameters": ["body"],
        "callback_payload_type": "WebhookSubitemColumnChangesResponse",
    },
}
