# Copyright (c) Microsoft Corporation. All rights reserved.

# Office365groupsmailClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict, List
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class ListConversationsResponse:
    """
    Response for List the conversations of a group
    """

    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.nextLink"},
    )
    """Link to get next page of results"""
    value: Optional[List[Conversation]] = None


@dataclass
class CreateConversationResponse:
    """
    Response for Create a new conversation in a group
    """

    context: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.context"},
    )
    """The @odata.context link."""
    id: Optional[str] = None
    """New Conversation ID."""
    threads_odata_context: Optional[str] = field(
        default=None,
        metadata={"wire_name": "threads@odata.context"},
    )
    """The threads@odata.context link."""
    threads: Optional[List[Dict[str, Any]]] = None
    """Created conversation thread."""


@dataclass
class Conversation:
    """
    Response for Get a group conversation
    """

    id: Optional[str] = None
    """The conversations's unique identifier."""
    topic: Optional[str] = None
    """The topic of the conversation."""
    has_attachments: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "hasAttachments"},
    )
    """
    Indicates whether any of the posts within this Conversation has at least
    one attachment.
    """
    last_delivered_date_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "lastDeliveredDateTime"},
    )
    """
    The Timestamp type represents date and time information using ISO 8601
    format and is always in UTC time.
    """
    unique_senders: Optional[List[str]] = field(
        default=None,
        metadata={"wire_name": "uniqueSenders"},
    )
    """All the users that sent a message to this Conversation."""
    preview: Optional[str] = None
    """
    A short summary from the body of the latest post in this Conversation.
    """
    threads: Optional[List[ConversationThread]] = None


@dataclass
class ListConversationThreadsResponse:
    """
    Response for List the conversation threads of a conversation
    """

    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.nextLink"},
    )
    """Link to get next page of results"""
    context: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.context"},
    )
    """The Odata.context link."""
    value: Optional[List[ConversationThread]] = None


@dataclass
class NewConversationThreadResponse:
    """
    Response for Create a conversation thread
    """

    context: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.context"},
    )
    """The @odata.context link."""
    id: Optional[str] = None
    """New conversation thread ID."""


@dataclass
class ListGroupThreadsResponse:
    """
    Response for List the threads of a group
    """

    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.nextLink"},
    )
    """Link to get next page of results"""
    value: Optional[List[ConversationThread]] = None


@dataclass
class ConversationThread:
    """
    Response for Get a conversation thread
    """

    id: Optional[str] = None
    """The conversation thread's unique identifier."""
    topic: Optional[str] = None
    """The topic of the conversation."""
    has_attachments: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "hasAttachments"},
    )
    """
    Indicates whether any of the posts within this Conversation has at least
    one attachment.
    """
    last_delivered_date_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "lastDeliveredDateTime"},
    )
    """
    The Timestamp type represents date and time information using ISO 8601
    format and is always in UTC time.
    """
    unique_senders: Optional[List[str]] = field(
        default=None,
        metadata={"wire_name": "uniqueSenders"},
    )
    """All the users that sent a message to this Conversation."""
    preview: Optional[str] = None
    """
    A short summary from the body of the latest post in this Conversation.
    """
    is_locked: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "isLocked"},
    )
    """Indicates if the thread is locked."""
    to_recipients: Optional[List[EmailAddress]] = field(
        default=None,
        metadata={"wire_name": "toRecipients"},
    )
    """The To: recipients for the thread."""
    cc_recipients: Optional[List[EmailAddress]] = field(
        default=None,
        metadata={"wire_name": "ccRecipients"},
    )
    """The Cc: recipients for the thread."""
    posts: Optional[List[Post]] = None


@dataclass
class ListThreadPostsResponse:
    """
    Response for List the posts of a conversation thread
    """

    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.nextLink"},
    )
    """Link to get next page of results"""
    context: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.context"},
    )
    """The @odata.context link."""
    value: Optional[List[Post]] = None
    """Array containing the posts in the specified thread."""


@dataclass
class Post:
    """
    Response for Get a thread post
    """

    id: Optional[str] = None
    """The post's unique identifier."""
    created_date_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "createdDateTime"},
    )
    last_modified_date_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "lastModifiedDateTime"},
    )
    change_key: Optional[str] = field(
        default=None,
        metadata={"wire_name": "changeKey"},
    )
    """Identifies the version of the post."""
    conversation_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "conversationId"},
    )
    """Unique ID of the conversation the post belongs to."""
    conversation_thread_id: Optional[str] = field(
        default=None,
        metadata={"wire_name": "conversationThreadId"},
    )
    """Unique ID of the conversation thread the post belongs to."""
    categories: Optional[List[str]] = None
    """The categories associated with the post."""
    received_date_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "receivedDateTime"},
    )
    """Post received timestamp."""
    has_attachments: Optional[bool] = field(
        default=None,
        metadata={"wire_name": "hasAttachments"},
    )
    """Indicates whether the post has at least one attachment."""
    new_participants: Optional[List[EmailAddress]] = field(
        default=None,
        metadata={"wire_name": "newParticipants"},
    )
    """
    Conversation participants that were added to the thread as part of this
    post.
    """
    body: Optional[ItemBody] = None
    from_: Optional[EmailAddress] = field(
        default=None,
        metadata={"wire_name": "from"},
    )
    sender: Optional[EmailAddress] = None
    attachments: Optional[List[Attachment]] = None


@dataclass
class GetAttachmentsResponse:
    """
    Response for List the attachments of a post
    """

    next_link: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.nextLink"},
    )
    """Link to get next page of results"""
    context: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.context"},
    )
    """The @odata.context link."""
    value: Optional[List[Attachment]] = None
    """Array containing the attachments of the post."""


@dataclass
class OnNewEmailInGroupResponse:
    """
    Response for When a new email arrives to a group
    """

    value: Optional[List[ConversationTriggerResponse]] = None
    """Response of the trigger."""


@dataclass
class ObjectWithoutType:
    """
    Response for Send an HTTP request
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ListGroupsResponse:
    """
    Response for List user groups
    """

    value: Optional[List[Dict[str, Any]]] = None
    """Array with the groups the user is part of."""


@dataclass
class Attachment:
    """
    Definition: Attachment
    """

    id: Optional[str] = None
    """Id of the attachment."""
    name: Optional[str] = None
    """Name of attachment."""
    content_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "contentType"},
    )
    """Content type of attachment."""
    size: Optional[int] = None
    """Size of attachment."""
    content_bytes: Optional[str] = field(
        default=None,
        metadata={"wire_name": "contentBytes"},
    )
    """Content of attachment."""


@dataclass
class EmailAddress:
    """
    Definition: EmailAddress
    """

    email_address: Optional[Dict[str, Any]] = field(
        default=None,
        metadata={"wire_name": "emailAddress"},
    )
    """
    Represents information about a user in the sending or receiving end of an
    event, message or group post.
    """


@dataclass
class ItemBody:
    """
    Definition: ItemBody
    """

    content_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "contentType"},
    )
    """Content type of the body."""
    content: Optional[str] = None
    """Content of the body."""


@dataclass
class ReplyConversationThreadBody:
    """
    Definition: ReplyConversationThreadBody
    """

    post: Optional[NewPostBody] = None


@dataclass
class ForwardPostBody:
    """
    Definition: ForwardPost_V2Body
    """

    comment: Optional[str] = field(
        default=None,
        metadata={"wire_name": "Comment"},
    )
    """Comment to forward with the post."""
    to_recipients: Optional[List[GetUsersGraphAction]] = field(
        default=None,
        metadata={"wire_name": "ToRecipients"},
    )
    """The recipients to whom the threaded is forwarded to."""


@dataclass
class CreateConversationBody:
    """
    Definition: CreateConversationBody
    """

    topic: Optional[str] = None
    """Topic of the new conversation."""
    post: Optional[NewPostBody] = None


@dataclass
class NewPostBody:
    """
    Definition: NewPostBody
    """

    body: Optional[Dict[str, Any]] = None
    """Body of the new post."""
    categories: Optional[List[str]] = None
    """The categories associated with the post."""
    new_participants: Optional[List[GetUsersGraphAction]] = field(
        default=None,
        metadata={"wire_name": "newParticipants"},
    )
    """Add participants to the thread as part of this post."""
    attachments: Optional[List[ClientSendAttachment]] = None
    """File attachments to include."""


@dataclass
class GetUsersGraphAction:
    """
    Definition: GetUsers__GraphAction
    """

    email_address: Optional[Dict[str, Any]] = field(
        default=None,
        metadata={"wire_name": "EmailAddress"},
    )
    """User email address."""


@dataclass
class ClientSendAttachment:
    """
    Definition: ClientSendAttachment
    """

    type_: Optional[str] = field(
        default=None,
        metadata={"wire_name": "@odata.type"},
    )
    """@odata.type for a file attachment."""
    name: Optional[str] = field(default=None, metadata={"wire_name": "Name"})
    """Name of the attachment."""
    content_bytes: Optional[str] = field(
        default=None,
        metadata={"wire_name": "ContentBytes"},
    )
    """Content of the attachment."""


@dataclass
class ConversationTriggerResponse:
    """
    Definition: ConversationTriggerResponse
    """

    id: Optional[str] = None
    """The conversation unique identifier."""
    last_delivered_date_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "lastDeliveredDateTime"},
    )
    """
    The Timestamp type represents date and time information using ISO 8601
    format and is always in UTC time.
    """
    threads: Optional[List[ConversationThreadTriggerResponse]] = None


@dataclass
class ConversationThreadTriggerResponse:
    """
    Definition: ConversationThreadTriggerResponse
    """

    id: Optional[str] = None
    """The conversation thread's unique identifier."""
    posts: Optional[List[PostTriggerResponse]] = None


@dataclass
class PostTriggerResponse:
    """
    Definition: PostTriggerResponse
    """

    id: Optional[str] = None
    """The post's unique identifier."""
    last_modified_date_time: Optional[str] = field(
        default=None,
        metadata={"wire_name": "lastModifiedDateTime"},
    )
    change_key: Optional[str] = field(
        default=None,
        metadata={"wire_name": "changeKey"},
    )
    """Identifies the version of the post."""


# Client Class

class Office365groupsmailClient(ConnectorClientBase):
    """Typed client for office365groupsmail connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a Office365groupsmailClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "office365groupsmail"

    async def list_conversations_async(
        self,
        group_id: str,
    ) -> dict[str, Any] | None:
        """
        List the conversations of a group

        Get all the conversations in this group.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0/groups/{quote(str(group_id), safe='')}/conversations"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_conversation_async(
        self,
        input: CreateConversationBody,
        group_id: str,
    ) -> dict[str, Any] | None:
        """
        Create a new conversation in a group

        Create a new conversation in this group.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0/groups/{quote(str(group_id), safe='')}/conversations"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_group_conversation_async(
        self,
        group_id: str,
        conversation_id: str,
    ) -> dict[str, Any] | None:
        """
        Get a group conversation

        Retrieves the properties of a particular conversation.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/conversations"
            f"/{quote(str(conversation_id), safe='')}"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_conversation_threads_async(
        self,
        group_id: str,
        conversation_id: str,
    ) -> dict[str, Any] | None:
        """
        List the conversation threads of a conversation

        Get all the threads in a group conversation.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/conversations"
            f"/{quote(str(conversation_id), safe='')}"
            f"/threads"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_conversation_thread_async(
        self,
        input: CreateConversationBody,
        group_id: str,
        conversation_id: str,
    ) -> dict[str, Any] | None:
        """
        Create a conversation thread

        Create a new thread in the specified conversation.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/conversations"
            f"/{quote(str(conversation_id), safe='')}"
            f"/threads"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_group_threads_async(
        self,
        group_id: str,
    ) -> dict[str, Any] | None:
        """
        List the threads of a group

        Get all the threads of a group.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0/groups/{quote(str(group_id), safe='')}/threads"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_group_thread_async(
        self,
        input: CreateConversationBody,
        group_id: str,
    ) -> dict[str, Any] | None:
        """
        Start a new group conversation by creating a thread

        Start a new group conversation by first creating a thread.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0/groups/{quote(str(group_id), safe='')}/threads"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_conversation_thread_async(
        self,
        group_id: str,
        thread_id: str,
    ) -> dict[str, Any] | None:
        """
        Get a conversation thread

        Get a specific thread that belongs to a group.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/threads"
            f"/{quote(str(thread_id), safe='')}"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def delete_conversation_thread_async(
        self,
        group_id: str,
        thread_id: str,
    ) -> None:
        """
        Delete a conversation thread

        Deletes the specified conversation thread.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/threads"
            f"/{quote(str(thread_id), safe='')}"
        )

        response = await self.http_client.send_async(
            "DELETE", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "DELETE",
                request_url,
                response.status,
                response.text,
            )

    async def list_thread_posts_async(
        self,
        group_id: str,
        thread_id: str,
    ) -> dict[str, Any] | None:
        """
        List the posts of a conversation thread

        Get all the posts of the specified conversation thread.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/threads"
            f"/{quote(str(thread_id), safe='')}"
            f"/posts"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_thread_async(
        self,
        group_id: str,
        thread_id: str,
        post_id: str,
    ) -> dict[str, Any] | None:
        """
        Get a thread post

        Retrieves a post in a specified thread.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/threads"
            f"/{quote(str(thread_id), safe='')}"
            f"/posts"
            f"/{quote(str(post_id), safe='')}"
        )
        query_params = []
        query_params.append("$expand=" + quote("attachments"))
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_attachments_async(
        self,
        group_id: str,
        thread_id: str,
        post_id: str,
    ) -> dict[str, Any] | None:
        """
        List the attachments of a post

        Retrieve a list of attachments that belong to a post.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/threads"
            f"/{quote(str(thread_id), safe='')}"
            f"/posts"
            f"/{quote(str(post_id), safe='')}"
            f"/attachments"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def reply_to_a_thread_async(
        self,
        input: ReplyConversationThreadBody,
        group_id: str,
        thread_id: str,
    ) -> None:
        """
        Reply to a conversation thread

        Reply to a thread in a group conversation and add a new post to it.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/threads"
            f"/{quote(str(thread_id), safe='')}"
            f"/reply"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

    async def reply_async(
        self,
        input: ReplyConversationThreadBody,
        group_id: str,
        thread_id: str,
        post_id: str,
    ) -> None:
        """
        Reply to a post

        Reply to a post and add a new post to the specified thread in a group
        conversation.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0"
            f"/groups"
            f"/{quote(str(group_id), safe='')}"
            f"/threads"
            f"/{quote(str(thread_id), safe='')}"
            f"/posts"
            f"/{quote(str(post_id), safe='')}"
            f"/reply"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

    async def http_request_async(
        self,
        input: bytes,
    ) -> dict[str, Any] | None:
        """
        Send an HTTP request

        Construct a Microsoft Graph REST API request to invoke. Learn more:
        https://docs.microsoft.com/en-us/graph/use-the-api
        """
        request_url = f"{self._connection_runtime_url}/httprequest"

        response = await self.http_client.send_async(
            "POST",
            request_url,
            body=input,
            content_type="application/octet-stream",
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def forward_async(
        self,
        input: ForwardPostBody,
        group_mail: str,
        conversation_id: str,
        thread_id: str,
        post_id: str,
    ) -> None:
        """
        Forward a post

        Forward a post to a recipient.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/beta"
            f"/groups"
            f"/{quote(str(group_mail), safe='')}"
            f"/conversations"
            f"/{quote(str(conversation_id), safe='')}"
            f"/threads"
            f"/{quote(str(thread_id), safe='')}"
            f"/posts"
            f"/{quote(str(post_id), safe='')}"
            f"/forward"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

    async def list_groups_async(
        self,
    ) -> dict[str, Any] | None:
        """
        List user groups

        Retrieves all Office 365 Groups the user is part of.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1.0/me/memberOf/$/microsoft.graph.group"
        )
        query_params = []
        query_params.append("$filter=" + quote("groupTypes/any(c:c eq 'Unified')"))
        query_params.append("$select=" + quote("id,displayName"))
        query_params.append("$top=" + quote("999"))
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)


# Trigger Operations
#
# Trigger routes are not callable client methods. Register a trigger with the
# Connector Namespace trigger-config API using the operation id and required
# parameters below; Connector Namespace invokes the callback when the trigger
# fires. When the callback body has a JSON schema, ``callback_payload_type``
# names the generated dataclass to deserialize the callback payload into.
TRIGGER_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "OnNewEmailInGroup": {
        "operation_id": "OnNewEmailInGroup",
        "path": "/{connectionId}/trigger/v1.0/groups/{groupId}/conversations",
        "method": "get",
        "required_parameters": ["groupId"],
        "callback_payload_type": "OnNewEmailInGroupResponse",
    },
}
