# Copyright (c) Microsoft Corporation. All rights reserved.

# PlivoClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Dict, List, Any, Mapping
from urllib.parse import quote
import json

from azure.core.credentials import AzureKeyCredential
from azure.core.credentials_async import AsyncTokenCredential
from azure.core.pipeline.transport import AsyncHttpTransport

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorException,
    ConnectorResponseHook,
)


# Type Definitions

@dataclass
class MakeCallResponse:
    """
    Response for Make a call
    """

    api_id: Optional[str] = None
    """Unique ID of the API request."""
    message: Optional[str] = None
    """Response obtained when the call was made."""
    request_uuid: Optional[str] = None
    """Unique ID of the call."""


@dataclass
class ListMessagesResponse:
    """
    Response for List all messages
    """

    api_id: Optional[str] = None
    """Unique ID of the API request."""
    meta: Optional[Dict[str, Any]] = None
    """Meta information about the response."""
    objects: Optional[List[Dict[str, Any]]] = None
    """Details of all messages."""


@dataclass
class SendSMSResponse:
    """
    Response for Send SMS
    """

    api_id: Optional[str] = None
    """Unique ID of the API request."""
    message: Optional[str] = None
    """Response of the sent message."""
    message_uuid: Optional[List[str]] = None
    """Unique ID of the message."""


@dataclass
class GetMessageResponse:
    """
    Response for Get message
    """

    api_id: Optional[str] = None
    """Unique ID of the API request."""
    error_code: Optional[str] = None
    """Delivery error code if the message isn't delivered."""
    from_number: Optional[str] = None
    """Number from which the message was sent."""
    message_direction: Optional[str] = None
    """Direction of the message (inbound/outbound)."""
    message_state: Optional[str] = None
    """Status of the message (queued/sent/delivered/failed)."""
    message_time: Optional[str] = None
    """
    Timestamp at which the message was sent or received (yyyy-MM-dd HH:mm:ss
    UTC).
    """
    message_type: Optional[str] = None
    """Type of the message."""
    message_uuid: Optional[str] = None
    """Unique ID of the message."""
    resource_uri: Optional[str] = None
    """URI to get details of this single message."""
    to_number: Optional[str] = None
    """Number to which the message was sent."""
    total_amount: Optional[str] = None
    """Amount charged for the message."""
    total_rate: Optional[str] = None
    """Rate per unit of the message."""
    units: Optional[int] = None
    """Number of units the message was split into."""


@dataclass
class SMS:
    """
    Definition: SMS
    """

    src: Optional[str] = None
    """Plivo number from which the message is to be sent."""
    dst: Optional[str] = None
    """Phone number to which the message is to be sent."""
    text: Optional[str] = None
    """Text of the message to be sent."""


@dataclass
class Call:
    """
    Definition: Call
    """

    from_: Optional[str] = field(default=None, metadata={"wire_name": "from"})
    """Plivo number to be used to make the call."""
    to: Optional[str] = None
    """The phone number to call."""
    answer_url: Optional[str] = None
    """URL to be called when the call is made."""
    answer_method: Optional[str] = None
    """HTTP Method (GET/POST) that should be used to call the Answer URL."""


# Client Class

class PlivoClient(ConnectorClientBase):
    """Typed client for plivo connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        credential: AsyncTokenCredential | AzureKeyCredential,
        *,
        max_retry_attempts: int = 3,
        timeout_seconds: float = 30.0,
        use_exponential_backoff: bool = True,
        initial_retry_delay_seconds: float = 0.5,
        maximum_retry_delay_seconds: float = 120.0,
        retry_jitter_factor: float = 0.1,
        retry_unsafe_http_methods: bool = False,
        transport: Optional[AsyncHttpTransport] = None,
        **kwargs: Any,
    ):
        """
        Initialize a PlivoClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            credential: Caller-owned Azure Core credential.
            max_retry_attempts: The maximum number of request attempts.
            timeout_seconds: The total network timeout for each request,
                including retries, response loading, and body reads.
                Nonpositive values disable SDK and transport deadlines.
            use_exponential_backoff: Whether retries use exponential backoff.
            initial_retry_delay_seconds: The initial retry delay in seconds.
            maximum_retry_delay_seconds: The maximum retry delay in seconds.
            retry_jitter_factor: The jitter fraction applied to retry delays.
            retry_unsafe_http_methods: Whether unsafe HTTP methods may be
                retried.
            transport: Optional Azure Core async HTTP transport.
            **kwargs: Optional Azure Core pipeline policy settings.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if credential is None:
            raise ValueError("credential cannot be None")

        super().__init__(
            credential,
            max_retry_attempts=max_retry_attempts,
            timeout_seconds=timeout_seconds,
            use_exponential_backoff=use_exponential_backoff,
            initial_retry_delay_seconds=initial_retry_delay_seconds,
            maximum_retry_delay_seconds=maximum_retry_delay_seconds,
            retry_jitter_factor=retry_jitter_factor,
            retry_unsafe_http_methods=retry_unsafe_http_methods,
            transport=transport,
            **kwargs,
        )
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "plivo"

    async def make_call_async(
        self,
        input: Call,
        auth_id: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Make a call

        This operation is used to make a call.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1/Account/{quote(str(auth_id), safe='')}/Call/"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_messages_async(
        self,
        auth_id: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        List all messages

        This operation returns a list of all messages associated with your
        Plivo account.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1/Account/{quote(str(auth_id), safe='')}/Message/"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def send_sms_async(
        self,
        input: SMS,
        auth_id: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Send SMS

        This operation is used to send a text message.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1/Account/{quote(str(auth_id), safe='')}/Message/"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_message_async(
        self,
        auth_id: str,
        message_uuid: str,
        *,
        timeout: Optional[float] = None,
        headers: Optional[Mapping[str, str]] = None,
        client_request_id: Optional[str] = None,
        response_hook: Optional[ConnectorResponseHook] = None,
    ) -> dict[str, Any] | None:
        """
        Get message

        This operation is used to fetch the details of a message, given the
        message ID.
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1"
            f"/Account"
            f"/{quote(str(auth_id), safe='')}"
            f"/Message"
            f"/{quote(str(message_uuid), safe='')}"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None,
            timeout=timeout,
            headers=headers,
            client_request_id=client_request_id,
            response_hook=response_hook,
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)
