# Copyright (c) Microsoft Corporation. All rights reserved.

# ProjectplaceClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Any, Dict
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class SetWebhookCardCreateInput:
    """
    When a card is created
    """

    card_create: Optional[bool] = None
    """Triggers when a card is created on the defined board"""
    webhook: Optional[str] = None
    """webhook"""
    board_id: Optional[int] = None
    """The id of the Board that the card belongs to"""


@dataclass
class SetWebhookPropertiesChangeInput:
    """
    When a card's properties are changed
    """

    card_blocked: Optional[bool] = None
    """Triggers when a card is blocked"""
    card_unblock: Optional[bool] = None
    """Triggers when a card block is removed"""
    status_change: Optional[bool] = None
    """Triggers when a card is moved to another column on the"""
    card_done: Optional[bool] = None
    """
    Triggers when a card is set to done by moving it to the rightmost column on
    the board
    """
    description_changed: Optional[bool] = None
    """Triggers when the description of a card changes"""
    due_date_changed: Optional[bool] = None
    """Triggers when the due date of a card changes"""
    webhook: Optional[str] = None
    """webhook"""
    board_id: Optional[int] = None
    """The id of the Board that the card belongs to"""


@dataclass
class SetWebhookCardDueDateInput:
    """
    When a card is due
    """

    due_today: Optional[bool] = None
    """Triggers on the date that the card is due"""
    webhook: Optional[str] = None
    """webhook"""
    board_id: Optional[int] = None
    """The id of the Board that the card belongs to"""


@dataclass
class CreateCardInput:
    """
    Create Card
    """

    column_id: Optional[int] = None
    """The column where the card should be created"""
    title: Optional[str] = None
    """The title of the created card"""
    description: Optional[str] = None
    """The description of the created card"""
    assignee_email: Optional[str] = None
    """The person that will be assigned to the created card"""
    planlet_id: Optional[int] = None
    """The activity the Card should be associated with"""
    due_date: Optional[str] = None
    """The due date of the created card"""
    label_id: Optional[int] = None
    """The label of the created card"""


@dataclass
class CreateCardResponse:
    """
    Response for Create Card
    """

    access: Optional[str] = None
    """Access rights"""
    assignee: Optional[Dict[str, Any]] = None
    """The person who is assigned to the card"""
    assignee_id: Optional[int] = None
    """The id of the person who is assigned the card"""
    board_id: Optional[int] = None
    """The ID of the board"""
    board_name: Optional[str] = None
    """The name of the board"""
    direct_url: Optional[str] = None
    """The card's direct URL"""
    due_date: Optional[str] = None
    """The due date of the card"""
    estimated_time: Optional[str] = None
    """Estimated time for completion"""
    id: Optional[int] = None
    """The ID of the card"""
    is_blocked: Optional[bool] = None
    """Is the card is"""
    is_blocked_reason: Optional[str] = None
    """The blocking reason - if blocked"""
    is_done: Optional[bool] = None
    """Is the card done"""
    is_template: Optional[bool] = None
    """Is a template card"""
    label_id: Optional[int] = None
    """The id of the label"""
    planlet_id: Optional[int] = None
    """The id of the activity"""
    reported_time: Optional[str] = None
    """How much time was reported for the card"""
    title: Optional[str] = None
    """The card's title"""


@dataclass
class MoveCardInput:
    """
    Move card to another column
    """

    card_id: Optional[int] = None
    """The card to be moved"""
    card_title: Optional[str] = None
    """The title of the card to be moved"""
    column_id: Optional[int] = None
    """The column where the card should be moved to"""


@dataclass
class MoveCardResponse:
    """
    Response for Move card to another column
    """

    access: Optional[str] = None
    """Access rights"""
    assignee_id: Optional[int] = None
    """The ID of the person the card assigned to"""
    board_id: Optional[int] = None
    """The ID of the board"""
    board_name: Optional[str] = None
    """The name of the board"""
    column_id: Optional[int] = None
    """The id of the column the card is on"""
    column_name: Optional[str] = None
    """The name of the column"""
    description: Optional[str] = None
    """The description on the card"""
    direct_url: Optional[str] = None
    """The direct URL of the card"""
    due_date: Optional[str] = None
    """The due date of the card"""
    estimated_time: Optional[str] = None
    """The estimated time of the card"""
    id: Optional[int] = None
    """The id of the card"""
    is_blocked: Optional[bool] = None
    """Is the card blocked"""
    is_blocked_reason: Optional[str] = None
    """The reason the card is blocked"""
    is_done: Optional[bool] = None
    """Is the card done"""
    is_template: Optional[bool] = None
    """Is a template card"""
    label_id: Optional[int] = None
    """The id of the card's label"""
    label_name: Optional[str] = None
    """The name of the label"""
    planlet_id: Optional[int] = None
    """The id of the activity"""
    reported_time: Optional[str] = None
    """The time reported for this card"""
    title: Optional[str] = None
    """The title of the card"""


# Client Class

class ProjectplaceClient(ConnectorClientBase):
    """Typed client for projectplace connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a ProjectplaceClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "projectplace"

    async def create_card_async(
        self,
        input: CreateCardInput,
        board_id: str,
    ) -> dict[str, Any] | None:
        """
        Create Card

        Creates a new card with the parameters provided
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1"
            f"/external_notifications"
            f"/{quote(str(board_id), safe='')}"
            f"/create_card"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def move_card_async(
        self,
        input: MoveCardInput,
        board_id: str,
    ) -> dict[str, Any] | None:
        """
        Move card to another column

        Move a card on the selected board
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1"
            f"/external_notifications"
            f"/{quote(str(board_id), safe='')}"
            f"/move_card"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def list_boards_async(
        self,
    ) -> dict[str, Any] | None:
        """
        Lists the boards the user have access to

        Lists the boards that are part of the projects the user have access to
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/v1/external_notifications/lists/list_boards"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)


# Trigger Operations
#
# Trigger routes are not callable client methods. Register a trigger with the
# Connector Namespace trigger-config API using the operation id and required
# parameters below; Connector Namespace invokes the callback when the trigger
# fires. When the callback body has a JSON schema, ``callback_payload_type``
# names the generated dataclass to deserialize the callback payload into.
TRIGGER_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "set_webhook_card_create": {
        "operation_id": "set_webhook_card_create",
        "path": "/{connectionId}/v1/external_notifications/0/hooks/set_power_hook",
        "method": "post",
        "required_parameters": [],
        "callback_payload_type": None,
    },
    "set_webhook_properties_change": {
        "operation_id": "set_webhook_properties_change",
        "path": "/{connectionId}/v1/external_notifications/1/hooks/set_power_hook",
        "method": "post",
        "required_parameters": [],
        "callback_payload_type": None,
    },
    "set_webhook_card_due_date": {
        "operation_id": "set_webhook_card_due_date",
        "path": "/{connectionId}/v1/external_notifications/2/hooks/set_power_hook",
        "method": "post",
        "required_parameters": [],
        "callback_payload_type": None,
    },
}
