# Copyright (c) Microsoft Corporation. All rights reserved.

# TallyfyClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict, List
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class GetUserTasksResponse:
    """
    Response for Get a member's tasks
    """

    data: Optional[List[Dict[str, Any]]] = None
    """data"""
    meta: Optional[Dict[str, Any]] = None
    """meta"""


@dataclass
class InviteUserToOrganizationInput:
    """
    Invite a new member to your organization
    """

    first_name: Optional[str] = None
    """Invitee's first name"""
    last_name: Optional[str] = None
    """invitee's last name"""
    email: Optional[str] = None
    """invitee's work email address"""
    message: Optional[str] = None
    """Message to add"""
    role: Optional[str] = None
    """Role"""


@dataclass
class InviteUserToOrganizationResponse:
    """
    Response for Invite a new member to your organization
    """

    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class CreateRunInput:
    """
    Launch a Process
    """

    name: Optional[str] = None
    """Name to give the new Process"""
    checklist_id: Optional[str] = None
    """ID of the Blueprint to start the process"""
    summary: Optional[str] = None
    """Summary notes to include with the Process"""


@dataclass
class CreateRunResponse:
    """
    Response for Launch a Process
    """

    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class CompletedOneOffTaskInput:
    """
    Complete One Off Task
    """

    task_id: Optional[str] = None
    """Task ID"""
    is_approved: Optional[bool] = None
    """starred"""


@dataclass
class CompletedOneOffTaskResponse:
    """
    Response for Complete One Off Task
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ReopenOneOffTaskResponse:
    """
    Response for Reopen One Off Task
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class CompletedProcessTaskInput:
    """
    Complete process task
    """

    task_id: Optional[str] = None
    """Task ID"""
    is_approved: Optional[bool] = None
    """starred"""


@dataclass
class CompletedProcessTaskResponse:
    """
    Response for Complete process task
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ReopenProcessTaskResponse:
    """
    Response for Reopen process Task
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class CommentTaskInput:
    """
    Add comment, report issue, resolve issue on a task
    """

    content: Optional[str] = None
    """Comment content"""
    label: Optional[str] = None
    """Comment label"""


@dataclass
class CommentTaskResponse:
    """
    Response for Add comment, report issue, resolve issue on a task
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class CreateTaskInput:
    """
    Create a task
    """

    owners: Optional[Dict[str, Any]] = None
    """owners"""
    task_type: Optional[str] = None
    """Task type"""
    deadline: Optional[str] = None
    """task deadline, in date-time format"""
    description: Optional[str] = None
    """Task's description"""
    name: Optional[str] = None
    """task name"""


@dataclass
class CreateTaskResponse:
    """
    Response for Create a task
    """

    data: Optional[Dict[str, Any]] = None
    """data"""


@dataclass
class EditTaskDeadlineInput:
    """
    Edit task deadline
    """

    deadline: Optional[str] = field(
        default=None,
        metadata={"wire_name": "Deadline"},
    )
    """New task deadline"""


@dataclass
class EditTaskDeadlineResponse:
    """
    Response for Edit task deadline
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class RemoveGuestResponse:
    """
    Response for Remove guest assigned
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class RemoveAssigneeResponse:
    """
    Response for Remove assignee
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class EditStepTypeInput:
    """
    Edit step type
    """

    step_type: Optional[str] = field(
        default=None,
        metadata={"wire_name": "stepType"},
    )
    """New step type"""


@dataclass
class EditStepTypeResponse:
    """
    Response for Edit step type
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class GetUserOrganizationsResponse:
    """
    Response for Get user's organizations
    """

    data: Optional[List[Dict[str, Any]]] = None
    """data"""
    meta: Optional[Dict[str, Any]] = None
    """meta"""


@dataclass
class GetOrganizationUsersResponse:
    """
    Response for Get organization's users
    """

    data: Optional[List[Dict[str, Any]]] = None
    """data"""


@dataclass
class Error:
    """
    Definition: error
    """

    error: Optional[bool] = None
    message: Optional[str] = None


Date = str


RequestDate = str


@dataclass
class Address:
    """
    Definition: Address
    """

    address1: Optional[str] = None
    address2: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zip: Optional[str] = None
    country: Optional[str] = None
    phone: Optional[str] = None


@dataclass
class LoginInput:
    """
    Definition: loginInput
    """

    email: Optional[str] = None
    password: Optional[str] = None


@dataclass
class File:
    """
    Definition: File
    """

    name: Optional[str] = None
    url: Optional[str] = None
    extension: Optional[str] = None
    size: Optional[int] = None
    last_modified: Optional[str] = None


@dataclass
class RegisterInput:
    """
    Definition: registerInput
    """

    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None
    password: Optional[str] = None
    company_name: Optional[str] = None
    timezone: Optional[str] = None
    plan_code: Optional[str] = None
    coupon_code: Optional[str] = None


@dataclass
class ResetPasswordInput:
    """
    Definition: resetPasswordInput
    """

    password: Optional[str] = None
    password_confirmation: Optional[str] = None
    code: Optional[str] = None


@dataclass
class OrganizationInput:
    """
    Definition: organizationInput
    """

    name: Optional[str] = None
    address1: Optional[str] = None
    address2: Optional[str] = None
    address3: Optional[str] = None
    slug: Optional[str] = None
    welcome_title: Optional[str] = None
    welcome_description: Optional[str] = None
    industry: Optional[str] = None
    country: Optional[str] = None
    state: Optional[str] = None
    city: Optional[str] = None
    zipcode: Optional[str] = None
    settings: Optional[OrganizationSettings] = None


@dataclass
class OrganizationSettings:
    """
    Definition: organizationSettings
    """

    determine_deadline: Optional[GenericObject] = None
    workdays: Optional[List[str]] = None
    holidays: Optional[List[str]] = None


@dataclass
class BillInput:
    """
    Definition: billInput
    """

    token_id: Optional[str] = None


@dataclass
class SubcriptionInput:
    """
    Definition: subcriptionInput
    """

    plan_code: Optional[str] = None
    coupon_code: Optional[str] = None


@dataclass
class AccountInput:
    """
    Definition: accountInput
    """

    email: Optional[str] = None
    cc_emails: Optional[str] = None
    address: Optional[Address] = None


@dataclass
class RunView:
    """
    Definition: RunView
    """

    name: Optional[str] = None
    is_active: Optional[int] = None
    filter_type: Optional[str] = None
    criteria: Optional[List[str]] = None


@dataclass
class RunViewInput:
    """
    Definition: runViewInput
    """

    name: Optional[str] = None
    filter_type: Optional[str] = None
    is_active: Optional[int] = None
    criteria: Optional[List[Dict[str, Any]]] = None


@dataclass
class PreferenceInput:
    """
    Definition: preferenceInput
    """

    slug: Optional[str] = None
    value: Optional[str] = None
    metadata: Optional[GenericObject] = None


@dataclass
class AccountsInput:
    """
    Definition: accountsInput
    """

    email: Optional[str] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    username: Optional[str] = None
    phone: Optional[str] = None
    job_title: Optional[str] = None
    job_description: Optional[str] = None
    timezone: Optional[str] = None
    country_id: Optional[int] = None


@dataclass
class InviteInput:
    """
    Definition: inviteInput
    """

    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None


@dataclass
class Passwordreset:
    """
    Definition: passwordreset
    """

    new_password: Optional[str] = None


@dataclass
class Passwordreseterro:
    """
    Definition: passwordreseterro
    """

    error: Optional[bool] = None
    message: Optional[str] = None
    code: Optional[str] = None


@dataclass
class CheckUrlInput:
    """
    Definition: checkUrlInput
    """

    url: Optional[str] = None


@dataclass
class AssetSubject:
    """
    Definition: AssetSubject
    """

    id: Optional[int] = None
    type_: Optional[str] = field(default=None, metadata={"wire_name": "type"})


@dataclass
class Asset:
    """
    Definition: Asset
    """

    id: Optional[str] = None
    filename: Optional[str] = None
    version: Optional[int] = None
    step_id: Optional[str] = None
    uploaded_from: Optional[str] = None
    subject: Optional[AssetSubject] = None


@dataclass
class CaptureInput:
    """
    Definition: CaptureInput
    """

    alias: Optional[str] = None
    field_type: Optional[str] = None
    guidance: Optional[str] = None
    label: Optional[str] = None
    position: Optional[int] = None
    required: Optional[bool] = None
    options: Optional[List[GenericObject]] = None


@dataclass
class Capture:
    """
    Definition: Capture
    """

    id: Optional[int] = None
    step_id: Optional[int] = None
    alias: Optional[str] = None
    field_type: Optional[str] = None
    guidance: Optional[str] = None
    label: Optional[str] = None
    position: Optional[int] = None
    required: Optional[bool] = None
    options: Optional[str] = None
    created_at: Optional[RequestDate] = None
    last_updated: Optional[RequestDate] = None
    archived_at: Optional[RequestDate] = None


@dataclass
class BrandingInput:
    """
    Definition: brandingInput
    """

    bg_color: Optional[str] = None
    text_color: Optional[str] = None
    alternate_color: Optional[str] = None
    bright_shade: Optional[str] = None
    dark_shade: Optional[str] = None


@dataclass
class Branding:
    """
    Definition: Branding
    """

    bg_color: Optional[str] = None
    text_color: Optional[str] = None
    alternate_color: Optional[str] = None
    bright_shade: Optional[str] = None
    dark_shade: Optional[str] = None
    updated_at: Optional[Date] = None


@dataclass
class ChecklistInput:
    """
    Definition: checklistInput
    """

    checklist: Optional[Checklist] = None


@dataclass
class PowerbuilderInput:
    """
    Definition: powerbuilderInput
    """

    id: Optional[str] = None
    steps: Optional[str] = None


@dataclass
class CreateChecklistInput:
    """
    Definition: createChecklistInput
    """

    title: Optional[str] = None
    summary: Optional[str] = None
    privacy: Optional[str] = None
    settings: Optional[GenericObject] = None
    contributors: Optional[List[int]] = None
    """The list of users who can update the checklist."""
    tags: Optional[List[str]] = None
    start_run_permissions: Optional[GenericObject] = None
    """The list of groups and users who can access the run."""
    prerun: Optional[GenericObject] = None
    user_id: Optional[int] = None
    """Template creator ID"""
    owner_id: Optional[int] = None
    """Template Owner ID"""


@dataclass
class Checklist:
    """
    Definition: Checklist
    """

    id: Optional[str] = None
    title: Optional[str] = None
    summary: Optional[str] = None
    privacy: Optional[str] = None
    starred: Optional[int] = None
    settings: Optional[GenericObject] = None
    contributors: Optional[List[int]] = None
    """The list of users who can update the Blueprint."""
    statistics: Optional[GenericObject] = None
    created_by: Optional[int] = None
    owner_id: Optional[int] = None
    """Template Owner ID"""
    created_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    archived_at: Optional[Date] = None
    created_ago: Optional[str] = None
    steps: Optional[List[Step]] = None


@dataclass
class CommentOn:
    """
    Definition: comment_on
    """

    id: Optional[int] = None
    type_: Optional[str] = field(default=None, metadata={"wire_name": "type"})


@dataclass
class CreateCommentInput:
    """
    Definition: createCommentInput
    """

    comment_on: Optional[CommentOn] = None
    content: Optional[str] = None


@dataclass
class Comment:
    """
    Definition: Comment
    """

    id: Optional[int] = None
    comment_on: Optional[CommentOn] = None
    content: Optional[str] = None
    replies_count: Optional[int] = None
    author_id: Optional[int] = None
    metadata: Optional[str] = None
    archived_at: Optional[str] = None


@dataclass
class CreateGroupInput:
    """
    Definition: createGroupInput
    """

    name: Optional[str] = None
    users: Optional[List[int]] = None


@dataclass
class Group:
    """
    Definition: Group
    """

    id: Optional[int] = None
    name: Optional[str] = None
    created_at: Optional[Date] = None
    updated_at: Optional[Date] = None


@dataclass
class IntegrationS3Input:
    """
    Definition: integrationS3Input
    """

    aws_key: Optional[str] = None
    aws_secret: Optional[str] = None
    aws_region: Optional[str] = None
    aws_bucket: Optional[str] = None
    aws_account_id: Optional[str] = None


@dataclass
class Message:
    """
    Definition: Message
    """

    id: Optional[int] = None
    thread_id: Optional[str] = None
    label: Optional[str] = None
    thread_last_updated_at: Optional[str] = None
    updated_at: Optional[Date] = None
    content: Optional[str] = None
    sent_by: Optional[int] = None
    sent_at: Optional[Date] = None
    created_ago: Optional[str] = None
    sent_to: Optional[List[int]] = None
    author_name: Optional[str] = None
    author: Optional[GenericObject] = None
    subject: Optional[GenericObject] = None


@dataclass
class Organization:
    """
    Definition: Organization
    """

    id: Optional[int] = None
    name: Optional[str] = None
    address1: Optional[str] = None
    address2: Optional[str] = None
    address3: Optional[str] = None
    slug: Optional[str] = None
    welcome_title: Optional[str] = None
    welcome_description: Optional[str] = None
    created_on: Optional[Date] = None
    last_updated: Optional[Date] = None
    user_status: Optional[str] = None
    joined_on: Optional[Date] = None
    disabled_on: Optional[Date] = None
    last_accessed: Optional[Date] = None


@dataclass
class Preference:
    """
    Definition: Preference
    """

    slug: Optional[str] = None
    value: Optional[str] = None
    metadata: Optional[GenericObject] = None
    last_updated: Optional[Date] = None


@dataclass
class RunRatingsInput:
    """
    Definition: runRatingsInput
    """

    rating: Optional[float] = None
    comment: Optional[str] = None


@dataclass
class CreateRoleInput:
    """
    Definition: createRoleInput
    """

    name: Optional[str] = None
    permissions: Optional[List[str]] = None


@dataclass
class Role:
    """
    Definition: Role
    """

    id: Optional[int] = None
    name: Optional[str] = None
    permissions: Optional[GenericObject] = None
    created_at: Optional[Date] = None
    updated_at: Optional[Date] = None


@dataclass
class RunCollaborators:
    """
    Definition: runCollaborators
    """

    members: Optional[List[int]] = None
    guests: Optional[List[str]] = None


@dataclass
class OwnerInput:
    """
    Definition: ownerInput
    """

    owners: Optional[Any] = None


@dataclass
class DueDateInput:
    """
    Definition: dueDateInput
    """

    deadline: Optional[str] = None


@dataclass
class PrerunData:
    """
    Definition: PrerunData
    """

    id: Optional[str] = None
    alias: Optional[str] = None
    created_at: Optional[Date] = None
    field_type: Optional[str] = None
    field_value: Optional[str] = None
    label: Optional[str] = None
    updated_at: Optional[Date] = None
    options: Optional[str] = None
    position: Optional[int] = None
    required: Optional[bool] = None
    value: Optional[str] = None


@dataclass
class AlertIssues:
    """
    Definition: AlertIssues
    """

    id: Optional[str] = None
    task_id: Optional[str] = None
    label: Optional[str] = None
    content: Optional[str] = None
    sent_to: Optional[GenericObject] = None
    sent_by: Optional[int] = None
    created_at: Optional[Date] = None
    created_ago: Optional[str] = None
    recent_updated_at: Optional[Date] = None
    author: Optional[GenericObject] = None
    resolve_id: Optional[int] = None


@dataclass
class RunAlerts:
    """
    Definition: RunAlerts
    """

    issues: Optional[List[AlertIssues]] = None


@dataclass
class Run:
    """
    Definition: Run
    """

    id: Optional[str] = None
    checklist_id: Optional[str] = None
    name: Optional[str] = None
    summary: Optional[str] = None
    status: Optional[str] = None
    progress: Optional[GenericObject] = None
    started_by: Optional[int] = None
    owner_id: Optional[int] = None
    prerun: Optional[List[PrerunData]] = None
    alerts: Optional[RunAlerts] = None
    starred: Optional[bool] = None
    created_at: Optional[Date] = None
    started_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    last_synced: Optional[Date] = None
    completed_at: Optional[Date] = None
    archived_at: Optional[Date] = None
    due_date_passed: Optional[bool] = None
    collaborators: Optional[List[int]] = None
    due_soon: Optional[bool] = None
    max_task_deadline: Optional[Date] = None


@dataclass
class RunMetaInput:
    """
    Definition: runMetaInput
    """

    run_id: Optional[str] = None
    category: Optional[str] = None
    slug: Optional[str] = None
    value: Optional[str] = None


@dataclass
class Section:
    """
    Definition: Section
    """

    id: Optional[str] = None
    checklist_id: Optional[str] = None
    name: Optional[str] = None
    position: Optional[int] = None
    condition: Optional[GenericObject] = None


@dataclass
class SectionInput:
    """
    Definition: SectionInput
    """

    name: Optional[str] = None
    position: Optional[int] = None
    condition: Optional[StepCondition] = None


@dataclass
class SectionCreateInput:
    """
    Definition: SectionCreateInput
    """

    name: Optional[str] = None
    position: Optional[int] = None


@dataclass
class StandaloneTask:
    """
    Definition: StandaloneTask
    """

    id: Optional[str] = None
    title: Optional[str] = None
    run_id: Optional[str] = None
    step_id: Optional[str] = None
    alias: Optional[str] = None
    taskdata: Optional[GenericObject] = None
    owners: Optional[StepOwner] = None
    is_completable: Optional[int] = None
    status: Optional[str] = None
    position: Optional[int] = None
    deadline: Optional[Date] = None
    created_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    archived_at: Optional[Date] = None
    completed_at: Optional[Date] = None
    starter_id: Optional[int] = None
    completer_id: Optional[int] = None
    name: Optional[str] = None
    description: Optional[str] = None
    owner_id: Optional[int] = None
    task_type: Optional[str] = None
    is_accepted: Optional[int] = None


@dataclass
class CreateStandaloneTaskInput:
    """
    Definition: createStandaloneTaskInput
    """

    owners: Optional[StepOwner] = None
    task_type: Optional[str] = None
    deadline: Optional[RequestDate] = None
    description: Optional[str] = None
    name: Optional[str] = None


@dataclass
class UpdateStandaloneTaskInput:
    """
    Definition: updateStandaloneTaskInput
    """

    taskdata: Optional[GenericObject] = None
    owners: Optional[StepOwner] = None
    name: Optional[str] = None
    description: Optional[str] = None
    task_type: Optional[str] = None
    status: Optional[str] = None
    deadline: Optional[RequestDate] = None


@dataclass
class StepOwner:
    """
    Definition: stepOwner
    """

    users: Optional[List[int]] = None
    guests: Optional[List[str]] = None


@dataclass
class StepDeadline:
    """
    Definition: stepDeadline
    """

    value: Optional[int] = None
    unit: Optional[str] = None
    option: Optional[str] = None
    step: Optional[str] = None


@dataclass
class StepConditionTerm:
    """
    Definition: StepConditionTerm
    """

    subject_id: Optional[str] = None
    subject_type: Optional[str] = None
    operation: Optional[str] = None
    statement: Optional[str] = None
    logic: Optional[str] = None


@dataclass
class StepCondition:
    """
    Definition: StepCondition
    """

    terms: Optional[List[StepConditionTerm]] = None
    flag: Optional[str] = None


@dataclass
class CreateStepInput:
    """
    Definition: createStepInput
    """

    title: Optional[str] = None
    checklist_id: Optional[str] = None
    summary: Optional[str] = None
    rationale: Optional[str] = None
    position: Optional[int] = None
    owners: Optional[StepOwner] = None
    invisibility: Optional[GenericObject] = None
    """The list of groups the step is invisible to."""
    settings: Optional[GenericObject] = None
    metadata: Optional[GenericObject] = None
    condition: Optional[StepCondition] = None
    captures: Optional[List[CaptureInput]] = None


@dataclass
class Step:
    """
    Definition: Step
    """

    id: Optional[int] = None
    checklist_id: Optional[str] = None
    summary: Optional[str] = None
    title: Optional[str] = None
    rationale: Optional[str] = None
    position: Optional[int] = None
    owners: Optional[StepOwner] = None
    invisibility: Optional[GenericObject] = None
    """The list of groups the step is invisible to."""
    settings: Optional[GenericObject] = None
    metadata: Optional[GenericObject] = None
    deadline: Optional[StepDeadline] = None
    captures: Optional[GenericObject] = None
    condition: Optional[GenericObject] = None
    created_at: Optional[RequestDate] = None
    last_updated: Optional[RequestDate] = None
    archived_at: Optional[RequestDate] = None


@dataclass
class StepMeta:
    """
    Definition: StepMeta
    """

    step_id: Optional[str] = None
    category: Optional[str] = None
    slug: Optional[str] = None
    value: Optional[str] = None
    created_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    archived_at: Optional[Date] = None


@dataclass
class Tag:
    """
    Definition: Tag
    """

    id: Optional[str] = None
    title: Optional[str] = None
    items: Optional[int] = None
    created_at: Optional[Date] = None
    deleted_at: Optional[Date] = None


@dataclass
class CreateTagInput:
    """
    Definition: createTagInput
    """

    title: Optional[str] = None


@dataclass
class AddTagInput:
    """
    Definition: addTagInput
    """

    tag_id: Optional[str] = None
    subject_id: Optional[str] = None
    subject_type: Optional[str] = None


@dataclass
class TaskObject:
    """
    Definition: Task
    """

    id: Optional[str] = None
    title: Optional[str] = None
    run_id: Optional[str] = None
    step_id: Optional[str] = None
    alias: Optional[str] = None
    taskdata: Optional[GenericObject] = None
    owners: Optional[StepOwner] = None
    is_completable: Optional[bool] = None
    status: Optional[str] = None
    position: Optional[int] = None
    deadline: Optional[Date] = None
    created_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    archived_at: Optional[Date] = None
    completed_at: Optional[Date] = None
    starter_id: Optional[int] = None
    completer_id: Optional[int] = None
    run_status: Optional[str] = None


@dataclass
class Pagination:
    """
    Definition: Pagination
    """

    total: Optional[int] = None
    count: Optional[int] = None
    per_page: Optional[int] = None
    current_page: Optional[int] = None
    total_pages: Optional[int] = None
    links: Optional[GenericObject] = None


@dataclass
class TasksListMeta:
    """
    Definition: TasksListMeta
    """

    overdue_tasks: Optional[int] = None
    tasks_due_soon: Optional[int] = None
    pagination: Optional[Pagination] = None


@dataclass
class TasksList:
    """
    Definition: TasksList
    """

    data: Optional[List[TaskObject]] = None
    meta: Optional[TasksListMeta] = None


@dataclass
class CompletedProcessTask:
    """
    Definition: CompletedProcessTask
    """

    id: Optional[str] = None
    title: Optional[str] = None
    run_id: Optional[str] = None
    step_id: Optional[str] = None
    alias: Optional[str] = None
    taskdata: Optional[GenericObject] = None
    owners: Optional[StepOwner] = None
    is_completable: Optional[bool] = None
    status: Optional[str] = None
    position: Optional[int] = None
    deadline: Optional[Date] = None
    created_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    archived_at: Optional[Date] = None
    completed_at: Optional[Date] = None
    starter_id: Optional[int] = None
    completer_id: Optional[int] = None
    run_status: Optional[str] = None
    tasks_changed_by_rules: Optional[GenericObject] = None


@dataclass
class UpdateTaskInput:
    """
    Definition: updateTaskInput
    """

    taskdata: Optional[GenericObject] = None
    threads: Optional[Dict[str, Any]] = None
    owners: Optional[StepOwner] = None
    status: Optional[str] = None
    position: Optional[int] = None
    deadline: Optional[Date] = None


@dataclass
class TaskGuest:
    """
    Definition: TaskGuest
    """

    alias: Optional[str] = None
    organization: Optional[GenericObject] = None
    taskdata: Optional[GenericObject] = None
    threads: Optional[GenericObject] = None
    status: Optional[str] = None
    is_completable: Optional[bool] = None
    deadline: Optional[Date] = None
    created_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    completed_at: Optional[Date] = None
    step: Optional[Step] = None
    step_id: Optional[int] = None
    guest_email: Optional[str] = None


@dataclass
class UpdateGuestsTasksInput:
    """
    Definition: updateGuestsTasksInput
    """

    taskdata: Optional[GenericObject] = None
    status: Optional[str] = None


@dataclass
class CreateGuestsTasksComment:
    """
    Definition: createGuestsTasksComment
    """

    content: Optional[str] = None


@dataclass
class TaskMetaInput:
    """
    Definition: TaskMetaInput
    """

    slug: Optional[str] = None
    value: Optional[GenericObject] = None


@dataclass
class TaskMeta:
    """
    Definition: TaskMeta
    """

    task_id: Optional[str] = None
    slug: Optional[str] = None
    value: Optional[str] = None
    created_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    archived_at: Optional[Date] = None


@dataclass
class ThreadInput:
    """
    Definition: threadInput
    """

    content: Optional[str] = None


@dataclass
class ThreadResolveInput:
    """
    Definition: threadResolveInput
    """

    thread_id: Optional[str] = None
    content: Optional[str] = None


@dataclass
class Thread:
    """
    Definition: Thread
    """

    id: Optional[int] = None
    label: Optional[str] = None
    sent_by: Optional[int] = None
    content: Optional[str] = None
    created_at: Optional[Date] = None
    sent_to: Optional[List[int]] = None
    last_updated_at: Optional[Date] = None
    archived_at: Optional[Date] = None


@dataclass
class User:
    """
    Definition: User
    """

    id: Optional[int] = None
    email: Optional[str] = None
    username: Optional[str] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    full_name: Optional[str] = None
    phone: Optional[str] = None
    job_title: Optional[str] = None
    job_description: Optional[str] = None
    profile_pic: Optional[str] = None
    locale: Optional[str] = None
    active: Optional[bool] = None
    is_suspended: Optional[bool] = None
    country: Optional[str] = None
    created_at: Optional[Date] = None
    last_updated: Optional[Date] = None
    last_login_at: Optional[Date] = None


@dataclass
class AccessToken:
    """
    Definition: AccessToken
    """

    access_token: Optional[str] = None
    token_type: Optional[str] = None
    expire: Optional[int] = None
    expires_in: Optional[int] = None


@dataclass
class GenericObject:
    """
    Definition: GenericObject
    """

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class Client:
    """
    Definition: Client
    """

    name: Optional[str] = None
    redirect: Optional[str] = None


# Client Class

class TallyfyClient(ConnectorClientBase):
    """Typed client for tallyfy connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a TallyfyClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "tallyfy"

    async def get_user_tasks_async(
        self,
        org: str,
        user_id: str,
        q: Optional[str] = None,
        status: Optional[str] = None,
        sort: Optional[str] = None,
        tag: Optional[str] = None,
        page: Optional[str] = None,
        per_page: Optional[str] = None,
    ) -> dict[str, Any] | None:
        """
        Get a member's tasks

        Get all tasks that belong to a specific member
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/users"
            f"/{quote(str(user_id), safe='')}"
            f"/tasks"
        )
        query_params = []
        if q is not None:
            value = str(q)
            if isinstance(q, bool):
                value = value.lower()
            query_params.append(f"q={quote(value)}")
        if status is not None:
            value = str(status)
            if isinstance(status, bool):
                value = value.lower()
            query_params.append(f"status={quote(value)}")
        if sort is not None:
            value = str(sort)
            if isinstance(sort, bool):
                value = value.lower()
            query_params.append(f"sort={quote(value)}")
        if tag is not None:
            value = str(tag)
            if isinstance(tag, bool):
                value = value.lower()
            query_params.append(f"tag={quote(value)}")
        if page is not None:
            value = str(page)
            if isinstance(page, bool):
                value = value.lower()
            query_params.append(f"page={quote(value)}")
        if per_page is not None:
            value = str(per_page)
            if isinstance(per_page, bool):
                value = value.lower()
            query_params.append(f"per_page={quote(value)}")
        if query_params:
            request_url += '?' + '&'.join(query_params)

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def invite_user_to_organization_async(
        self,
        input: InviteUserToOrganizationInput,
        org: str,
    ) -> dict[str, Any] | None:
        """
        Invite a new member to your organization

        Invite a new member to your organization
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations/{quote(str(org), safe='')}/users/invite"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_run_async(
        self,
        input: CreateRunInput,
        org: str,
    ) -> dict[str, Any] | None:
        """
        Launch a Process

        Launch a process using a blueprint
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations/{quote(str(org), safe='')}/runs"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def completed_one_off_task_async(
        self,
        input: CompletedOneOffTaskInput,
        org: str,
    ) -> dict[str, Any] | None:
        """
        Complete One Off Task

        Complete one off task
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations/{quote(str(org), safe='')}/completed-tasks"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def reopen_one_off_task_async(
        self,
        org: str,
        task: str,
    ) -> dict[str, Any] | None:
        """
        Reopen One Off Task

        Reopen one off task
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/completed-tasks"
            f"/{quote(str(task), safe='')}"
        )

        response = await self.http_client.send_async(
            "DELETE", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "DELETE",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def completed_process_task_async(
        self,
        input: CompletedProcessTaskInput,
        org: str,
        run: str,
    ) -> dict[str, Any] | None:
        """
        Complete process task

        Complete process task
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/runs"
            f"/{quote(str(run), safe='')}"
            f"/completed-tasks"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def reopen_process_task_async(
        self,
        org: str,
        run: str,
        task: str,
    ) -> dict[str, Any] | None:
        """
        Reopen process Task

        Reopen process task
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/runs"
            f"/{quote(str(run), safe='')}"
            f"/completed-tasks"
            f"/{quote(str(task), safe='')}"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def comment_task_async(
        self,
        input: CommentTaskInput,
        org: str,
        task: str,
    ) -> dict[str, Any] | None:
        """
        Add comment, report issue, resolve issue on a task

        task deadline, in date-time format
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/tasks"
            f"/{quote(str(task), safe='')}"
            f"/comment"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_task_async(
        self,
        input: CreateTaskInput,
        org: str,
    ) -> dict[str, Any] | None:
        """
        Create a task

        Create Task
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/processes"
            f"/micro-functions"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/tasks"
        )

        response = await self.http_client.send_async(
            "POST", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def edit_task_deadline_async(
        self,
        input: EditTaskDeadlineInput,
        org: str,
        task: str,
    ) -> dict[str, Any] | None:
        """
        Edit task deadline

        Edit deadline of a task
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/processes"
            f"/micro-functions"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/tasks"
            f"/{quote(str(task), safe='')}"
            f"/edit-deadline"
        )

        response = await self.http_client.send_async(
            "PUT", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def remove_guest_async(
        self,
        org: str,
        task: str,
        guest: str,
    ) -> dict[str, Any] | None:
        """
        Remove guest assigned

        Remove guest of a task
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/processes"
            f"/micro-functions"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/tasks"
            f"/{quote(str(task), safe='')}"
            f"/remove-guest"
            f"/{quote(str(guest), safe='')}"
        )

        response = await self.http_client.send_async(
            "PUT", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def remove_assignee_async(
        self,
        org: str,
        task: str,
        member: str,
    ) -> dict[str, Any] | None:
        """
        Remove assignee

        Remove assignee of a task
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/processes"
            f"/micro-functions"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/tasks"
            f"/{quote(str(task), safe='')}"
            f"/remove-assignee"
            f"/{quote(str(member), safe='')}"
        )

        response = await self.http_client.send_async(
            "PUT", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def edit_step_type_async(
        self,
        input: EditStepTypeInput,
        org: str,
        blueprint: str,
        step: str,
    ) -> dict[str, Any] | None:
        """
        Edit step type

        Edit step type
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/processes"
            f"/micro-functions"
            f"/organizations"
            f"/{quote(str(org), safe='')}"
            f"/blueprints"
            f"/{quote(str(blueprint), safe='')}"
            f"/steps"
            f"/{quote(str(step), safe='')}"
            f"/edit-step-type"
        )

        response = await self.http_client.send_async(
            "PUT", request_url, body=input
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "PUT",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_user_organizations_async(
        self,
    ) -> dict[str, Any] | None:
        """
        Get user's organizations

        Get user's organizations
        """
        request_url = f"{self._connection_runtime_url}/me/organizations"

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_organization_users_async(
        self,
        org: str,
    ) -> dict[str, Any] | None:
        """
        Get organization's users

        Get all users belonging to an organization
        """
        request_url = (
            f"{self._connection_runtime_url}"
            f"/organizations/{quote(str(org), safe='')}/users"
        )

        response = await self.http_client.send_async(
            "GET", request_url, body=None
        )

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                request_url,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)
