# Copyright (c) Microsoft Corporation. All rights reserved.

# TeamsClient.py - Auto-generated DirectClient SDK
# Do not edit this file directly.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Any, Dict, List
from datetime import datetime
from urllib.parse import quote
import json

from azure.connectors.sdk import (
    ConnectorClientBase,
    ConnectorClientOptions,
    TokenProvider,
    ManagedIdentityTokenProvider,
    ConnectorException,
)


# Type Definitions

@dataclass
class NewMeetingResponse:
    """Response for Create a Teams meeting"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class GetAllTeamsResponse:
    """Response for List joined teams"""

    context: Optional[str] = None
    value: Optional[List[Dict[str, Any]]] = None
    """List of the teams you are a member of"""


@dataclass
class GetAllAssociatedTeamsResponse:
    """Response for List associated teams"""

    context: Optional[str] = None
    value: Optional[List[AssociatedTeamInfo]] = None
    """List of the teams you are associated with"""


@dataclass
class GetChannelsForGroupResponse:
    """Response for List channels"""

    context: Optional[str] = None
    value: Optional[List[GetChannelResponse]] = None
    """List of one or more channels for a specific team"""


@dataclass
class CreateChannelInput:
    """Create a channel"""

    description: Optional[str] = None
    """Optional textual description for the channel"""
    display_name: Optional[str] = None
    """Channel name as it appears in Microsoft Teams"""


@dataclass
class CreateChannelResponse:
    """Response for Create a channel"""

    description: Optional[str] = None
    """Optional textual description for the channel"""
    display_name: Optional[str] = None
    """Channel name as it appears in Microsoft Teams"""
    id: Optional[str] = None
    """The channel's unique identifier"""


@dataclass
class GetChannelResponse:
    """Response for Get details for a specific channel in a team"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class GetAllChannelsForTeamResponse:
    """Response for List all channels"""

    context: Optional[str] = None
    value: Optional[List[ChannelWithOwnerTeamId]] = None
    """List of one or more channels for a specific team"""


@dataclass
class GetChatsResponse:
    """Response for List chats"""

    context: Optional[str] = None
    value: Optional[List[Dict[str, Any]]] = None
    """List of one or more chats you are a part of"""


@dataclass
class GetTagsResponseSchema:
    """Response for List all tags for a team"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class CreateTagInput:
    """Create a tag for a team"""

    display_name: Optional[str] = None
    """The name of the tag as it appears to the user in Microsoft Teams."""
    members: Optional[str] = None
    """
    List of users' IDs separated by semi-colons, identifier must be in a format
    like '550e8400-e29b-41d4-a716-446655440000'.
    """


@dataclass
class CreateTagResponseSchema:
    """Response for Create a tag for a team"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class AddMemberToTagInput:
    """Add a member to a team tag"""

    user_id: Optional[str] = None
    """
    The user's ID of the member to add to the tag, must be in a format like
    '550e8400-e29b-41d4-a716-446655440000'.
    """


@dataclass
class AddMemberToTagResponseSchema:
    """Response for Add a member to a team tag"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class GetTagMembersResponseSchema:
    """Response for List the members of a team tag"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class AtMentionTagResponse:
    """Response for Get an @mention token for a team tag"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class GetMessagesFromConversationResponse:
    """Response for Get messages in a channel"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicGetMessageDetailsResponseSchema:
    """Response for Get message details"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ListRepliesResponseSchema:
    """Response for List replies of a channel message"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ListMembersResponseSchema:
    """Response for List members"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ChatMessageList:
    """Response for When a new channel message is added"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookChatMessageTriggerInput:
    """When a new chat message is added"""

    notification_url: Optional[str] = None


@dataclass
class GetTeamResponse:
    """Response for Get a team"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class AtMentionUser:
    """Response for Get an @mention token for a user"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class OnGroupMemberChangeResponse:
    """Response for When a new team member is removed"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class NewChatResponse:
    """Response for Create a chat"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class CreateATeamInput:
    """Create a team"""

    display_name: Optional[str] = None
    """The name of the team"""
    description: Optional[str] = None
    """An optional description for the team"""
    visibility: Optional[str] = None
    """The visibility of the the team"""


@dataclass
class CreateATeamResponse:
    """Response for Create a team"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class AddMemberToTeamInput:
    """Add a member to a team"""

    user_id: Optional[str] = None
    """User principal name or Microsoft Entra ID to add"""
    owner: Optional[bool] = None
    """True, if the user should be a team owner"""


@dataclass
class AddMemberToChannelInput:
    """Add a member to a channel"""

    user_id: Optional[str] = None
    """User principal name or Microsoft Entra ID to add"""
    owner: Optional[bool] = None
    """True, if the user should be a channel owner"""


@dataclass
class PostToConversationResponse:
    """Response for Post message in a chat or channel"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class PostCardAndWaitForResponseInput:
    """Post adaptive card and wait for a response"""

    notification_url: Optional[str] = None
    body: Optional[Dict[str, Any]] = None


@dataclass
class DynamicPostGatherInputToConversationResponse:
    """Response for Post adaptive card and wait for a response"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class HttpRequestInput:
    """Send a Microsoft Graph HTTP request"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ObjectWithoutType:
    """Response for Send a Microsoft Graph HTTP request"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ObjectEntity:
    """Definition: Object"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ConnectorMetadata:
    """Definition: ConnectorMetadata"""

    metadatatype: Optional[str] = None
    activitytype: Optional[str] = None
    schema: Optional[ObjectEntity] = None


@dataclass
class PostFeedSchema:
    """Definition: PostFeedSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class PostMessageSchema:
    """Definition: PostMessageSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class PostCardSchema:
    """Definition: PostCardSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class PostCardAndWaitSchema:
    """Definition: PostCardAndWaitSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class UnifiedActionSchema:
    """Definition: UnifiedActionSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class GetMessageDetailsSchema:
    """Definition: GetMessageDetailsSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class ListMembersSchema:
    """Definition: ListMembersSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class DynamicGetMessageDetailsSchema:
    """Definition: DynamicGetMessageDetailsSchema"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicListMembersSchema:
    """Definition: DynamicListMembersSchema"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicUserNotificationRequest:
    """Definition: DynamicUserNotificationRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicPostConversationNotificationRequest:
    """Definition: DynamicPostConversationNotificationRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicChannelNotificationRequest:
    """Definition: DynamicChannelNotificationRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicPostFeedNotificationRequest:
    """Definition: DynamicPostFeedNotificationRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicPostMessageRequest:
    """Definition: DynamicPostMessageRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicReplyMessageRequest:
    """Definition: DynamicReplyMessageRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicPostCardRequest:
    """Definition: DynamicPostCardRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicPostCardAndWaitRequest:
    """Definition: DynamicPostCardAndWaitRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicReplyCardRequest:
    """Definition: DynamicReplyCardRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicUpdateCardRequest:
    """Definition: DynamicUpdateCardRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicUserAdaptiveCardRequest:
    """Definition: DynamicUserAdaptiveCardRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicChannelAdaptiveCardRequest:
    """Definition: DynamicChannelAdaptiveCardRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicUserMessageWithOptionsSubscriptionRequest:
    """Definition: DynamicUserMessageWithOptionsSubscriptionRequest"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicUserMessageWithOptionsSubscriptionResult:
    """Definition: DynamicUserMessageWithOptionsSubscriptionResult"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicSelectedMessageTriggerResult:
    """Definition: DynamicSelectedMessageTriggerResult"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicComposeMessageTriggerResult:
    """Definition: DynamicComposeMessageTriggerResult"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicCardResponseTriggerResult:
    """Definition: DynamicCardResponseTriggerResult"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookTriggerSchema:
    """Definition: WebhookTriggerSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class MessageReactionWebhookResponseSchema:
    """Definition: MessageReactionWebhookResponseSchema"""

    thread_type: Optional[str] = None
    chat_id: Optional[str] = None
    """The chat's unique identifier"""
    team_id: Optional[str] = None
    """The team's unique identifier"""
    channel_id: Optional[str] = None
    """The channel's unique identifier"""
    message_id: Optional[str] = None
    """Id of the message which was reacted"""
    reply_to_id: Optional[str] = None
    """ID of the parent message of the thread"""
    message_link: Optional[str] = None
    """Link to the message which was reacted"""
    user_id: Optional[str] = None
    """Reacting user's Id"""
    message_reaction: Optional[str] = None
    """Message reaction used"""


@dataclass
class ChatMessageWebhookResponseSchema:
    """Definition: ChatMessageWebhookResponseSchema"""

    value: Optional[List[Dict[str, Any]]] = None
    """Message details response"""


@dataclass
class DynamicWebhookTriggerRequestSchema:
    """Definition: DynamicWebhookTriggerRequestSchema"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicKeywordWebhookTriggerResponseSchema:
    """Definition: DynamicKeywordWebhookTriggerResponseSchema"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicAtMentionWebhookTriggerResponseSchema:
    """Definition: DynamicAtMentionWebhookTriggerResponseSchema"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicNewMessageWebhookTriggerResponseSchema:
    """Definition: DynamicNewMessageWebhookTriggerResponseSchema"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicPostToConversationResponse:
    """Definition: DynamicPostToConversationResponse"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicResponseSchema:
    """Definition: DynamicResponseSchema"""

    schema: Optional[ObjectEntity] = None


@dataclass
class MessageId:
    """Definition: MessageId"""

    id: Optional[str] = None
    """Unique message identifier"""


@dataclass
class DynamicUserFlowContinuationSubscriptionResult:
    """Definition: DynamicUserFlowContinuationSubscriptionResult"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicChannelFlowContinuationSubscriptionResult:
    """Definition: DynamicChannelFlowContinuationSubscriptionResult"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class DynamicGatherInputSubscriptionResult:
    """Definition: DynamicGatherInputSubscriptionResult"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ChatMessage:
    """Definition: ChatMessage"""

    attachments: Optional[List[Dict[str, Any]]] = None
    """attachments"""
    body: Optional[Dict[str, Any]] = None
    """Plaintext representation of the content of the message"""
    created_date_time: Optional[str] = None
    """Timestamp of when the chat message was created"""
    deleted: Optional[bool] = None
    """deleted"""
    etag: Optional[str] = None
    """Version number of the chat message."""
    from_: Optional[Dict[str, Any]] = None
    """The message sender"""
    id: Optional[str] = None
    """Unique ID of the message"""
    importance: Optional[str] = None
    """
    The importance of the message. The possible values are: normal, high,
    urgent.
    """
    last_modified_date_time: Optional[str] = None
    """
    Timestamp when the chat message is created (initial setting) or modified,
    including when a reaction is added or removed
    """
    locale: Optional[str] = None
    """Locale of the chat message set by the client."""
    mentions: Optional[List[Dict[str, Any]]] = None
    """
    List of entities mentioned in the chat message. Supported entities are:
    user, bot, team, and channel.
    """
    message_type: Optional[str] = None
    """The type of chat message"""
    reactions: Optional[List[Dict[str, Any]]] = None
    """Reactions for this chat message (for example, Like)"""
    reply_to_id: Optional[str] = None
    """ID of the parent message of the thread"""
    subject: Optional[str] = None
    """The subject of the chat message, optional"""
    summary: Optional[str] = None
    """
    Summary text of the message that could be used for push notifications and
    summary views or fall back views
    """


@dataclass
class AssociatedTeamInfo:
    """Definition: AssociatedTeamInfo"""

    id: Optional[str] = None
    """The unique identifier of the team"""
    display_name: Optional[str] = None
    """The name of the team"""
    tenant_id: Optional[str] = None
    """The ID of the Microsoft Entra tenant this team belongs to"""


@dataclass
class ChannelWithOwnerTeamId:
    """Definition: ChannelWithOwnerTeamId"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class WebhookRequest:
    """Definition: WebhookRequest"""

    notification_url: Optional[str] = None
    """
    Specify a well-formed URL of the endpoint that will receive notifications
    """


@dataclass
class GetTimeOffReasonsResponse:
    """Definition: GetTimeOffReasonsResponse"""

    context: Optional[str] = None
    value: Optional[List[Dict[str, Any]]] = None
    """The list of time off reasons."""


@dataclass
class TimeOffRequestResponse:
    """Definition: TimeOffRequestResponse"""

    id: Optional[str] = None
    """The unique ID of the TimeOff request."""
    created_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    last_modified_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    assigned_to: Optional[str] = None
    """The person the request is assigned to: 'manager' or 'recipient'"""
    state: Optional[str] = None
    """'approved', 'pending' or 'declined'"""
    sender_date_time: Optional[str] = None
    """Time when the request was sent"""
    sender_message: Optional[str] = None
    """The message from the request sender"""
    sender_user_id: Optional[str] = None
    """The ID of the user that sent the request"""
    manager_action_date_time: Optional[str] = None
    """Time when the manager responded"""
    manager_action_message: Optional[str] = None
    """The message from the manager"""
    manager_user_id: Optional[str] = None
    """The ID of the manager that responded"""
    start_date_time: Optional[str] = None
    """Start of time requested off"""
    end_date_time: Optional[str] = None
    """End of time requested off"""
    time_off_reason_id: Optional[str] = None
    """The ID of the TimeOff Reason"""


@dataclass
class OfferShiftRequestResponse:
    """Definition: OfferShiftRequestResponse"""

    id: Optional[str] = None
    """The unique ID of the Offer Shift request."""
    created_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    last_modified_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    assigned_to: Optional[str] = None
    """The person the request is assigned to: 'manager' or 'recipient'"""
    state: Optional[str] = None
    """'approved', 'pending' or 'declined'"""
    sender_date_time: Optional[str] = None
    """Time when the request was sent"""
    sender_message: Optional[str] = None
    """The message from the request sender"""
    sender_user_id: Optional[str] = None
    """The ID of the user that sent the request"""
    sender_shift_id: Optional[str] = None
    """The ID of the shift from the sender"""
    recipient_action_date_time: Optional[str] = None
    """Time when the recipient responded"""
    recipient_action_message: Optional[str] = None
    """The message from the recipient"""
    recipient_user_id: Optional[str] = None
    """The ID of the recipient of the request"""
    manager_action_date_time: Optional[str] = None
    """Time when the manager responded"""
    manager_action_message: Optional[str] = None
    """The message from the manager"""
    manager_user_id: Optional[str] = None
    """The ID of the manager that responded"""


@dataclass
class SwapShiftsChangeRequestResponse:
    """Definition: SwapShiftsChangeRequestResponse"""

    id: Optional[str] = None
    """The unique ID of the Swap Shift request."""
    created_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    last_modified_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    assigned_to: Optional[str] = None
    """The person the request is assigned to: 'manager' or 'recipient'"""
    state: Optional[str] = None
    """'approved', 'pending' or 'declined'"""
    sender_date_time: Optional[str] = None
    """Time when the request was sent"""
    sender_message: Optional[str] = None
    """The message from the request sender"""
    sender_user_id: Optional[str] = None
    """The ID of the user that sent the request"""
    sender_shift_id: Optional[str] = None
    """The ID of the shift from the sender"""
    recipient_action_date_time: Optional[str] = None
    """Time when the recipient responded"""
    recipient_action_message: Optional[str] = None
    """The message from the recipient"""
    recipient_user_id: Optional[str] = None
    """The ID of the recipient of the request"""
    recipient_shift_id: Optional[str] = None
    """The ID of the shift from the recipient"""
    manager_action_date_time: Optional[str] = None
    """Time when the manager responded"""
    manager_action_message: Optional[str] = None
    """The message from the manager"""
    manager_user_id: Optional[str] = None
    """The ID of the manager that responded"""


@dataclass
class OpenShiftChangeRequestResponse:
    """Definition: OpenShiftChangeRequestResponse"""

    id: Optional[str] = None
    """The unique ID of the Open Shift Change request."""
    created_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    last_modified_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    assigned_to: Optional[str] = None
    """The person the request is assigned to: 'manager' or 'recipient'"""
    state: Optional[str] = None
    """'approved', 'pending' or 'declined'"""
    sender_date_time: Optional[str] = None
    """Time when the request was sent"""
    sender_message: Optional[str] = None
    """The message from the request sender"""
    sender_user_id: Optional[str] = None
    """The ID of the user that sent the request"""
    manager_action_date_time: Optional[str] = None
    """Time when the manager responded"""
    manager_action_message: Optional[str] = None
    """The message from the manager"""
    manager_user_id: Optional[str] = None
    """The ID of the manager that responded"""
    open_shift_id: Optional[str] = None
    """The ID of the open shift being requested"""


@dataclass
class EditOpenShiftRequest:
    """Definition: EditOpenShiftRequest"""

    scheduling_group_id: Optional[str] = None
    """Scheduling Group ID"""
    shared_open_shift: Optional[Dict[str, Any]] = None


@dataclass
class OpenShiftResponse:
    """Definition: OpenShiftResponse"""

    id: Optional[str] = None
    """The unique ID of the open shift."""
    created_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    last_modified_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    scheduling_group_id: Optional[str] = None
    """Scheduling Group ID"""
    last_modified_by: Optional[LastModifiedBy] = None
    shared_open_shift: Optional[SharedOpenShift] = None
    draft_open_shift: Optional[DraftOpenShift] = None


@dataclass
class SharedOpenShift:
    """Definition: SharedOpenShift"""

    display_name: Optional[str] = None
    """Display Name"""
    notes: Optional[str] = None
    """Notes"""
    start_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    end_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    theme: Optional[str] = None
    """Theme"""
    open_slot_count: Optional[int] = None
    """Open Slot Count"""
    activities: Optional[Activities] = None


@dataclass
class DraftOpenShift:
    """Definition: DraftOpenShift"""

    display_name: Optional[str] = None
    """Display Name"""
    notes: Optional[str] = None
    """Notes"""
    start_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    end_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    theme: Optional[str] = None
    """Theme"""
    open_slot_count: Optional[int] = None
    """Open Slot Count"""
    activities: Optional[Activities] = None


@dataclass
class ShiftResponse:
    """Definition: ShiftResponse"""

    id: Optional[str] = None
    """The unique ID of the shift."""
    created_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    last_modified_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    user_id: Optional[str] = None
    """Assigned To User ID"""
    scheduling_group_id: Optional[str] = None
    """Scheduling Group ID"""
    last_modified_by: Optional[LastModifiedBy] = None
    shared_shift: Optional[SharedShift] = None
    draft_shift: Optional[DraftShift] = None


@dataclass
class SharedShift:
    """Definition: SharedShift"""

    display_name: Optional[str] = None
    """Display Name"""
    notes: Optional[str] = None
    """Notes"""
    start_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    end_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    theme: Optional[str] = None
    """Theme"""
    activities: Optional[Activities] = None


@dataclass
class DraftShift:
    """Definition: DraftShift"""

    display_name: Optional[str] = None
    """Display Name"""
    notes: Optional[str] = None
    """Notes"""
    start_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    end_date_time: Optional[str] = None
    """yyyy-MM-ddTHH:mm:ss.fffZ (UTC format)"""
    theme: Optional[str] = None
    """Theme"""
    activities: Optional[Activities] = None


@dataclass
class ScheduleResponse:
    """Definition: ScheduleResponse"""

    id: Optional[str] = None
    """The unique ID of the schedule."""
    time_zone: Optional[str] = None
    """The Time Zone of the schedule."""
    provision_status: Optional[str] = None
    """The Provision Status of the schedule."""
    provision_status_code: Optional[str] = None
    """The Provision Status Code of the schedule."""


@dataclass
class ThemeEditor:
    """Definition: ThemeEditor"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class Activities:
    """Definition: Activities"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class SchedulingGroupResponse:
    """Definition: SchedulingGroupResponse"""

    id: Optional[str] = None
    """The unique ID of the scheduling group."""
    display_name: Optional[str] = None
    """The display name for the scheduling group."""
    is_active: Optional[bool] = None
    """
    Indicates whether the scheduling group can be used when creating new
    entities or updating existing ones.
    """
    user_ids: Optional[List[str]] = None
    """List of IDs of users in the scheduling group."""


@dataclass
class AtMentionUserV1:
    """Definition: AtMentionUser_V1"""

    at_mention: Optional[str] = None
    """
    An @mention token for the user. This property can be inserted into messages
    """


@dataclass
class BotMentionRequest:
    """Definition: BotMentionRequest"""

    bot_id: Optional[str] = None
    """The bot's unique identifier (GUID)"""
    app_id: Optional[str] = None
    """The bot's app identifier (GUID)"""
    name: Optional[str] = None
    """The bot's display name"""


@dataclass
class AtMentionBotResponse:
    """Definition: AtMentionBotResponse"""

    at_mention: Optional[str] = None
    """
    An @mention token for the bot. This property can be inserted into messages
    and adaptive cards
    """


@dataclass
class ChannelIdForTeam:
    """Definition: ChannelIdForTeam"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class ChannelIds:
    """Definition: ChannelIds"""

    channel: Optional[ChannelIdForTeam] = None


@dataclass
class ChatId:
    """Definition: ChatId"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class BotIdForChat:
    """Definition: BotIdForChat"""

    additional_properties: Dict[str, Any] = field(default_factory=dict)
    """
    Dynamic properties determined at runtime
    (similar to .NET [JsonExtensionData])
    """


@dataclass
class NewChat:
    """Definition: NewChat"""

    topic: Optional[str] = None
    """Title, displayed only in group chats"""
    members: Optional[str] = None
    """User's IDs, separated by semicolons"""


@dataclass
class NewMeeting:
    """Definition: NewMeeting"""

    subject: Optional[str] = None
    """The text of the event's subject line"""
    body: Optional[Dict[str, Any]] = None
    """The body of the message associated with the event"""
    time_zone: Optional[str] = None
    """Time zone of the event"""
    start: Optional[Dict[str, Any]] = None
    end: Optional[Dict[str, Any]] = None
    required_attendees: Optional[str] = None
    """Required attendees for the event separated by semicolons"""
    optional_attendees: Optional[str] = None
    """Optional attendees for the event separated by semicolons"""
    location: Optional[Dict[str, Any]] = None
    """The location of the event"""
    importance: Optional[str] = None
    """The importance of the event: low, normal or high"""
    recurrence: Optional[Dict[str, Any]] = None
    """The recurrence pattern for the meeting"""
    is_all_day: Optional[bool] = None
    """Set to true if the event lasts all day"""
    reminder_minutes_before_start: Optional[int] = None
    """
    The number of minutes before the event start time that the reminder alert
    occurs
    """
    is_reminder_on: Optional[bool] = None
    """Set to true if an alert is set to remind the user of the event"""
    show_as: Optional[str] = None
    """Status to show during the event"""
    response_requested: Optional[bool] = None
    """
    Set to true if the sender would like a response when the event is accepted
    """
    is_online_meeting: Optional[bool] = None
    """Set to true, if the meeting should have an online meeting provider"""
    online_meeting_provider: Optional[str] = None
    """Represents the online meeting service provider"""


@dataclass
class LastModifiedBy:
    """Definition: LastModifiedBy"""

    application: Optional[str] = None
    """Application"""
    device: Optional[str] = None
    """Device"""
    conversation: Optional[str] = None
    """Conversation"""
    user: Optional[Dict[str, Any]] = None
    """User"""


@dataclass
class MemberSettings:
    """Definition: MemberSettings"""

    allow_create_update_channels: Optional[bool] = None
    """If set to true, members can add and update channels"""
    allow_delete_channels: Optional[bool] = None
    """If set to true, members can delete channels"""
    allow_add_remove_apps: Optional[bool] = None
    """If set to true, members can add and remove apps"""
    allow_create_update_remove_tabs: Optional[bool] = None
    """If set to true, members can add, update, and remove tabs"""
    allow_create_update_remove_connectors: Optional[bool] = None
    """If set to true, members can add, update, and remove connectors"""


@dataclass
class GuestSettings:
    """Definition: GuestSettings"""

    allow_create_update_channels: Optional[bool] = None
    """If set to true, guests can add and update channels"""
    allow_delete_channels: Optional[bool] = None
    """If set to true, guests can delete channels"""


@dataclass
class MessagingSettings:
    """Definition: MessagingSettings"""

    allow_user_edit_messages: Optional[bool] = None
    """If set to true, users can edit their messages"""
    allow_user_delete_messages: Optional[bool] = None
    """If set to true, users can delete their messages"""
    allow_owner_delete_messages: Optional[bool] = None
    """If set to true, owners can delete any message"""
    allow_team_mentions: Optional[bool] = None
    """If set to true, @team mentions are allowed"""
    allow_channel_mentions: Optional[bool] = None
    """If set to true, @channel mentions are allowed"""


@dataclass
class FunSettings:
    """Definition: FunSettings"""

    allow_giphy: Optional[bool] = None
    """If set to true, enables Giphy use"""
    giphy_content_rating: Optional[str] = None
    """Giphy content rating. Possible values are: moderate, strict"""
    allow_stickers_and_memes: Optional[bool] = None
    """If set to true, enables users to include stickers and memes"""
    allow_custom_memes: Optional[bool] = None
    """If set to true, enables users to include custom memes"""


@dataclass
class DiscoverySettings:
    """Definition: DiscoverySettings"""

    show_in_teams_search_and_suggestions: Optional[bool] = None
    """
    If set to true, the team is visible via search and suggestions from the
    Teams client
    """


@dataclass
class SelectedMessageTriggerMetadata:
    """Definition: SelectedMessageTriggerMetadata"""

    teams_flow_run_context: Optional[ObjectEntity] = None
    card_outputs: Optional[ObjectEntity] = None


@dataclass
class ComposeMessageTriggerMetadata:
    """Definition: ComposeMessageTriggerMetadata"""

    teams_flow_run_context: Optional[ObjectEntity] = None
    card_outputs: Optional[ObjectEntity] = None


@dataclass
class CardResponseTriggerMetadata:
    """Definition: CardResponseTriggerMetadata"""

    teams_flow_run_context: Optional[ObjectEntity] = None
    card_outputs: Optional[ObjectEntity] = None


@dataclass
class VirtualAgentBots:
    """Definition: VirtualAgentBots"""

    context: Optional[str] = None
    value: Optional[List[Dict[str, Any]]] = None
    """List of the Microsoft Copilot Studio agents"""


# Client Class

class TeamsClient(ConnectorClientBase):
    """Typed client for teams connector."""

    def __init__(
        self,
        connection_runtime_url: str,
        token_provider: Optional[TokenProvider] = None,
        options: Optional[ConnectorClientOptions] = None,
    ):
        """
        Initialize a TeamsClient.

        Args:
            connection_runtime_url: The connection runtime
                URL from Azure Portal.
            token_provider: Optional token provider.
                Defaults to ManagedIdentityTokenProvider.
            options: Optional connector client options.
        """
        if not connection_runtime_url:
            raise ValueError("connection_runtime_url cannot be None or empty")

        if token_provider is None:
            token_provider = ManagedIdentityTokenProvider()

        super().__init__(token_provider, options)
        self._connection_runtime_url = connection_runtime_url.rstrip('/')

    @property
    def connector_name(self) -> str:
        return "teams"

    async def create_teams_meeting_async(
        self,
        input: NewMeeting,
        calendarid: str,
    ):
        """
        Create a Teams meeting

        Create a meeting with a link at the bottom of the invite to join the
        meeting online on Microsoft Teams.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/v1.0/me/calendars/{str(calendarid)}/events"
        )

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_all_teams_async(
        self,
    ):
        """
        List joined teams

        Lists all the teams in Microsoft Teams that you are a member of
        """
        path = f"{self._connection_runtime_url}/beta/me/joinedTeams"

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def get_all_associated_teams_async(
        self,
    ):
        """
        List associated teams

        Lists all the teams you are a direct member of, or are a member of a
        shared channel that is hosted inside the team.
        """
        path = (
            f"{self._connection_runtime_url}/v1.0/me/teamwork/associatedTeams"
        )

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def webhook_chat_message_trigger_async(
        self,
        input: WebhookChatMessageTriggerInput,
    ):
        """
        When a new chat message is added

        Triggers when a new message is posted in any chat the user is a part
        of.
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/beta/subscriptions/chatmessagetrigger"
        )

        await self.http_client.send_async("POST", path, body=input)

    async def subscribe_user_message_with_options_async(
        self,
        input: DynamicUserMessageWithOptionsSubscriptionRequest,
    ):
        """
        Post a choice of options as the Flow bot to a user

        Send a set of options to a Microsoft Teams user, that they must respond
        to before the flow will continue. This action will pause the flow until
        the user response to the options
        """
        path = (
            f"{self._connection_runtime_url}"
            f"/flowbot"
            f"/actions"
            f"/messagewithoptions"
            f"/recipienttypes"
            f"/user"
            f"/$subscriptions"
        )

        await self.http_client.send_async("POST", path, body=input)

    async def at_mention_user_async(
        self,
        user_id: str,
    ):
        """
        Get an @mention token for a user

        Creates a token that can be inserted into a message or adaptive card to
        @mention a user.
        """
        path = f"{self._connection_runtime_url}/v1.0/users/{str(user_id)}"

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def on_group_membership_removal_async(
        self,
        select: Optional[str] = None,
    ):
        """
        When a new team member is removed

        Triggers when a member is removed from the specified team
        """
        path = f"{self._connection_runtime_url}/trigger/v1.0/groups/removal"
        query_params = []
        if select is not None:
            value = str(select)
            if isinstance(select, bool):
                value = value.lower()
            query_params.append(f"$select={quote(value)}")
        if query_params:
            path += '?' + '&'.join(query_params)

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def on_group_membership_add_async(
        self,
        select: Optional[str] = None,
    ):
        """
        When a new team member is added

        Triggers when a member is added to the given team
        """
        path = f"{self._connection_runtime_url}/trigger/v1.0/groups/delta"
        query_params = []
        if select is not None:
            value = str(select)
            if isinstance(select, bool):
                value = value.lower()
            query_params.append(f"$select={quote(value)}")
        if query_params:
            path += '?' + '&'.join(query_params)

        response = await self.http_client.send_async("GET", path, body=None)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "GET",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_chat_async(
        self,
        input: NewChat,
    ):
        """
        Create a chat

        Creates a one on one or group chat
        """
        path = f"{self._connection_runtime_url}/beta/chats"

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def create_a_team_async(
        self,
        input: CreateATeamInput,
    ):
        """
        Create a team

        Creates a new team in Microsoft Teams
        """
        path = f"{self._connection_runtime_url}/beta/teams"

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)

    async def http_request_async(
        self,
        input: HttpRequestInput,
    ):
        """
        Send a Microsoft Graph HTTP request

        Construct a Microsoft Graph REST API request to invoke against the
        Microsoft Teams endpoints. These segments are supported: 1st segment:
        /teams, /me, /users 2nd segment: channels, chats, installedApps,
        messages, pinnedMessages, onlineMeetings. Learn more:
        https://docs.microsoft.com/en-us/graph/use-the-api
        """
        path = f"{self._connection_runtime_url}/httprequest"

        response = await self.http_client.send_async("POST", path, body=input)

        if not (200 <= response.status < 300):
            raise ConnectorException(
                "POST",
                path,
                response.status,
                response.text,
            )

        if not response.text:
            return None

        return json.loads(response.text)
