jobs:
  - job: "Build"
    displayName: 'Build Connectors SDK'

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    templateContext:
      outputParentDirectory: $(Build.ArtifactStagingDirectory)
      outputs:
        - output: pipelineArtifact
          targetPath: $(Build.SourcesDirectory)
          artifactName: "azure-connectors"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.13"
      - bash: |
          python --version
        displayName: 'Check python version'
      - task: PipAuthenticate@1
        displayName: 'Pip Authenticate'
        inputs:
          artifactFeeds: 'internal/PythonSDK_Internal_PublicPackages'
      - bash: |
          python -m pip install -U pip
          python -m pip install build
          cd src
          python -m build
        displayName: 'Build Connectors SDK'
