{
 "swagger": "2.0",
 "info": {
  "version": "1.0",
  "title": "Word Online (Business)",
  "description": "Word Online (Business) connector lets you work with Word files in document libraries supported by Microsoft Graph (OneDrive for Business, SharePoint Online Sites, and Office 365 Groups).",
  "contact": {
   "name": "Microsoft",
   "url": "https://learn.microsoft.com/en-us/connectors/wordonlinebusiness/",
   "email": "idcknowledgeeco@microsoft.com"
  }
 },
 "host": "logic-apis-westus.azure-apim.net",
 "basePath": "/apim/wordonlinebusiness",
 "schemes": [
  "https"
 ],
 "paths": {
  "/{connectionId}/api/templates/schema": {
   "get": {
    "summary": "Fetches the schema of the selected file",
    "description": "Fetches the schema of the selected file.",
    "operationId": "GetFileSchema",
    "deprecated": false
   }
  },
  "/{connectionId}/api/templates/getFile": {
   "post": {
    "summary": "Populate a Microsoft Word template",
    "description": "Reads a Microsoft Word template to then fill the template fields with selected dynamic values to generate a Word Document.",
    "operationId": "CreateFileItem",
    "parameters": [
     {
      "name": "connectionId",
      "in": "path",
      "required": true,
      "type": "string"
     },
     {
      "$ref": "#/parameters/source"
     },
     {
      "$ref": "#/parameters/queryDrive"
     },
     {
      "$ref": "#/parameters/file"
     },
     {
      "name": "dynamicFileSchema",
      "in": "body",
      "description": "Dynamic Schema of items in selected File",
      "schema": {
       "type": "object",
       "x-ms-dynamic-schema": {
        "operationId": "GetFileSchema",
        "value-path": "items"
       }
      }
     }
    ],
    "deprecated": false
   }
  },
  "/{connectionId}/api/templates/createWordFileWithContent": {
   "post": {
    "summary": "Create a Microsoft Word document with the given content",
    "description": "Creates a Microsoft Word file with the given content in the root directory (use only from Copilot Studio)",
    "operationId": "CreateWordFileWithContent",
    "deprecated": false
   }
  },
  "/{connectionId}/codeless/v1.0/sources": {
   "get": {
    "summary": "Get sources",
    "description": "Get a list of sources.",
    "operationId": "GetSources",
    "deprecated": false
   }
  },
  "/{connectionId}/codeless/v1.0/drives": {
   "get": {
    "summary": "Get drives",
    "description": "Get a list of drives.",
    "operationId": "GetDrives",
    "parameters": [
     {
      "name": "connectionId",
      "in": "path",
      "required": true,
      "type": "string"
     },
     {
      "name": "source",
      "in": "query",
      "description": "Select from the drop-down or specify one of the following:\r\n              - \"me\"\r\n              - \"SharePoint Site URL\"\r\n              - \"users/someone's UPN\"\r\n              - \"groups/group Id\"\r\n              - \"sites/SharePoint Site URL:/teams/team name:\" (colons are required).",
      "required": true,
      "x-ms-dynamic-values": {
       "operationId": "GetSources",
       "value-path": "id",
       "value-title": "displayName",
       "value-collection": "value"
      },
      "type": "string",
      "default": "me"
     },
     {
      "name": "$select",
      "in": "query",
      "description": "Select.",
      "required": false,
      "type": "string",
      "default": ""
     }
    ],
    "deprecated": false
   }
  },
  "/{connectionId}/codeless/v1.0/drives/{drive}/root/children": {
   "get": {
    "summary": "List the root folder",
    "description": "List the root folder.",
    "operationId": "ListRootFolder",
    "deprecated": false
   }
  },
  "/{connectionId}/codeless/v1.0/drives/{drive}/items/{id}/children": {
   "get": {
    "summary": "List blobs under a given folder",
    "description": "List blobs under a given folder.",
    "operationId": "ListFolder",
    "parameters": [
     {
      "name": "connectionId",
      "in": "path",
      "required": true,
      "type": "string"
     },
     {
      "$ref": "#/parameters/source"
     },
     {
      "$ref": "#/parameters/drive"
     },
     {
      "name": "id",
      "in": "path",
      "description": "Folder Id.",
      "required": true,
      "x-ms-dynamic-tree": {
       "settings": {
        "canSelectParentNodes": true,
        "canSelectLeafNodes": false
       },
       "open": {
        "operationId": "ListRootFolder",
        "itemValuePath": "Id",
        "itemTitlePath": "DisplayName",
        "itemFullTitlePath": "Path",
        "itemIsParent": "(IsFolder eq true)"
       },
       "browse": {
        "operationId": "ListFolder",
        "itemValuePath": "Id",
        "itemTitlePath": "DisplayName",
        "itemFullTitlePath": "Path",
        "itemIsParent": "(IsFolder eq true)"
       }
      },
      "type": "string"
     }
    ],
    "deprecated": false
   }
  },
  "/{connectionId}/api/templates/convertFile": {
   "get": {
    "summary": "Convert Word Document to PDF",
    "description": "Gets a PDF version of the selected file",
    "operationId": "GetFilePDF"
   }
  }
 },
 "securityDefinitions": {
  "oauth2_auth": {
   "type": "oauth2",
   "flow": "accessCode",
   "authorizationUrl": "https://login.windows.net/common/oauth2/authorize",
   "tokenUrl": "https://login.windows.net/common/oauth2/authorize",
   "scopes": {
    "Files.Read": "Files.Read",
    "Files.ReadWrite": "Files.ReadWrite",
    "Files.Read.All": "Files.Read.All",
    "Files.ReadWrite.All": "Files.ReadWrite.All"
   }
  }
 },
 "security": [
  {
   "oauth2_auth": [
    "Files.Read",
    "Files.ReadWrite",
    "Files.Read.All",
    "Files.ReadWrite.All"
   ]
  }
 ],
 "x-ms-capabilities": {
  "file-picker": {
   "open": {
    "operationId": "ListRootFolder"
   },
   "browse": {
    "operationId": "ListFolder"
   },
   "value-title": "DisplayName",
   "value-folder-property": "IsFolder",
   "value-media-property": "MediaType"
  }
 },
 "parameters": {
  "source": {
   "name": "source",
   "in": "query",
   "required": true,
   "type": "string",
   "description": "Select from the drop-down or specify one of the following:\r\n              - \"me\"\r\n              - \"SharePoint Site URL\"\r\n              - \"users/someone's UPN\"\r\n              - \"groups/group Id\"\r\n              - \"sites/SharePoint Site URL:/teams/team name:\" (colons are required).",
   "x-ms-dynamic-values": {
    "operationId": "GetSources",
    "value-path": "id",
    "value-collection": "value",
    "value-title": "displayName"
   }
  },
  "drive": {
   "name": "drive",
   "in": "path",
   "required": true,
   "type": "string",
   "description": "Select a document library from the drop-down.",
   "x-ms-dynamic-values": {
    "operationId": "GetDrives",
    "value-path": "id",
    "value-collection": "value",
    "value-title": "name"
   }
  },
  "queryDrive": {
   "name": "drive",
   "in": "query",
   "description": "Select a document library from the drop-down.",
   "required": true,
   "x-ms-dynamic-values": {
    "operationId": "GetDrives",
    "value-collection": "value",
    "value-path": "id",
    "value-title": "name"
   },
   "type": "string"
  },
  "file": {
   "name": "file",
   "in": "query",
   "description": "Select a Word file through File Browse.",
   "required": true,
   "x-ms-dynamic-tree": {
    "settings": {
     "canSelectParentNodes": false,
     "canSelectLeafNodes": true
    },
    "open": {
     "operationId": "ListRootFolder",
     "itemValuePath": "Id",
     "itemTitlePath": "DisplayName",
     "itemFullTitlePath": "Path",
     "itemIsParent": "(IsFolder eq true)",
     "selectableFilter": "(MediaType eq 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')"
    },
    "browse": {
     "operationId": "ListFolder",
     "itemValuePath": "Id",
     "itemTitlePath": "DisplayName",
     "itemFullTitlePath": "Path",
     "itemIsParent": "(IsFolder eq true)",
     "selectableFilter": "(MediaType eq 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')"
    }
   },
   "type": "string"
  }
 }
}