[project]
name = "azure-connectors"
dynamic = ["version"]
requires-python = ">=3.10"
description = "Azure Connectors SDK for Python"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Azure Connector Namespaces team at Microsoft Corp.", email = "azurelogicapps@microsoft.com" }
]
keywords = ["azure", "connectors", "python", "serverless"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Typing :: Typed"
]
dependencies = [
    "aiohttp",
    "azure-identity[aio]",
]

[project.urls]
Documentation = "https://github.com/Azure/connectors-python-sdk"
Repository = "https://github.com/Azure/connectors-python-sdk"
Changelog = "https://github.com/Azure/connectors-python-sdk/blob/main/CHANGELOG.md"

[project.optional-dependencies]
dev = [
    "flake8>=6,<8",
    "mypy",
    "pytest",
    "pytest-asyncio",
    "httpx",  # For FastAPI testing
    "requests==2.*",
    "coverage",
    "pytest-sugar",
    "pytest-cov",
    "pytest-xdist",
    "pytest-randomly",
    "pytest-instafail",
    "pytest-rerunfailures",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = [
    'azure', 'docs', 'tests*', 'samples', 'scripts'
]

[tool.setuptools.dynamic]
version = {attr = "azure.connectors.__version__"}