[project]
name = "<TBD>"
version = "0.1.0dev1"
requires-python = ">=3.10"
description = "Azure Logic Apps Connector SDK for Python"
authors = [
    { name = "Azure Logic Apps team at Microsoft Corp.", email = "azurelogicapps@microsoft.com" }
]
keywords = ["azure", "connectors", "logic-apps",
            "python", "serverless"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers"
]
dependencies = [
    "aiohttp",
    "azure-identity-aio",
]

[project.urls]
Documentation = ""
Repository = ""

[project.optional-dependencies]
dev = [
    "flake8==6.*",
    "mypy",
    "pytest",
    "pytest-asyncio",
    "httpx",  # For FastAPI testing
    "requests==2.*",
    "coverage",
    "pytest-sugar",
    "pytest-cov",
    "pytest-xdist",
    "pytest-randomly",
    "pytest-instafail",
    "pytest-rerunfailures",
]

[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["azure.connectors"]


[tool.setuptools.package-data]
azure.connectors = ["py.typed"]
